// config.bin - 23:39:30 07/23/20, generated in 0.06 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class RC_V2 {
		units[] = {""};
		weapons[] = {"RC_nvg", "RC_nvg_antenna", "RC_sniper_armor_V2", "RC_tech_armor_V2", "RC_eod_armor_V2", "RC_sl_armor_V2", "RC_basic_armor_v2", "RC_Uniform", "RC_MPStealth_Uniform", "RC_MPRecon_Uniform", "RC_MPMarksman_Uniform", "RC_MPGunner_Uniform", "RC_YayaxCov_Uniform", "RC_YayaxDev_Uniform", "RC_YayaxJind_Uniform", "RC_YayaxYover_Uniform", "RC_AiwhaDikut_Uniform", "RC_AiwhaSarge_Uniform", "RC_AiwhaTyto_Uniform", "RC_AiwhaZag_Uniform", "RC_BravoRam_Uniform", "RC_Bravo2_Uniform", "RC_Bravo3_Uniform", "RC_Bravo4_Uniform", "RC_Omega_Uniform", "RC_DeltaFixer_Uniform", "RC_DeltaScorch_Uniform", "RC_DeltaSev_Uniform", "RC_backpack", "RC_RTO_Backpack", "RC_EOD_Backpack", "RC_Tech_Backpack"};
		author = "LastWarTeam";
		requiredAddons[] = {SWLB_CEE, "SWLB_clones"};
	};
};

class CfgFactionClasses {
	class LW_Faction {
		displayName = "LastWar";
	};
};

class CfgEditorSubcategories {
	class RC_V2 {
		displayName = "Republic Commando LW";
	};
};

class CfgWeapons {
	class SWLB_DeltaScorch_Helmet;	// External class reference
	class SWLB_DeltaFixer_Helmet;	// External class reference
	class SWLB_DeltaSev_Helmet;	// External class reference
	class SWLB_DeltaBoss_Helmet;	// External class reference
	class SWLB_MPStealth_Helmet;	// External class reference
	class SWLB_MPRecon_Helmet;	// External class reference
	class SWLB_MPGunner_Helmet;	// External class reference
	class SWLB_MPMarksman_Helmet;	// External class reference
	class SWLB_YayaxCov_Helmet;	// External class reference
	class SWLB_YayaxDev_Helmet;	// External class reference
	class SWLB_YayaxJind_Helmet;	// External class reference
	class SWLB_YayaxYover_Helmet;	// External class reference
	class SWLB_AiwhaDikut_Helmet;	// External class reference
	class SWLB_AiwhaSarge_Helmet;	// External class reference
	class SWLB_AiwhaTyto_Helmet;	// External class reference
	class SWLB_AiwhaZag_Helmet;	// External class reference
	class SWLB_BravoRam_Helmet;	// External class reference
	class SWLB_Bravo2_Helmet;	// External class reference
	class SWLB_Bravo3_Helmet;	// External class reference
	class SWLB_Bravo4_Helmet;	// External class reference
	class SWLB_MPStealth_Armor;	// External class reference
	class SWLB_MPRecon_Uniform;	// External class reference
	class SWLB_MPMarksman_Uniform;	// External class reference
	class SWLB_YayaxCov_Uniform;	// External class reference
	class SWLB_YayaxDev_Uniform;	// External class reference
	class SWLB_YayaxJind_Uniform;	// External class reference
	class SWLB_YayaxYover_Uniform;	// External class reference
	class SWLB_AiwhaDikut_Uniform;	// External class reference
	class SWLB_AiwhaSarge_Uniform;	// External class reference
	class SWLB_AiwhaTyto_Uniform;	// External class reference
	class SWLB_AiwhaZag_Uniform;	// External class reference
	class SWLB_Omega_Helmet;	// External class reference
	class SWLB_BravoRam_Uniform;	// External class reference
	class SWLB_Bravo2_Uniform;	// External class reference
	class SWLB_Bravo3_Uniform;	// External class reference
	class SWLB_Bravo4_Uniform;	// External class reference
	class SWLB_DeltaBoss_Uniform;	// External class reference
	class SWLB_DeltaFixer_Uniform;	// External class reference
	class SWLB_DeltaSev_Uniform;	// External class reference
	class SWLB_DeltaScorch_Uniform;	// External class reference
	class SWLB_Omega_Uniform;	// External class reference
	class SWLB_MPGunner_Uniform;	// External class reference
	class SWLB_clone_commando_uniform_k1;	// External class reference
	class SWLB_clone_commando_helmet_k1;	// External class reference
	class SWLB_clone_commando_basic_armor_k1;	// External class reference
	class SWLB_clone_commando_sniper_armor_k1;	// External class reference
	class SWLB_clone_commando_tech_armor_k1;	// External class reference
	class SWLB_clone_commando_eod_armor_k1;	// External class reference
	class SWLB_clone_commando_sl_armor_k1;	// External class reference
	class NVGoggles;	// External class reference
	class SWLB_clone_commando_nvg;	// External class reference
	class SWLB_clone_commando_nvg_antenna;	// External class reference
	class VestItem;	// External class reference
	class UniformItem;	// External class reference
	class HeadgearItem;	// External class reference
	
	class RC_Helmet : SWLB_clone_commando_helmet_k1 {
		class ItemInfo : HeadgearItem {
			mass = 10;
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_helmet.p3d";
			hiddenSelections[] = {"illum", "camo1"};
			allowedSlots[] = {801, 901, 701, 605};
			modelSides[] = {6};
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 60;
					passThrough = 0.4;
				};
			};
		};
	};
	
	class RC_Helmet_MPStealth : RC_Helmet {
		displayName = "Katarn I clone commando helmet (stealth)";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_MPStealth_Helmet_co.paa", "SWLB_units_spec\data\SWLB_MPStealth_Helmet_co.paa"};
	};
	
	class RC_Helmet_MPRecon : RC_Helmet {
		displayName = "Katarn I clone commando helmet (recon)";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_MPRecon_Helmet_co.paa", "SWLB_units_spec\data\SWLB_MPRecon_Helmet_co.paa"};
	};
	
	class RC_Helmet_MPMarksman : RC_Helmet {
		displayName = "Katarn I clone commando helmet (marksman)";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_MPMarksman_Helmet_co.paa", "SWLB_units_spec\data\SWLB_MPMarksman_Helmet_co.paa"};
	};
	
	class RC_Helmet_MPGunner : RC_Helmet {
		displayName = "Katarn I clone commando helmet (gunner)";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_MPGunner_Helmet_co.paa", "SWLB_units_spec\data\SWLB_MPGunner_Helmet_co.paa"};
	};
	
	class RC_Helmet_YayaxCov : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Yayax [Cov])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_YayaxCov_Helmet_co.paa", "SWLB_units_spec\data\SWLB_YayaxCov_Helmet_co.paa"};
	};
	
	class RC_Helmet_YayaxDev : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Yayax [Dev])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_YayaxDev_Helmet_co.paa", "SWLB_units_spec\data\SWLB_YayaxDev_Helmet_co.paa"};
	};
	
	class RC_Helmet_YayaxJind : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Yayax [Jind])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_YayaxJind_Helmet_co.paa", "SWLB_units_spec\data\SWLB_YayaxJind_Helmet_co.paa"};
	};
	
	class RC_Helmet_YayaxYover : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Yayax [Yover])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_YayaxYover_Helmet_co.paa", "SWLB_units_spec\data\SWLB_YayaxYover_Helmet_co.paa"};
	};
	
	class RC_Helmet_AiwhaDikut : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Aiwha [Di'kut])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_AiwhaDikut_Helmet_co.paa", "SWLB_units_spec\data\SWLB_AiwhaDikut_Helmet_co.paa"};
	};
	
	class RC_Helmet_AiwhaSarge : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Aiwha [Sarge])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_AiwhaSarge_Helmet_co.paa", "SWLB_units_spec\data\SWLB_AiwhaSarge_Helmet_co.paa"};
	};
	
	class RC_Helmet_AiwhaTyto : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Aiwha [Tyto])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_AiwhaTyto_Helmet_co.paa", "SWLB_units_spec\data\SWLB_AiwhaTyto_Helmet_co.paa"};
	};
	
	class RC_Helmet_AiwhaZag : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Aiwha [Zag])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_AiwhaZag_Helmet_co.paa", "SWLB_units_spec\data\SWLB_AiwhaZag_Helmet_co.paa"};
	};
	
	class RC_Helmet_Omega : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Omega)";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Omega_Helmet_co.paa", "SWLB_units_spec\data\SWLB_Omega_Helmet_co.paa"};
	};
	
	class RC_Helmet_DeltaBoss : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Delta [Boss])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_DeltaBoss_Helmet_co.paa", "SWLB_units_spec\data\SWLB_DeltaBoss_Helmet_co.paa"};
	};
	
	class RC_HelmetDeltaSev : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Delta [Sev])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_DeltaSev_Helmet_co.paa", "SWLB_units_spec\data\SWLB_DeltaSev_Helmet_co.paa"};
	};
	
	class RC_Helmet_DeltaFixer : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Delta [Fixer])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_DeltaFixer_Helmet_co.paa", "SWLB_units_spec\data\SWLB_DeltaFixer_Helmet_co.paa"};
	};
	
	class RC_Helmet_DeltaScorch : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Delta [Scorch])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_DeltaScorch_Helmet_co.paa", "SWLB_units_spec\data\SWLB_DeltaScorch_Helmet_co.paa"};
	};
	
	class RC_Helmet_BravoRam : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Bravo [Ram])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_BravoRam_Helmet_co.paa", "SWLB_units_spec\data\SWLB_BravoRam_Helmet_co.paa"};
	};
	
	class RC_Helmet_Bravo2 : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Bravo [2])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Bravo2_Helmet_co.paa", "SWLB_units_spec\data\SWLB_Bravo2_Helmet_co.paa"};
	};
	
	class RC_Helmet_Bravo3 : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Bravo [3])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Bravo3_Helmet_co.paa", "SWLB_units_spec\data\SWLB_Bravo3_Helmet_co.paa"};
	};
	
	class RC_Helmet_Bravo4 : RC_Helmet {
		displayName = "Katarn I clone commando helmet (Bravo [4])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Bravo4_Helmet_co.paa", "SWLB_units_spec\data\SWLB_Bravo4_Helmet_co.paa"};
	};
	
	class RC_nvg : SWLB_clone_commando_nvg {
		displayName = "Clone II commando NV visor";
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_nvg_antenna : SWLB_clone_commando_nvg_antenna {
		displayName = "Clone II commando helmet antenna";
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_Omega_sniper_armor_V2 : SWLB_clone_commando_sniper_armor_k1 {
		displayName = "Omega Katarn II commando sniper vest";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Omega_Armor2_Co"};
		hiddenSelectionsMaterials[] = {"a3\characters_f_bootcamp\common\data\vrarmoremmisive.rvmat"};
		
		class ItemInfo : VestItem {
			hiddenSelections[] = {"camo1"};
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_sniper_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_sniper_armor_V2 : SWLB_clone_commando_sniper_armor_k1 {
		displayName = "Katarn II commando sniper vest";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsMaterials[] = {"a3\characters_f_bootcamp\common\data\vrarmoremmisive.rvmat"};
		
		class ItemInfo : VestItem {
			hiddenSelections[] = {"camo1"};
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_sniper_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_tech_armor_V2 : SWLB_clone_commando_tech_armor_k1 {
		displayName = "Katarn II commando tech vest";
		hiddenSelectionsTextures[] = {"\SWLB_clones_spec\data\camo2_co.paa"};
		hiddenSelections[] = {"camo1"};
		
		class ItemInfo : VestItem {
			hiddenSelections[] = {"camo1"};
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_tech_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_Omega_eod_armor_V2 : SWLB_clone_commando_eod_armor_k1 {
		displayName = "Omega Katarn II commando EOD vest";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Omega_Armor2_Co"};
		
		class ItemInfo : VestItem {
			hiddenSelections[] = {"camo1"};
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_eod_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_eod_armor_V2 : SWLB_clone_commando_eod_armor_k1 {
		displayName = "Katarn II commando EOD vest";
		
		class ItemInfo : VestItem {
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_eod_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_sl_armor_V2 : SWLB_clone_commando_sl_armor_k1 {
		displayName = "Katarn II commando squad leader pauldron";
		
		class ItemInfo : VestItem {
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_sl_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_basic_armor_v2 : SWLB_clone_commando_basic_armor_k1 {
		displayName = "Katarn II commando vest V2";
		
		class ItemInfo : VestItem {
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_basic_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "Clone commando (RC)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "RC";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_MPStealth_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Stealth armor";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "MPStealth";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_MPRecon_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Recon armor";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Recon";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_MPMarksman_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Marksman armor";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Marksman";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_MPGunner_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Gunner armor";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Gunner";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_YayaxCov_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Yayax armor (Cov)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "YayaxCov";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_YayaxDev_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Yayax armor (Dev)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "YayaxDev";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_YayaxJind_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Yayax armor (Jind)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "YayaxJind";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_YayaxYover_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Yayax armor (Yover)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "YayaxYover";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_AiwhaDikut_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Aiwha armor (Dikut)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "AiwhaDikut";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_AiwhaSarge_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Aiwha armor (Sarge)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "AiwhaSarge";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_AiwhaTyto_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Aiwha armor (Tyto)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "AiwhaTyto";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_AiwhaZag_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Aiwha armor (Zag)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "AiwhaZag";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_OmegaNiner_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Omega armor (Niner)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "OmegaNiner";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_OmegaDarman_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Omega armor (Darman)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "OmegaDarman";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_OmegaFi_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Omega armor (Fi)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "OmegaFi";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_DeltaBoss_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Delta armor (Boss)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "DeltaBoss";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_DeltaSev_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Delta armor (Sev)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "DeltaSev";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_DeltaFixer_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Delta armor (Fixer)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "DeltaFixer";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_DeltaScorch_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Delta armor (Scorch)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "DeltaScorch";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_BravoRam_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Bravo armor (Ram)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "BravoRam";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_Bravo2_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Bravo armor (2)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Bravo2";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_Bravo3_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Bravo armor (3)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Bravo3";
			containerClass = "Supply140";
			mass = 40;
		};
	};
	
	class RC_Bravo4_Uniform : SWLB_clone_commando_uniform_k1 {
		displayName = "RC Bravo armor (4)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Bravo4";
			containerClass = "Supply140";
			mass = 40;
		};
	};
};

class CfgVehicles {
	class SWLB_MPStealth;	// External class reference
	class SWLB_MPRecon;	// External class reference
	class SWLB_MPMarksman;	// External class reference
	class SWLB_YayaxCov;	// External class reference
	class SWLB_YayaxDev;	// External class reference
	class SWLB_YayaxJind;	// External class reference
	class SWLB_YayaxYover;	// External class reference
	class SWLB_AiwhaDikut;	// External class reference
	class SWLB_AiwhaSarge;	// External class reference
	class SWLB_AiwhaTyto;	// External class reference
	class SWLB_AiwhaZag;	// External class reference
	class SWLB_BravoRam;	// External class reference
	class SWLB_Bravo2;	// External class reference
	class SWLB_Bravo3;	// External class reference
	class SWLB_Bravo4;	// External class reference
	class SWLB_DeltaBoss;	// External class reference
	class SWLB_DeltaFixer;	// External class reference
	class SWLB_DeltaSev;	// External class reference
	class SWLB_DeltaScorch;	// External class reference
	class SWLB_OmegaNiner;	// External class reference
	class SWLB_DeltaBoss_backpack;	// External class reference
	class SWLB_DeltaFixer_backpack;	// External class reference
	class SWLB_DeltaSev_backpack;	// External class reference
	class SWLB_DeltaScorch_backpack;	// External class reference
	class SWLB_Omega_backpack;	// External class reference
	class SWLB_OmegaDarman_backpack;	// External class reference
	class SWLB_OmegaNiner_backpack;	// External class reference
	class SWLB_MPGunner;	// External class reference
	class SWLB_MPGunner_backpack;	// External class reference
	class SWLB_clone_commando_base;	// External class reference
	class SWLB_clone_commando_backpack_k2;	// External class reference
	class SWLB_clone_commando_backpack_k2_rto;	// External class reference
	class SWLB_clone_commando_backpack_k2_eod;	// External class reference
	class SWLB_clone_commando_backpack_k2_tech;	// External class reference
	
	class RC_backpack : SWLB_clone_commando_backpack_k2 {
		author = "LastWar Team";
		scopecurator = 2;
		displayName = "RC Backpack v2";
		maximumLoad = 400;
		tf_dialog = "SWLB_clone_rto_commando_radio_dialog";
		tf_dialogUpdate = "call TFAR_fnc_updateLRDialogToChannel;";
		tf_encryptionCode = "tf_west_radio_code";
		tf_hasLRradio = 1;
		tf_range = 25000;
		tf_subtype = "digital_lr";
	};
	
	class RC_RTO_Backpack : SWLB_clone_commando_backpack_k2_rto {
		author = "LastWar Team";
		scopecurator = 2;
		displayName = "RC RTO Backpack v2";
		maximumLoad = 400;
	};
	
	class RC_EOD_Backpack : SWLB_clone_commando_backpack_k2_eod {
		author = "LastWar Team";
		scopecurator = 2;
		displayName = "RC EOD Backpack v2";
		maximumLoad = 400;
		tf_dialog = "SWLB_clone_rto_commando_radio_dialog";
		tf_dialogUpdate = "call TFAR_fnc_updateLRDialogToChannel;";
		tf_encryptionCode = "tf_west_radio_code";
		tf_hasLRradio = 1;
		tf_range = 25000;
		tf_subtype = "digital_lr";
	};
	
	class RC_Tech_Backpack : SWLB_clone_commando_backpack_k2_tech {
		author = "LastWar Team";
		scopecurator = 2;
		displayName = "RC Tech Backpack v2";
		maximumLoad = 400;
		tf_dialog = "SWLB_clone_rto_commando_radio_dialog";
		tf_dialogUpdate = "call TFAR_fnc_updateLRDialogToChannel;";
		tf_encryptionCode = "tf_west_radio_code";
		tf_hasLRradio = 1;
		tf_range = 25000;
		tf_subtype = "digital_lr";
	};
	
	class RC_MPStealth_backpack : RC_backpack {
		displayName = "RC Backpack v2 (stealth)";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_MPstealth_Backpack_co.paa", "SWLB_units_spec\data\SWLB_MPstealth_Backpack_co.paa"};
	};
	
	class RC_MPRecon_backpack : RC_backpack {
		displayName = "RC Backpack v2 (recon)";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_MPRecon_Backpack_co.paa", "SWLB_units_spec\data\SWLB_MPRecon_Backpack_co.paa"};
	};
	
	class RC_MPMarksman_backpack : RC_backpack {
		displayName = "RC Backpack v2 (marksman)";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_MPMarksman_Backpack_co.paa", "SWLB_units_spec\data\SWLB_MPMarksman_Backpack_co.paa"};
	};
	
	class RC_MPGunner_backpack : RC_backpack {
		displayName = "RC Backpack v2 (gunner)";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_MPGunner_Backpack_co.paa", "SWLB_units_spec\data\SWLB_MPGunner_Backpack_co.paa"};
	};
	
	class RC_YayaxDev_backpack : RC_EOD_Backpack {
		displayName = "RC EOD Backpack v2 (Yayax [Dev])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_YayaxDev_Backpack_co.paa", "SWLB_units_spec\data\SWLB_YayaxDev_Backpack_co.paa"};
	};
	
	class RC_YayaxYover_backpack : RC_EOD_Backpack {
		displayName = "RC EOD Backpack v2 (Yayax [Yover])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_YayaxYover_Backpack_co.paa", "SWLB_units_spec\data\SWLB_YayaxYover_Backpack_co.paa"};
	};
	
	class RC_OmegaNiner_backpack : RC_RTO_Backpack {
		displayName = "RC RTO Backpack v2 (Omega [Niner])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Omega_Backpack_co.paa", "SWLB_units_spec\data\SWLB_Omega_Backpack_co.paa"};
	};
	
	class RC_OmegaDarman_backpack : RC_EOD_Backpack {
		displayName = "RC EOD Backpack v2 (Omega [Darman])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Omega_Backpack_co.paa", "SWLB_units_spec\data\SWLB_Omega_Backpack_co.paa"};
	};
	
	class RC_Omega_Tech_backpack : RC_Tech_Backpack {
		displayName = "RC Tech Backpack v2 (Omega)";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Omega_Backpack_co.paa", "SWLB_units_spec\data\SWLB_Omega_Backpack_co.paa", "\SWLB_clones_spec\backpacks\data\backpack_tech_co.paa"};
	};
	
	class RC_Omega_backpack : RC_backpack {
		displayName = "RC Backpack v2 (Omega)";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Omega_Backpack_co.paa", "SWLB_units_spec\data\SWLB_Omega_Backpack_co.paa"};
	};
	
	class RC_DeltaBoss_backpack : RC_RTO_Backpack {
		displayName = "RC RTO Backpack v2 (Delta [Boss])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_DeltaBoss_Backpack_co.paa", "SWLB_units_spec\data\SWLB_DeltaBoss_Backpack_co.paa"};
	};
	
	class RC_DeltaSev_backpack : RC_backpack {
		displayName = "RC Backpack v2 (Delta [Sev])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_DeltaSev_Backpack_co.paa", "SWLB_units_spec\data\SWLB_DeltaSev_Backpack_co.paa"};
	};
	
	class RC_DeltaFixer_backpack : RC_Tech_Backpack {
		displayName = "RC Backpack v2 (Delta [Fixer])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_DeltaFixer_Backpack_co.paa", "SWLB_units_spec\data\SWLB_DeltaFixer_Backpack_co.paa", "\SWLB_clones_spec\backpacks\data\backpack_tech_co.paa"};
	};
	
	class RC_DeltaScorch_backpack : RC_EOD_Backpack {
		displayName = "RC EOD Backpack v2 (Delta [Scorch])";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_DeltaScorch_Backpack_co.paa", "SWLB_units_spec\data\SWLB_DeltaScorch_Backpack_co.paa"};
	};
	
	class RC : SWLB_clone_commando_base {
		author = "LastWar Team";
		displayName = "RC armor v2";
		faction = "LW_Faction";
		editorSubcategory = RC_V2;
		uniformclass = "RC";
		linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		armor = 60;
		armorStructural = 5;
		explosionShielding = 0.0005;
		minTotalDamageThreshold = 10;
		impactDamageMultiplier = 0.4;
		passThrough = 0.4;
	};
	
	class MPStealth : RC {
		author = "LastWar Team";
		displayName = "MPStealth";
		uniformclass = "MPStealth";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_MPStealth_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_MPStealth_Armor2_Co.paa"};
	};
	
	class Recon : RC {
		author = "LastWar Team";
		displayName = "Recon";
		uniformclass = "Recon";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_MPRecon_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_MPRecon_Armor2_Co.paa"};
	};
	
	class Marksman : RC {
		author = "LastWar Team";
		displayName = "Marksman";
		uniformclass = "Marksman";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_MPMarksman_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_MPMarksman_Armor2_Co.paa"};
	};
	
	class Gunner : RC {
		author = "LastWar Team";
		displayName = "Gunner";
		uniformclass = "Gunner";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_MPGunner_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_MPGunner_Armor2_Co.paa"};
	};
	
	class YayaxCov : RC {
		author = "LastWar Team";
		displayName = "YayaxCov";
		uniformclass = "YayaxCov";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_YayaxCov_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_YayaxCov_Armor2_Co.paa"};
	};
	
	class YayaxDev : RC {
		author = "LastWar Team";
		displayName = "YayaxDev";
		uniformclass = "YayaxDev";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_YayaxDev_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_YayaxDev_Armor2_Co.paa"};
	};
	
	class YayaxJind : RC {
		author = "LastWar Team";
		displayName = "YayaxJind";
		uniformclass = "YayaxJind";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_YayaxJind_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_YayaxJind_Armor2_Co.paa"};
	};
	
	class YayaxYover : RC {
		author = "LastWar Team";
		displayName = "YayaxYover";
		uniformclass = "YayaxYover";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_YayaxYover_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_YayaxYover_Armor2_Co.paa"};
	};
	
	class AiwhaDikut : RC {
		author = "LastWar Team";
		displayName = "AiwhaDikut";
		uniformclass = "AiwhaDikut";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_AiwhaDikut_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_AiwhaDikut_Armor2_Co.paa"};
	};
	
	class AiwhaSarge : RC {
		author = "LastWar Team";
		displayName = "AiwhaSarge";
		uniformclass = "AiwhaSarge";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_AiwhaSarge_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_AiwhaSarge_Armor2_Co.paa"};
	};
	
	class AiwhaTyto : RC {
		author = "LastWar Team";
		displayName = "AiwhaTyto";
		uniformclass = "AiwhaTyto";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_AiwhaTyto_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_AiwhaTyto_Armor2_Co.paa"};
	};
	
	class AiwhaZag : RC {
		author = "LastWar Team";
		displayName = "AiwhaZag";
		uniformclass = "AiwhaZag";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_AiwhaZag_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_AiwhaZag_Armor2_Co.paa"};
	};
	
	class OmegaNiner : RC {
		author = "LastWar Team";
		displayName = "OmegaNiner";
		uniformclass = "OmegaNiner";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Omega_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_Omega_Armor2_Co.paa"};
	};
	
	class OmegaDarman : RC {
		author = "LastWar Team";
		displayName = "OmegaDarman";
		uniformclass = "OmegaDarman";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Omega_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_Omega_Armor2_Co.paa"};
	};
	
	class OmegaFi : RC {
		author = "LastWar Team";
		displayName = "OmegaFi";
		uniformclass = "OmegaFi";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Omega_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_Omega_Armor2_Co.paa"};
	};
	
	class DeltaBoss : RC {
		author = "LastWar Team";
		displayName = "DeltaBoss";
		uniformclass = "DeltaBoss";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_DeltaBoss_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_DeltaBoss_Armor2_Co.paa"};
	};
	
	class DeltaSev : RC {
		author = "LastWar Team";
		displayName = "DeltaSev";
		uniformclass = "DeltaSev";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_DeltaSev_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_DeltaSev_Armor2_Co.paa"};
	};
	
	class DeltaFixer : RC {
		author = "LastWar Team";
		displayName = "DeltaFixer";
		uniformclass = "DeltaFixer";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_DeltaFixer_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_DeltaFixer_Armor2_Co.paa"};
	};
	
	class DeltaScorch : RC {
		author = "LastWar Team";
		displayName = "DeltaScorch";
		uniformclass = "DeltaScorch";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_DeltaScorch_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_DeltaScorch_Armor2_Co.paa"};
	};
	
	class BravoRam : RC {
		author = "LastWar Team";
		displayName = "BravoRam";
		uniformclass = "BravoRam";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_BravoRam_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_BravoRam_Armor2_Co.paa"};
	};
	
	class Bravo2 : RC {
		author = "LastWar Team";
		displayName = "Bravo2";
		uniformclass = "Bravo2";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Bravo2_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_Bravo2_Armor2_Co.paa"};
	};
	
	class Bravo3 : RC {
		author = "LastWar Team";
		displayName = "Bravo3";
		uniformclass = "Bravo3";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Bravo3_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_Bravo3_Armor2_Co.paa"};
	};
	
	class Bravo4 : RC {
		author = "LastWar Team";
		displayName = "Bravo4";
		uniformclass = "Bravo4";
		hiddenSelectionsTextures[] = {"SWLB_units_spec\data\SWLB_Bravo4_Armor1_Co.paa", "SWLB_units_spec\data\SWLB_Bravo4_Armor2_Co.paa"};
	};
};

class cfgMods {
	author = "Last Force Project";
	timepacked = 1594648239;
};
