// config.bin - 23:40:26 07/23/20, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class Zulu_Legion {
		units[] = {"Sg", "Host", "Ofic", "Eng", "Med", "TR", ARF};
		weapons[] = {"Zulu_Officer_Visor", "Zulu_Backpack", "Zulu_Backpack_heavy", "Zulu_Backpack_medic", "Zulu_Backpack_RTO", "Zulu_HelmetP1_Sg", "Zulu_Uniform_Sg", "Zulu_HelmetP1_Host", "Zulu_Uniform_Host", "Zulu_HelmetP1_Ofic", "Zulu_Uniform_Ofic", "Zulu_HelmetP1_Eng", "Zulu_Uniform_Eng", "Zulu_HelmetP1_Med", "Zulu_Uniform_Med", "Zulu_HelmetP1_ARF", "Zulu_Uniform_ARF", "Zulu_HelmetP1", "Zulu_Uniform"};
	};
	author = "LastWarTeam";
	requiredAddons[] = {"SWLB_clones", "SWLB_equipment", SWLB_CEE};
};

class CfgFactionClasses {
	class LW_Faction {
		displayName = "LastWar";
	};
};

class CfgEditorSubcategories {
	class Zulu_Legion {
		displayName = "Zulu LW Legion";
	};
};

class CfgWeapons {
	class H_HelmetO_ViperSP_hex_F;	// External class reference
	class SWLB_clone_ccVisor;	// External class reference
	class SWLB_clone_mcVisor;	// External class reference
	class SWLB_clone_nvg;	// External class reference
	class SWLB_clone_nvg_nco;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_nvg_spec;	// External class reference
	class SWLB_clone_nvg_spec_nco;	// External class reference
	class SWLB_clone_commando_nvg_antenna;	// External class reference
	class SWLB_clone_commando_nvg;	// External class reference
	class SWLB_clone_P1_2_helmet;	// External class reference
	class SWLB_clone_ARF_P1_helmet;	// External class reference
	class SWLB_clone_ARF_P2_helmet;	// External class reference
	class SWLB_clone_P1_helmet;	// External class reference
	class SWLB_clone_eng_helmet;	// External class reference
	class SWLB_clone_BARC_helmet;	// External class reference
	class SWLB_clone_P2_helmet;	// External class reference
	class SWLB_clone_AB_helmet;	// External class reference
	class SWLB_clone_P15_helmet;	// External class reference
	class SDT_Hazard_Helmet;	// External class reference
	class SDT_stealth_helmet;	// External class reference
	class Scout_helmet;	// External class reference
	class SWLB_clone_pilot_P2_helmet;	// External class reference
	class SWLB_clone_commando_helmet_k1;	// External class reference
	class SWLB_clone_recon_armor;	// External class reference
	class SWLB_clone_recon_officer_armor;	// External class reference
	class SWLB_clone_recon_nco_armor;	// External class reference
	class SWLB_clone_officer_armor;	// External class reference
	class SWLB_clone_medic_armor;	// External class reference
	class SWLB_clone_kama_armor;	// External class reference
	class SWLB_clone_mc_uniform;	// External class reference
	class SWLB_clone_commander_armor;	// External class reference
	class SWLB_clone_cfr_armor;	// External class reference
	class SWLB_clone_airborne_armor;	// External class reference
	class SWLB_clone_airborne_nco_armor;	// External class reference
	class SWLB_clone_arc_armor;	// External class reference
	class SWLB_clone_commando_eod_armor_k1;	// External class reference
	class SWLB_clone_commando_sniper_armor_k1;	// External class reference
	class SWLB_clone_commando_sl_armor_k1;	// External class reference
	class SWLB_clone_commando_tech_armor_k1;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	class SWLB_clone_commando_uniform_k1;	// External class reference
	class SWLA_BL_Sergeant_Vest;	// External class reference
	class SWLB_mando_og_helmet;	// External class reference
	class SWLB_mando_og_armor;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_mando_uniform;	// External class reference
	class UniformItem;	// External class reference
	class HeadgearItem;	// External class reference
	class SDT_pilot_p1_helmet;	// External class reference
	class SWLB_P1_Pilot_Helmet;	// External class reference
	class SWLB_CEE_Hazard_Helmet;	// External class reference
	class SWLB_MonocularcularNVG;	// External class reference
	
	class Zulu_NVG : SWLB_clone_nvg {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper NV visor";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_NVG.paa"};
	};
	
	class Zulu_MonocularNVGSPC : SWLB_MonocularcularNVG {
		displayName = "Zulu Clone Specialist Monocular NV Visor";
		hiddenSelectionsTextures[] = {"Zulu_Unit\Data\Zulu_Monocular.paa"};
		
		class ItemInfo {
			hiddenSelections[] = {"Camo1"};
			hiddenSelectionsTextures[] = {"Zulu_Unit\Data\Zulu_Monocular.paa"};
			type = 616;
			hmdType = 0;
			uniformModel = "SWLB_Dutch_NVG\MonocularNV\MonocularNVDown.p3d";
			modelOff = "SWLB_Dutch_NVG\MonocularNV\MonocularNVUp.p3d";
			mass = 4;
		};
		visionMode[] = {"Normal", NVG};
	};
	
	class Zulu_Officer_Visor : SWLB_clone_ccVisor {
		author = "LastWar Team";
		displayName = "Zulu Clone trooper Officer visor";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_NVG.paa"};
		
		class ItemInfo {
			type = 616;
			uniformModel = "\SWLB_clones\SWLB_clone_ccVisor.p3d";
			modelOff = "\SWLB_clones\SWLB_clone_ccVisor.p3d";
			mass = 20;
			hiddenSelections[] = {"camo1", "camo2"};
		};
	};
	
	class Zulu_HelmetP1_Host : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper P1 Helmet (Host)";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_HelmetP1_Host.paa"};
	};
	
	class Zulu_HelmetP1_Hazard : SWLB_CEE_Hazard_Helmet {
		author = "LastWarTeam";
		displayName = "Zulu Clone Trooper Hazard helmet";
		hiddenSelectionsTextures[] = {"Zulu_unit\data\Zulu_Helmet_Hazard.paa"};
	};
	
	class Zulu_ARF_P2_helmet : SWLB_clone_ARF_P2_helmet {
		author = "LastWar Team";
		displayName = "Zulu Clone trooper P2 ARF helmet";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_HelmetP1_ARF.paa", "", "Zulu_Unit\data\Zulu_ARF_Flaps.paa"};
	};
	
	class Zulu_Helmet_Barc : SWLB_clone_BARC_helmet {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper BARC Helmet";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_Helmet_Barc.paa"};
	};
	
	class Zulu_HelmetP1_Ofic : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper P1 Helmet (Ofic)";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_HelmetP1_Ofic.paa"};
	};
	
	class Zulu_HelmetP1_Eng : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper P1 Helmet (Eng)";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_HelmetP1_Eng.paa"};
	};
	
	class Zulu_HelmetP1_Med : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper P1 Helmet (Med)";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_HelmetP1_Med.paa"};
	};
	
	class Zulu_HelmetP1_ARF : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper P1 Helmet ARF";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_HelmetP1_ARF.paa"};
	};
	
	class Zulu_HelmetP1 : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper P1 Helmet";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_HelmetP1.paa"};
	};
	
	class Zulu_Uniform_Host : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper Uniform (Host)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Host";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class Zulu_Uniform_Ofic : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper Uniform (Ofic)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Ofic";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class Zulu_Uniform_Sg : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper Uniform (Sg)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Sg";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class Zulu_Uniform_Eng : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper Uniform (Eng)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Eng";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class Zulu_Uniform_Med : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper Uniform (Med)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Med";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class Zulu_Uniform_ARF : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper Uniform ARF";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = ARF;
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class Zulu_Uniform : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper Uniform";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Tr";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class Zulu_Camo_Sg : SWLB_clone_kama_armor {
		author = "LastWar Team";
		displayName = "Zulu Officer Camo (Sg)";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_Camo.paa"};
	};
	
	class Zulu_Camo_Host : SWLB_clone_commander_armor {
		author = "LastWar Team";
		displayName = "Zulu Officer Camo (Host)";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_Camo.paa"};
	};
	
	class Zulu_Camo_Ofic : SWLB_clone_officer_armor {
		author = "LastWar Team";
		displayName = "Zulu Officer Camo";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_Camo.paa"};
	};
	
	class Zulu_Camo_Eng : SWLB_clone_airborne_nco_armor {
		author = "LastWar Team";
		displayName = "Zulu Camo (ENG)";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_Vest_Eng.paa", "Zulu_Unit\data\Zulu_Camo.paa", "Zulu_Unit\data\Zulu_Vest_Eng.paa", "Zulu_Unit\data\Zulu_Vest_Eng.paa"};
	};
	
	class Zulu_Camo_Med : SWLB_clone_airborne_nco_armor {
		author = "LastWar Team";
		displayName = "Zulu Camo (Med)";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_Vest_Med.paa", "Zulu_Unit\data\Zulu_Camo.paa", "Zulu_Unit\data\Zulu_Vest_Med.paa", "Zulu_Unit\data\Zulu_Vest_Med.paa"};
	};
};

class CfgVehicles {
	class SWLB_clone_commando_base;	// External class reference
	class SWLB_clone_commando_backpack_k2;	// External class reference
	class SWLB_clone_commando_backpack_k2_rto;	// External class reference
	class SWLB_clone_commando_backpack_k2_eod;	// External class reference
	class SWLB_clone_base_P2;	// External class reference
	class SWLB_clone_base_P1;	// External class reference
	class SWLB_clone_assault_base_P2;	// External class reference
	class SWLB_clone_cfr_base_P2;	// External class reference
	class SWLB_clone_medic_base_P2;	// External class reference
	class SWLB_clone_RTO_base_P2;	// External class reference
	class SWLB_clone_recon_base_P2;	// External class reference
	class SWLB_clone_recon_nco_base_P2;	// External class reference
	class SWLB_clone_recon_officer_base_P2;	// External class reference
	class SWLB_clone_airborne_base_P2;	// External class reference
	class SWLB_clone_airborne_nco_base_P2;	// External class reference
	class SWLB_clone_lieutenant_base_P2;	// External class reference
	class SWLB_clone_captain_base_P2;	// External class reference
	class SWLB_clone_commander_base_P2;	// External class reference
	class SWLB_clone_marshal_commander_base_P2;	// External class reference
	class SWLB_clone_arc_base_P2;	// External class reference
	class SWLB_clone_pilot_base_P2;	// External class reference
	class SWLB_clone_sniper_base_P2;	// External class reference
	class SWLB_clone_sg_base_P2;	// External class reference
	class SWLB_clone_at_base_P2;	// External class reference
	class SWLB_clone_backpack;	// External class reference
	class SWLB_clone_backpack_eod;	// External class reference
	class SWLB_clone_backpack_heavy;	// External class reference
	class SWLB_mando_base_assault;	// External class reference
	class SWLB_clone_backpack_RTO;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_RTO_mini_backpack;	// External class reference
	class SWLB_clone_backpack_medic;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	
	class Host : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper (Host)";
		faction = "LW_Faction";
		editorSubcategory = "Zulu_Legion";
		uniformclass = "Host";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_Armor1_Host.paa", "Zulu_Unit\data\Zulu_Armor2_Host.paa"};
		linkedItems[] = {"Zulu_HelmetP1_Host", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"Zulu_HelmetP1_Host", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Ofic : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper (Ofic)";
		faction = "LW_Faction";
		editorSubcategory = "Zulu_Legion";
		uniformclass = "Ofic";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_Armor1_Ofic.paa", "Zulu_Unit\data\Zulu_Armor2_Ofic.paa"};
		linkedItems[] = {"Zulu_HelmetP1_Ofic", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"Zulu_HelmetP1_Ofic", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Sg : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper (Sg)";
		faction = "LW_Faction";
		editorSubcategory = "Zulu_Legion";
		uniformclass = "Sg";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_Armor1_Sg.paa", "Zulu_Unit\data\Zulu_Armor2_Sg.paa"};
		linkedItems[] = {"Zulu_HelmetP1_Ofic", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"Zulu_HelmetP1_Ofic", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Eng : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper (Eng)";
		faction = "LW_Faction";
		editorSubcategory = "Zulu_Legion";
		uniformclass = "Eng";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_Armor1_Eng.paa", "Zulu_Unit\data\Zulu_Armor2_Eng.paa"};
		linkedItems[] = {"Zulu_HelmetP1_Eng", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"Zulu_HelmetP1_Eng", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Med : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper (Med)";
		faction = "LW_Faction";
		editorSubcategory = "Zulu_Legion";
		uniformclass = "Med";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_Armor1_Med.paa", "Zulu_Unit\data\Zulu_Armor2_Med.paa"};
		linkedItems[] = {"Zulu_HelmetP1_Med", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"Zulu_HelmetP1_Med", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class ARF : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper ARF";
		faction = "LW_Faction";
		editorSubcategory = "Zulu_Legion";
		uniformclass = ARF;
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_Armor1_ARF.paa", "Zulu_Unit\data\Zulu_Armor2_ARF.paa"};
		linkedItems[] = {"Zulu_HelmetP1_ARF", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"Zulu_HelmetP1_ARF", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Tr : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "Zulu Clone Trooper";
		faction = "LW_Faction";
		editorSubcategory = "Zulu_Legion";
		uniformclass = "Tr";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_Armor1.paa", "Zulu_Unit\data\Zulu_Armor2.paa"};
		linkedItems[] = {"Zulu_HelmetP1", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"Zulu_HelmetP1", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Zulu_Backpack : SWLB_clone_backpack {
		displayName = "Zulu Clone trooper backpack";
		author = "LastWar Team";
		scope = 2;
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_BPack.paa", "Zulu_Unit\data\Zulu_BPack.paa", "", ""};
	};
	
	class Zulu_Backpack_heavy : SWLB_clone_backpack_heavy {
		displayName = "Zulu Clone trooper heavy backpack";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_BPack.paa", "Zulu_Unit\data\Zulu_BPack.paa", "Zulu_Unit\data\Zulu_BPack.paa", "", ""};
	};
	
	class Zulu_Backpack_medic : SWLB_clone_backpack_medic {
		displayName = "Zulu Clone trooper medic backpack";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_BPack.paa", "Zulu_Unit\data\Zulu_BPack.paa", "", "Zulu_Unit\data\Zulu_BPack.paa"};
	};
	
	class Zulu_Backpack_RTO : SWLB_clone_backpack_RTO {
		displayName = "Zulu Clone trooper RTO backpack";
		hiddenSelectionsTextures[] = {"Zulu_Unit\data\Zulu_BPack.paa", "", "", "", "Zulu_Unit\data\Zulu_BPack.paa"};
	};
};

class cfgMods {
	author = "Last Force Project";
	timepacked = 1594648262;
};
