// config.bin - 23:37:15 07/23/20, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class 21_Legion {
		units[] = {"Keller"};
		weapons[] = {"21_Uniform", "21_HelmetP1_Keller", "21_Uniform_Keller"};
	};
	author = "LastWarTeam";
	requiredAddons[] = {"SWLB_clones", "SWLB_equipment", SWLB_CEE};
};

class CfgFactionClasses {
	class LW_Faction {
		displayName = "LastWar";
	};
};

class CfgEditorSubcategories {
	class 21_Legion {
		displayName = "21st LW Legion";
	};
};

class CfgWeapons {
	class H_HelmetO_ViperSP_hex_F;	// External class reference
	class SWLB_clone_ccVisor;	// External class reference
	class SWLB_clone_mcVisor;	// External class reference
	class SWLB_clone_nvg;	// External class reference
	class SWLB_clone_nvg_nco;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_nvg_spec;	// External class reference
	class SWLB_clone_nvg_spec_nco;	// External class reference
	class SWLB_clone_commando_nvg_antenna;	// External class reference
	class SWLB_clone_commando_nvg;	// External class reference
	class SWLB_clone_P1_2_helmet;	// External class reference
	class SWLB_clone_ARF_P1_helmet;	// External class reference
	class SWLB_clone_P1_helmet;	// External class reference
	class SWLB_clone_eng_helmet;	// External class reference
	class SWLB_clone_BARC_helmet;	// External class reference
	class SWLB_clone_P2_helmet;	// External class reference
	class SWLB_clone_AB_helmet;	// External class reference
	class SWLB_clone_P15_helmet;	// External class reference
	class SDT_Hazard_Helmet;	// External class reference
	class SDT_stealth_helmet;	// External class reference
	class Scout_helmet;	// External class reference
	class SWLB_clone_pilot_P2_helmet;	// External class reference
	class SWLB_clone_commando_helmet_k1;	// External class reference
	class SWLB_clone_recon_armor;	// External class reference
	class SWLB_clone_recon_officer_armor;	// External class reference
	class SWLB_clone_recon_nco_armor;	// External class reference
	class SWLB_clone_officer_armor;	// External class reference
	class SWLB_clone_medic_armor;	// External class reference
	class SWLB_clone_kama_armor;	// External class reference
	class SWLB_clone_mc_uniform;	// External class reference
	class SWLB_clone_commander_armor;	// External class reference
	class SWLB_clone_cfr_armor;	// External class reference
	class SWLB_clone_airborne_armor;	// External class reference
	class SWLB_CEE_Force_Recon_Officer;	// External class reference
	class SWLB_clone_airborne_nco_armor;	// External class reference
	class SWLB_clone_arc_armor;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	class SWLA_BL_Sergeant_Vest;	// External class reference
	class SWLB_CEE_Fox_Visor;	// External class reference
	class UniformItem;	// External class reference
	class HeadgearItem;	// External class reference
	class SDT_pilot_p1_helmet;	// External class reference
	class SWLB_P1_Pilot_Helmet;	// External class reference
	
	class 21_HelmetP1_Pilot : SWLB_P1_Pilot_Helmet {
		author = "LastWar Team";
		displayName = "21st Clone Trooper P1 Helmet (Pilot)";
		hiddenSelectionsTextures[] = {"21_Unit\data\21_HelmetP1_Pilot.paa", "swlb_cee\data\swlb_p1_pilot_lifesupport_co.paa"};
	};
	
	class 21_HelmetP1_Keller : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "212th Clone Trooper P1 Helmet (Keller)";
		hiddenSelectionsTextures[] = {"21_Unit\data\21_HelmetP1_Keller.paa"};
	};
	
	class 21_Uniform_Keller : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "21st Clone Trooper Uniform (Keller)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Keller";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 21_camo_Bacara : SWLB_clone_airborne_nco_armor {
		displayName = "21st Clone trooper vest (Bacara)";
		hiddenSelectionsTextures[] = {"\21_unit\data\21_Camo2_Bacara.paa", "21_unit\data\21_Camo_Bacara.paa", "\21_unit\data\21_Camo2_Bacara.paa", "\21_unit\data\21_Camo2_Bacara.paa"};
	};
};

class CfgVehicles {
	class SWLB_clone_base_P2;	// External class reference
	class SWLB_clone_base_P1;	// External class reference
	class SWLB_clone_assault_base_P2;	// External class reference
	class SWLB_clone_cfr_base_P2;	// External class reference
	class SWLB_clone_medic_base_P2;	// External class reference
	class SWLB_clone_RTO_base_P2;	// External class reference
	class SWLB_clone_recon_base_P2;	// External class reference
	class SWLB_clone_recon_nco_base_P2;	// External class reference
	class SWLB_clone_recon_officer_base_P2;	// External class reference
	class SWLB_clone_airborne_base_P2;	// External class reference
	class SWLB_clone_airborne_nco_base_P2;	// External class reference
	class SWLB_clone_lieutenant_base_P2;	// External class reference
	class SWLB_clone_captain_base_P2;	// External class reference
	class SWLB_clone_commander_base_P2;	// External class reference
	class SWLB_clone_marshal_commander_base_P2;	// External class reference
	class SWLB_clone_arc_base_P2;	// External class reference
	class SWLB_clone_pilot_base_P2;	// External class reference
	class SWLB_clone_sniper_base_P2;	// External class reference
	class SWLB_clone_sg_base_P2;	// External class reference
	class SWLB_clone_at_base_P2;	// External class reference
	class SWLB_clone_backpack;	// External class reference
	class SWLB_clone_backpack_eod;	// External class reference
	class SWLB_clone_backpack_heavy;	// External class reference
	class SWLB_clone_backpack_medic;	// External class reference
	class SWLB_mando_base_assault;	// External class reference
	class SWLB_clone_backpack_RTO;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_RTO_mini_backpack;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	
	class Keller : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "21st Clone Trooper (Keller)";
		faction = "LW_Faction";
		editorSubcategory = "212_Legion";
		uniformclass = "Keller";
		hiddenSelectionsTextures[] = {"21_Unit\data\21_Armor1_Keller.paa", "21_Unit\data\21_Armor2_Keller.paa"};
		linkedItems[] = {"21_Helmet_Keller", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"21_Helmet_Keller", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
};

class cfgMods {
	author = "Last Force Project";
	timepacked = 1594648101;
};
