// config.bin - 23:38:29 07/23/20, generated in 0.03 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class ARC_Legion {
		units[] = {"Black", "Anime", "Forlorn", "Dornan", "Vex1", "Mortem", "78", "Frey", "Spectr", "Fur"};
		weapons[] = {"LS_ARC_helmet_P1_2_olaf", "LS_ARC_kama_olaf", "ARC_HelmetP2_Vex", "ARC_HelmetP1_Black", "ARC_Uniform_Black", "ARC_Camo_Black", "ARC_HelmetP1_Anime", "ARC_Uniform_Anime", "ARC_HelmetP1_Forlorn", "ARC_Uniform_Forlorn", "ARC_HelmetP1_Dornan", "ARC_Uniform_Dornan", "ARC_HelmetP1_Vex", "ARC_Uniform_Vex", "ARC_HelmetP1_07", "ARC_HelmetP1_Fur", "ARC_Uniform_Fur", "ARC_HelmetP1_Mortem", "ARC_Uniform_Mortem", "ARC_HelmetP1_78", "ARC_Uniform_78", "ARC_HelmetP1_Frey", "ARC_Uniform_Frey", "ARC_HelmetP1_Spectr", "ARC_Uniform_Spectr"};
	};
	author = "LastWarTeam";
	requiredAddons[] = {SWLB_CEE, "SWLB_clones"};
};

class CfgFactionClasses {
	class LW_Faction {
		displayName = "LastWar";
	};
};

class CfgEditorSubcategories {
	class ARC_Legion {
		displayName = "ARC LW Legion";
	};
};

class CfgWeapons {
	class H_HelmetO_ViperSP_hex_F;	// External class reference
	class SWLB_clone_ccVisor;	// External class reference
	class SWLB_clone_mcVisor;	// External class reference
	class SWLB_clone_nvg;	// External class reference
	class SWLB_clone_nvg_nco;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_nvg_spec;	// External class reference
	class SWLB_clone_nvg_spec_nco;	// External class reference
	class SWLB_clone_commando_nvg_antenna;	// External class reference
	class SWLB_clone_commando_nvg;	// External class reference
	class SWLB_clone_P1_2_helmet;	// External class reference
	class SWLB_clone_ARF_P1_helmet;	// External class reference
	class SWLB_clone_P1_helmet;	// External class reference
	class SWLB_clone_eng_helmet;	// External class reference
	class SWLB_clone_BARC_helmet;	// External class reference
	class SWLB_clone_P2_helmet;	// External class reference
	class SWLB_clone_AB_helmet;	// External class reference
	class SWLB_clone_P15_helmet;	// External class reference
	class SDT_Hazard_Helmet;	// External class reference
	class SDT_stealth_helmet;	// External class reference
	class Scout_helmet;	// External class reference
	class SWLB_clone_pilot_P2_helmet;	// External class reference
	class SWLB_clone_commando_helmet_k1;	// External class reference
	class SWLB_clone_recon_armor;	// External class reference
	class SWLB_clone_recon_officer_armor;	// External class reference
	class SWLB_clone_recon_nco_armor;	// External class reference
	class SWLB_clone_officer_armor;	// External class reference
	class SWLB_clone_medic_armor;	// External class reference
	class SWLB_clone_kama_armor;	// External class reference
	class SWLB_clone_mc_uniform;	// External class reference
	class SWLB_clone_commander_armor;	// External class reference
	class SWLB_clone_cfr_armor;	// External class reference
	class SWLB_clone_airborne_armor;	// External class reference
	class SWLB_clone_airborne_nco_armor;	// External class reference
	class SWLB_clone_arc_armor;	// External class reference
	class SWLB_clone_commando_eod_armor_k1;	// External class reference
	class SWLB_clone_commando_sniper_armor_k1;	// External class reference
	class SWLB_clone_commando_sl_armor_k1;	// External class reference
	class SWLB_clone_commando_tech_armor_k1;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	class SWLB_clone_commando_uniform_k1;	// External class reference
	class SWLA_BL_Sergeant_Vest;	// External class reference
	class SWLB_mando_og_helmet;	// External class reference
	class SWLB_mando_og_armor;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_mando_uniform;	// External class reference
	class SWLB_CEE_Force_Recon_Officer;	// External class reference
	class SWLB_CEE_P1_Rangefinder;	// External class reference
	class UniformItem;	// External class reference
	class HeadgearItem;	// External class reference
	class ItemInfo;	// External class reference
	class VestItem;	// External class reference
	class SDT_pilot_p1_helmet;	// External class reference
	
	class LS_ARC_helmet_P1_2_olaf : SWLB_clone_P1_2_helmet {
		author = SCHTAMP;
		displayName = "501st Olaf Clone trooper P1-2 helmet";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_helmet_p12_olaf_co.paa"};
	};
	
	class ARC_HelmetP2_Vex : SWLB_clone_P15_helmet {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper P2 Helmet (Vex)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_HelmetP2_Vex.paa"};
	};
	
	class ARC_Rangefinder_Vex : SWLB_clone_rangefinder {
		author = "LastWar Team";
		displayName = "ARC Clone trooper rangefinder (Vex)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Rangefinder_Vex.paa"};
	};
	
	class ARC_HelmetP1_Black : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper P1 Helmet (Black)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_HelmetP1_Black.paa"};
	};
	
	class ARC_HelmetP1_Anime : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper P1 Helmet (Anime)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_HelmetP1_Anime.paa"};
	};
	
	class ARC_HelmetP1_Forlorn : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper P1 Helmet (Forlorn)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_HelmetP1_Forlorn.paa"};
	};
	
	class ARC_HelmetP1_Dornan : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper P1 Helmet (Dornan)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_HelmetP1_Dornan.paa"};
	};
	
	class ARC_HelmetP15_Vex : SWLB_clone_P1_2_helmet {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper P1\2 Helmet (Vex)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Helmet15_Vex.paa"};
	};
	
	class ARC_HelmetP1_Vex : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper P1 Helmet (Vex)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_HelmetP1_Vex.paa"};
	};
	
	class ARC_HelmetP1_Fur : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper P1 Helmet (Fur)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_HelmetP1_Fur.paa"};
	};
	
	class ARC_HelmetP1_07 : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper P1 Helmet (07)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_HelmetP1_07.paa"};
	};
	
	class ARC_HelmetP1_Spectr : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper P1 Helmet (Spectr)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_HelmetP1_Spectr.paa"};
	};
	
	class ARC_HelmetP1_Frey : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper P1 Helmet (Frey)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_HelmetP1_Frey.paa"};
	};
	
	class ARC_HelmetP1_78 : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper P1 Helmet (78)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_HelmetP1_78.paa"};
	};
	
	class ARC_HelmetP1_Mortem : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper P1 Helmet (Mortem)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_HelmetP1_Mortem.paa"};
	};
	
	class ARC_Uniform_VexP2 : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper Uniform (Vex)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "VexP2";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARC_Uniform_Black : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper Uniform (Black)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Black";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARC_Uniform_Anime : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper Uniform (Anime)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Anime";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARC_Uniform_Forlorn : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper Uniform (Forlorn)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Forlorn";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARC_Uniform_Dornan : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper Uniform (Dornan)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Dornan";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARC_Uniform_Vex : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper Uniform (Vex)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Vex1";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARC_Uniform_Fur : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper Uniform (Fur)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Fur";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARC_Uniform_Spectr : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper Uniform (Spectr)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Spectr";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARC_Uniform_Mortem : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper Uniform (Mortem)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Mortem";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARC_Uniform_78 : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper Uniform (78)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "78";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARC_Uniform_Frey : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper Uniform (Frey)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Frey";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARC_Camo_Plate : SWLB_clone_arc_armor {
		displayName = "ARC Camo\Plate";
		hiddenSelectionsTextures[] = {"\SWLB_clones\data\arc_accessories_co.paa", "\SWLB_clones\data\officer_accessories_black_co.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "\SWLB_clones\SWLB_clone_arc_armor.p3d";
			containerClass = "Supply100";
			hiddenSelections[] = {"camo1", "camo2"};
			mass = 100;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 60;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Legs {
					hitpointName = "HitChest";
					armor = 60;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Arms {
					hitpointName = "HitChest";
					armor = 40;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class ARC_Camo_Plate_Vex : SWLB_clone_arc_armor {
		displayName = "ARC Camo\Plate (Vex)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Plate_Vex.paa", "ARC_Unit\data\ARC_Camo_Vex.paa"};
	};
	
	class LS_ARC_kama_olaf : ARC_Camo_Plate {
		author = "LastWar Team";
		displayName = "Olaf Clone Trooper Kama";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_arc_access_olaf_co.paa", "ARC_Unit\data\ARC_officer_access_olaf_co.paa"};
	};
	
	class ARC_Camo_Black : SWLB_CEE_Force_Recon_Officer {
		author = "LastWar Team";
		displayName = "ARC Camo (Black)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Acces_Black.paa", "ARC_Unit\data\ARC_Camo_Black.paa"};
	};
	
	class ARC_Camo_Anime : SWLB_CEE_Force_Recon_Officer {
		author = "LastWar Team";
		displayName = "ARC Camo (Anime)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Acces_Anime.paa", "ARC_Unit\data\ARC_Camo_Anime.paa"};
	};
	
	class ARC_Camo_78 : SWLB_CEE_Force_Recon_Officer {
		author = "LastWar Team";
		displayName = "ARC Camo (78)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Acces_78.paa", "ARC_Unit\data\ARC_Camo_78.paa"};
	};
	
	class ARC_Camo_Dornan : SWLB_CEE_Force_Recon_Officer {
		author = "LastWar Team";
		displayName = "ARC Camo (Dornan)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Acces_Dornan.paa", "ARC_Unit\data\ARC_Camo_Dornan.paa"};
	};
	
	class ARC_Camo_Vex : SWLB_CEE_Force_Recon_Officer {
		author = "LastWar Team";
		displayName = "ARC Camo (Vex)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Acces_Vex.paa", "ARC_Unit\data\ARC_Camo_VexP1.paa"};
	};
	
	class ARC_Camo_Fur : SWLB_CEE_Force_Recon_Officer {
		author = "LastWar Team";
		displayName = "ARC Camo (Fur)";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Acces_Fur.paa", "ARC_Unit\data\ARC_Camo_Fur.paa"};
	};
};

class CfgVehicles {
	class SWLB_clone_commando_base;	// External class reference
	class SWLB_clone_commando_backpack_k2;	// External class reference
	class SWLB_clone_commando_backpack_k2_rto;	// External class reference
	class SWLB_clone_commando_backpack_k2_eod;	// External class reference
	class SWLB_clone_base_P2;	// External class reference
	class SWLB_clone_base_P1;	// External class reference
	class SWLB_clone_assault_base_P2;	// External class reference
	class SWLB_clone_cfr_base_P2;	// External class reference
	class SWLB_clone_medic_base_P2;	// External class reference
	class SWLB_clone_RTO_base_P2;	// External class reference
	class SWLB_clone_recon_base_P2;	// External class reference
	class SWLB_clone_recon_nco_base_P2;	// External class reference
	class SWLB_clone_recon_officer_base_P2;	// External class reference
	class SWLB_clone_airborne_base_P2;	// External class reference
	class SWLB_clone_airborne_nco_base_P2;	// External class reference
	class SWLB_clone_lieutenant_base_P2;	// External class reference
	class SWLB_clone_captain_base_P2;	// External class reference
	class SWLB_clone_commander_base_P2;	// External class reference
	class SWLB_clone_marshal_commander_base_P2;	// External class reference
	class SWLB_clone_arc_base_P2;	// External class reference
	class SWLB_clone_pilot_base_P2;	// External class reference
	class SWLB_clone_sniper_base_P2;	// External class reference
	class SWLB_clone_sg_base_P2;	// External class reference
	class SWLB_clone_at_base_P2;	// External class reference
	class SWLB_clone_backpack;	// External class reference
	class SWLB_clone_backpack_eod;	// External class reference
	class SWLB_clone_backpack_heavy;	// External class reference
	class SWLB_mando_base_assault;	// External class reference
	class SWLB_clone_backpack_RTO;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_RTO_mini_backpack;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	
	class VexP2 : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper (VexP2)";
		faction = "LW_Faction";
		editorSubcategory = "ARC_Legion";
		uniformclass = "VexP2";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Armor1_VexP2.paa", "ARC_Unit\data\ARC_Armor2_VexP2.paa"};
		linkedItems[] = {"ARC_HelmetP2_Vex", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARC_HelmetP2_Vex", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Black : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper (Black)";
		faction = "LW_Faction";
		editorSubcategory = "ARC_Legion";
		uniformclass = "Black";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Armor1_Black.paa", "ARC_Unit\data\ARC_Armor2_Black.paa"};
		linkedItems[] = {"ARC_HelmetP1_Black", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARC_HelmetP1_Black", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Anime : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper (Anime)";
		faction = "LW_Faction";
		editorSubcategory = "ARC_Legion";
		uniformclass = "Anime";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Armor1_Anime.paa", "ARC_Unit\data\ARC_Armor2_Anime.paa"};
		linkedItems[] = {"ARC_HelmetP1_Anime", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARC_HelmetP1_Anime", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Forlorn : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper (Forlorn)";
		faction = "LW_Faction";
		editorSubcategory = "ARC_Legion";
		uniformclass = "Forlorn";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Armor1_Forlorn.paa", "ARC_Unit\data\ARC_Armor2_Forlorn.paa"};
		linkedItems[] = {"ARC_HelmetP1_Forlorn", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARC_HelmetP1_Forlorn", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Dornan : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper (Dornan)";
		faction = "LW_Faction";
		editorSubcategory = "ARC_Legion";
		uniformclass = "Dornan";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Armor1_Dornan.paa", "ARC_Unit\data\ARC_Armor2_Dornan.paa"};
		linkedItems[] = {"ARC_HelmetP1_Dornan", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARC_HelmetP1_Dornan", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Vex1 : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper (Vex)";
		faction = "LW_Faction";
		editorSubcategory = "ARC_Legion";
		uniformclass = "Vex";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Armor1_Vex.paa", "ARC_Unit\data\ARC_Armor2_Vex.paa"};
		linkedItems[] = {"ARC_HelmetP1_Vex", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARC_HelmetP1_Vex", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Fur : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper (Fur)";
		faction = "LW_Faction";
		editorSubcategory = "ARC_Legion";
		uniformclass = "Fur";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Armor1_Fur.paa", "ARC_Unit\data\ARC_Armor2_Fur.paa"};
		linkedItems[] = {"ARC_HelmetP1_Fur", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARC_HelmetP1_Fur", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Spectr : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper (Spectr)";
		faction = "LW_Faction";
		editorSubcategory = "ARC_Legion";
		uniformclass = "Spectr";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Armor1_Spectr.paa", "ARC_Unit\data\ARC_Armor2_Spectr.paa"};
		linkedItems[] = {"ARC_HelmetP1_Spectr", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARC_HelmetP1_Spectr", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Frey : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper (Frey)";
		faction = "LW_Faction";
		editorSubcategory = "ARC_Legion";
		uniformclass = "Frey";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Armor1_Frey.paa", "ARC_Unit\data\ARC_Armor2_Frey.paa"};
		linkedItems[] = {"ARC_HelmetP1_Frey", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARC_HelmetP1_Frey", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class 78 : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper (78)";
		faction = "LW_Faction";
		editorSubcategory = "ARC_Legion";
		uniformclass = "78";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Armor1_78.paa", "ARC_Unit\data\ARC_Armor2_78.paa"};
		linkedItems[] = {"ARC_HelmetP1_78", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARC_HelmetP1_78", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Mortem : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper (Mortem)";
		faction = "LW_Faction";
		editorSubcategory = "ARC_Legion";
		uniformclass = "Mortem";
		hiddenSelectionsTextures[] = {"ARC_Unit\data\ARC_Armor1_Mortem.paa", "ARC_Unit\data\ARC_Armor2_Mortem.paa"};
		linkedItems[] = {"ARC_HelmetP1_Mortem", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARC_HelmetP1_Mortem", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
};

class cfgMods {
	author = "GLyba";
	timepacked = 1594312071;
};
