// config.bin - 23:38:17 07/23/20, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class 327_Legion {
		units[] = {"Ned", "Rook"};
		weapons[] = {"327_HelmetP1_Ned", "327_Uniform_Ned", "327_HelmetP1_Rook", "327_Uniform_Rook", "327_HelmetP1_ARF"};
		author = "LastWarTeam";
		requiredAddons[] = {"SWLB_clones"};
	};
};

class CfgFactionClasses {
	class LW_Faction {
		displayName = "LastWar";
	};
};

class CfgEditorSubcategories {
	class 327_Legion {
		displayName = "327th LW Legion";
	};
};

class CfgWeapons {
	class H_HelmetO_ViperSP_hex_F;	// External class reference
	class SWLB_clone_ccVisor;	// External class reference
	class SWLB_clone_mcVisor;	// External class reference
	class SWLB_clone_nvg;	// External class reference
	class SWLB_clone_nvg_nco;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_nvg_spec;	// External class reference
	class SWLB_clone_nvg_spec_nco;	// External class reference
	class SWLB_clone_commando_nvg_antenna;	// External class reference
	class SWLB_clone_commando_nvg;	// External class reference
	class SWLB_clone_P1_2_helmet;	// External class reference
	class SWLB_clone_ARF_P1_helmet;	// External class reference
	class SWLB_clone_P1_helmet;	// External class reference
	class SWLB_clone_eng_helmet;	// External class reference
	class SWLB_clone_BARC_helmet;	// External class reference
	class SWLB_clone_P2_helmet;	// External class reference
	class SWLB_clone_AB_helmet;	// External class reference
	class SWLB_clone_P15_helmet;	// External class reference
	class SDT_Hazard_Helmet;	// External class reference
	class SDT_stealth_helmet;	// External class reference
	class Scout_helmet;	// External class reference
	class SWLB_clone_pilot_P2_helmet;	// External class reference
	class SWLB_clone_commando_helmet_k1;	// External class reference
	class SWLB_clone_recon_armor;	// External class reference
	class SWLB_clone_recon_officer_armor;	// External class reference
	class SWLB_clone_recon_nco_armor;	// External class reference
	class SWLB_clone_officer_armor;	// External class reference
	class SWLB_clone_medic_armor;	// External class reference
	class SWLB_clone_kama_armor;	// External class reference
	class SWLB_clone_mc_uniform;	// External class reference
	class SWLB_clone_commander_armor;	// External class reference
	class SWLB_clone_cfr_armor;	// External class reference
	class SWLB_clone_airborne_armor;	// External class reference
	class SWLB_clone_airborne_nco_armor;	// External class reference
	class SWLB_clone_arc_armor;	// External class reference
	class SWLB_clone_commando_eod_armor_k1;	// External class reference
	class SWLB_clone_commando_sniper_armor_k1;	// External class reference
	class SWLB_clone_commando_sl_armor_k1;	// External class reference
	class SWLB_clone_commando_tech_armor_k1;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	class SWLB_clone_commando_uniform_k1;	// External class reference
	class SWLA_BL_Sergeant_Vest;	// External class reference
	class SWLB_mando_og_helmet;	// External class reference
	class SWLB_mando_og_armor;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_mando_uniform;	// External class reference
	class UniformItem;	// External class reference
	class HeadgearItem;	// External class reference
	class SDT_pilot_p1_helmet;	// External class reference
	class SWLB_P1_Pilot_Helmet;	// External class reference
	class SWLB_CEE_Hazard_Helmet;	// External class reference
	class SWLB_clone_ARF_P2_helmet;	// External class reference
	
	class 327_HelmetP2_ENG : SWLB_clone_eng_helmet {
		author = "LastWarTeam";
		displayName = "327th Clone Trooper ENG helmet";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_HelmetP2_ENG.paa"};
	};
	
	class 327_Helmet15_ARC : SWLB_clone_P15_helmet {
		author = "LastWar Team";
		displayName = "327th Clone Trooper ARC Helmet";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_Helmet15_ARC.paa"};
	};
	
	class 327_ARF_P2_helmet : SWLB_clone_ARF_P2_helmet {
		author = "LastWar Team";
		displayName = "327th Clone trooper P2 ARF helmet";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_HelmetP1_ARF.paa", "", "327_Unit\data\327_ARF_Flaps.paa"};
	};
	
	class 327_HelmetP2_Pilot : SWLB_clone_pilot_P2_helmet {
		author = "LastWar Team";
		displayName = "327th Clone Trooper P2 Pilot Helmet";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_HelmetP2_Pilot.paa", "327_Unit\data\327_HelmetP2_Pilot.paa"};
	};
	
	class 327_Helmet_Hazard : SWLB_CEE_Hazard_Helmet {
		author = "LastWar Team";
		displayName = "327th Clone Trooper Hazard Helmet";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_Helmet_Hazard.paa"};
	};
	
	class 327_HelmetP2_DW : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "327th Clone Trooper P2 Helmet (DW)";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_HelmetP2_DW.paa"};
	};
	
	class 327_HelmetP2_Ned : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "327th Clone Trooper P2 Helmet (Ned)";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_HelmetP2_Ned.paa"};
	};
	
	class 327_HelmetP15_Rook : SWLB_clone_P15_helmet {
		author = "LastWar Team";
		displayName = "327th Clone Trooper P2 ARC Helmet (Rook)";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_HelmetP15_Rook.paa"};
	};
	
	class 327_HelmetP1_Pilot : SWLB_P1_Pilot_Helmet {
		author = "LastWar Team";
		displayName = "327th Clone Trooper P1 Helmet (Pilot)";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_HelmetP1_Pilot.paa", "swlb_cee\data\swlb_p1_pilot_lifesupport_co.paa"};
	};
	
	class 327_HelmetP1_ARF : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "327th Clone Trooper P1 Helmet (ARF)";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_HelmetP1_ARF.paa"};
	};
	
	class 327_HelmetP1_DW : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "327th Clone Trooper P1 Helmet (DW)";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_HelmetP1_DW.paa"};
	};
	
	class 327_HelmetP1_Ned : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "327th Clone Trooper P1 Helmet (Ned)";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_HelmetP1_Ned.paa"};
	};
	
	class 327_HelmetP1_Rook : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "327th Clone Trooper P1 Helmet (Rook)";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_HelmetP1_Rook.paa"};
	};
	
	class 327_Uniform_DW : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "327th Clone Trooper Uniform (DW)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "DW";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 327_Uniform_Ned : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "327th Clone Trooper Uniform (Ned)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Ned";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 327_Uniform_Rook : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "327th Clone Trooper Uniform (Rook)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Rook";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 327_Camo_Officer : SWLB_clone_officer_armor {
		author = "LastWar Team";
		displayName = "327th Camo (Officer)";
		hiddenSelectionsTextures[] = {"327_unit\data\327_Camo.paa"};
	};
	
	class 327_Camo_SG : SWLB_clone_kama_armor {
		author = "LastWar Team";
		displayName = "327th Camo (SG)";
		hiddenSelectionsTextures[] = {"327_unit\data\327_Camo.paa"};
	};
};

class CfgVehicles {
	class SWLB_clone_commando_base;	// External class reference
	class SWLB_clone_commando_backpack_k2;	// External class reference
	class SWLB_clone_commando_backpack_k2_rto;	// External class reference
	class SWLB_clone_commando_backpack_k2_eod;	// External class reference
	class SWLB_clone_base_P2;	// External class reference
	class SWLB_clone_base_P1;	// External class reference
	class SWLB_clone_assault_base_P2;	// External class reference
	class SWLB_clone_cfr_base_P2;	// External class reference
	class SWLB_clone_medic_base_P2;	// External class reference
	class SWLB_clone_RTO_base_P2;	// External class reference
	class SWLB_clone_recon_base_P2;	// External class reference
	class SWLB_clone_recon_nco_base_P2;	// External class reference
	class SWLB_clone_recon_officer_base_P2;	// External class reference
	class SWLB_clone_airborne_base_P2;	// External class reference
	class SWLB_clone_airborne_nco_base_P2;	// External class reference
	class SWLB_clone_lieutenant_base_P2;	// External class reference
	class SWLB_clone_captain_base_P2;	// External class reference
	class SWLB_clone_commander_base_P2;	// External class reference
	class SWLB_clone_marshal_commander_base_P2;	// External class reference
	class SWLB_clone_arc_base_P2;	// External class reference
	class SWLB_clone_pilot_base_P2;	// External class reference
	class SWLB_clone_sniper_base_P2;	// External class reference
	class SWLB_clone_sg_base_P2;	// External class reference
	class SWLB_clone_at_base_P2;	// External class reference
	class SWLB_clone_backpack;	// External class reference
	class SWLB_clone_backpack_eod;	// External class reference
	class SWLB_clone_backpack_heavy;	// External class reference
	class SWLB_mando_base_assault;	// External class reference
	class SWLB_clone_backpack_RTO;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_RTO_mini_backpack;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	
	class DW : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "327th Clone Trooper (DW)";
		faction = "LW_Faction";
		editorSubcategory = "212_Legion";
		uniformclass = "DW";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_Armor1_DW.paa", "327_Unit\data\327_Armor2_DW.paa"};
		linkedItems[] = {"327_HelmetP2_DW", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"327_HelmetP2_DW", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Ned : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "327th Clone Trooper (Ned)";
		faction = "LW_Faction";
		editorSubcategory = "212_Legion";
		uniformclass = "Ned";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_Armor1_Ned.paa", "327_Unit\data\327_Armor2_Ned.paa"};
		linkedItems[] = {"327_HelmetP1_Ned", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"327_HelmetP1_Ned", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Rook : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "327th Clone Trooper (Rook)";
		faction = "LW_Faction";
		editorSubcategory = "212_Legion";
		uniformclass = "Rook";
		hiddenSelectionsTextures[] = {"327_Unit\data\327_Armor1_Rook.paa", "327_Unit\data\327_Armor2_Rook.paa"};
		linkedItems[] = {"327_HelmetP1_Rook", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"327_HelmetP1_Rook", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
};

class cfgMods {
	author = "GLyba";
	timepacked = 1595004325;
};
