// config.bin - 23:39:50 07/23/20, generated in 0.03 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class VOID {
		units[] = {"JP_Void", "LS_void_heavy_backpack", "LS_void_pilot_P1", "LS_nightwish_backpack_RTO", "LS_void_commander_P1", "LS_void_nightwish_ARF", "LS_void_clone_ARF", "LS_void_uport_ARF", "LS_void_uport_ARF", "LS_uport_backpack_RTO", "LS_void_arty_P2", "LS_void_recon_P2", "LS_void_assault_P2", "LS_void_backpack_RTO", "LS_void_backpack", "LS_void_medic_backpack", "LS_void_arc_P1"};
		weapons[] = {"LS_void_arc_vest", "LS_void_clone_nvg", "LS_void_clone_nvg_spec", "LS_void_clone_nvg_nco", "LS_void_clone_rangefinder", "LS_void_clone_ccVisor", "LS_void_clone_mcVisor", "LS_P1_pilot_void", "LS_void_commander_uniform", "LS_ARF_helmet", "LS_void_arf_uniform", "LS_void_arf_nightwish_uniform", "LS_void_goty_kama", "LS_void_kama", "LS_void_uport_uniform", "LS_void_officer_armor", "LS_void_commander_armor", "LS_void_lieutenant_armor", "TMP_716_armor", "LS_P1_helmet_void", "LS_P1_helmet_void_1", "LS_P2_helmet_void", "LS_P2_helmet_void_1", "LS_void_arty_uniform", "LS_void_recon_uniform", "LS_void_assault_uniform", "LS_P1_arc_helmet_void", "LS_void_arc_uniform"};
		author = "LastWarTeam";
		requiredAddons[] = {"SWLB_clones", SWLB_CEE, "Jetpack"};
	};
};

class CfgFactionClasses {
	class LW_Faction {
		displayName = "LastWar";
	};
};

class CfgEditorSubcategories {
	class LS_void_Legion {
		displayName = "Void LW Legion";
	};
};

class CfgWeapons {
	class SWLB_P1_SpecOps_Helmet;	// External class reference
	class SWLB_P2_SpecOps_Helmet;	// External class reference
	class SWLB_clone_eng_helmet;	// External class reference
	class SWLB_clone_ccVisor;	// External class reference
	class SWLB_clone_mcVisor;	// External class reference
	class SWLB_clone_nvg;	// External class reference
	class SWLB_clone_nvg_nco;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_nvg_spec;	// External class reference
	class SWLB_clone_nvg_spec_nco;	// External class reference
	class SWLB_clone_commando_nvg_antenna;	// External class reference
	class SWLB_clone_commando_nvg;	// External class reference
	class SWLB_clone_P2_helmet;	// External class reference
	class SWLB_clone_P1_helmet;	// External class reference
	class SWLB_clone_AB_helmet;	// External class reference
	class SWLB_clone_P15_helmet;	// External class reference
	class SWLB_clone_ARF_P1_helmet;	// External class reference
	class SWLB_clone_pilot_P2_helmet;	// External class reference
	class SWLB_clone_commando_helmet_k1;	// External class reference
	class SWLB_clone_recon_armor;	// External class reference
	class SWLB_clone_recon_officer_armor;	// External class reference
	class SWLB_clone_lieutenant_armor;	// External class reference
	class SWLB_clone_recon_nco_armor;	// External class reference
	class SWLB_clone_officer_armor;	// External class reference
	class SWLB_clone_medic_armor;	// External class reference
	class SWLB_clone_kama_armor;	// External class reference
	class SWLB_clone_commander_armor;	// External class reference
	class SWLB_clone_cfr_armor;	// External class reference
	class SWLB_clone_airborne_armor;	// External class reference
	class SWLB_clone_airborne_nco_armor;	// External class reference
	class SWLB_clone_arc_armor;	// External class reference
	class SWLB_clone_commando_eod_armor_k1;	// External class reference
	class SWLB_clone_commando_sniper_armor_k1;	// External class reference
	class SWLB_clone_commando_sl_armor_k1;	// External class reference
	class SWLB_clone_commando_tech_armor_k1;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	class SWLB_clone_commando_uniform_k1;	// External class reference
	class SWLB_CEE_Force_Recon_Officer;	// External class reference
	class UniformItem;	// External class reference
	class SWLB_P1_Pilot_Helmet;	// External class reference
	class SWLB_CEE_Hazard_Helmet;	// External class reference
	
	class LS_void_pilot_P2_helmet : SWLB_clone_pilot_P2_helmet {
		author = "LastWarTeam";
		scope = 2;
		scopecurator = 2;
		displayName = "Void Clone pilot P2 helmet";
		hiddenSelectionsTextures[] = {"void_unit\data\void_helmet_pilot_p2_co.paa"};
	};
	
	class LS_P1_specops_helmet_void : SWLB_P1_SpecOps_Helmet {
		author = "LastWarTeam";
		scope = 2;
		scopecurator = 2;
		displayName = " Void Clone trooper P1 Special Activities Helmet";
		hiddenSelectionsTextures[] = {"void_unit\data\void_helmet_specops_p1_co.paa", "void_unit\data\void_helmet_specops_p1_co.paa"};
	};
	
	class LS_P2_specops_helmet_void : SWLB_P2_SpecOps_Helmet {
		author = "LastWarTeam";
		scope = 2;
		scopecurator = 2;
		displayName = " Void Clone trooper P2 Special Activities Helmet";
		hiddenSelectionsTextures[] = {"void_unit\data\void_helmet_specops_p2_co.paa"};
	};
	
	class LS_eng_helmet_void : SWLB_clone_eng_helmet {
		author = "LastWarTeam";
		scope = 2;
		scopecurator = 2;
		displayName = " Void Clone troooper engineer Helmet";
		hiddenSelectionsTextures[] = {"void_unit\data\void_helmet_eng_co.paa"};
	};
	
	class LS_P15_helmet_void : SWLB_clone_P15_helmet {
		author = "LastWarTeam";
		scope = 2;
		scopecurator = 2;
		displayName = " Void Clone ARC trooper helmet";
		hiddenSelectionsTextures[] = {"void_unit\data\void_helmet_p15_co.paa"};
	};
	
	class LS_void_kama : SWLB_clone_kama_armor {
		author = "LastWarTeam";
		scope = 2;
		scopecurator = 2;
		displayName = "Void Clone Trooper Kama";
		hiddenSelections[] = {"camo1", "rank"};
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Offucer_Vest.paa", ""};
	};
	
	class LS_void_arc_vest : SWLB_CEE_Force_Recon_Officer {
		displayName = "Void ARC Trooper Kama";
		hiddenSelectionsTextures[] = {"void_unit\data\3rdparty\arc_accessories_co.paa", "void_unit\data\3rdparty\arc_vest_co.paa"};
	};
	
	class LS_void_goty_kama : SWLB_CEE_Force_Recon_Officer {
		author = "LastWarTeam";
		displayName = "Void Clone Trooper Kama (Goty)";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Acces.paa", "void_unit\data\Void_Offucer_Vest.paa"};
	};
	
	class LS_void_officer_armor : SWLB_clone_officer_armor {
		author = "LastWarTeam";
		displayName = "Void Clone Trooper Officer Vest";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Offucer_Vest.paa"};
	};
	
	class LS_void_lieutenant_armor : SWLB_clone_lieutenant_armor {
		author = "LastWarTeam";
		displayName = "Void Clone Trooper Lieutenant Vest";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Offucer_Vest.paa"};
	};
	
	class LS_void_commander_armor : SWLB_clone_commander_armor {
		author = "LastWarTeam";
		displayName = "Void Clone Trooper Commander Vest";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Offucer_Vest.paa"};
	};
	
	class LS_P1_helmet_void : SWLB_clone_P1_helmet {
		author = "LastWarTeam";
		scope = 2;
		scopecurator = 2;
		displayName = "Void Clone Trooper P1 helmet";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_HelmetP1.paa"};
	};
	
	class LS_P1_arc_helmet_void : LS_P1_helmet_void {
		displayName = "Void ARC Trooper P1 helmet";
		hiddenSelectionsTextures[] = {"void_unit\data\3rdparty\arc_P1_helmet_co.paa"};
	};
	
	class LS_void_hazard_helmet : SWLB_CEE_Hazard_Helmet {
		author = "LastWarTeam";
		scope = 2;
		scopecurator = 2;
		displayName = "Void Clone Trooper Hazard helmet";
		hiddenSelectionsTextures[] = {"void_unit\data\Hazard_helmet_co.paa"};
	};
	
	class LS_P1_helmet_void_1 : LS_P1_helmet_void {
		displayName = "Void Clone Trooper P1 helmet (Officer)";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_HelmetP1_Officer.paa"};
	};
	
	class LS_P1_helmet_void_goty : LS_P1_helmet_void {
		displayName = "Void Clone Trooper P1 helmet (Goty)";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_HelmetP1_Goty.paa"};
	};
	
	class LS_P1_helmet_void_commander : LS_P1_helmet_void {
		displayName = "Void Clone Commander P1 helmet";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_HelmetP1_Kivi.paa"};
	};
	
	class LS_P2_helmet_void : SWLB_clone_P2_helmet {
		author = "LastWarTeam";
		scope = 2;
		scopecurator = 2;
		displayName = "Void Clone Trooper P2 helmet";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_HelmetP2.paa"};
	};
	
	class Void_Helmet15_ARC : SWLB_clone_P15_helmet {
		author = "LastWar Team";
		displayName = "Void Clone Trooper P2 ARC Helmet";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Helmet15_ARC.paa"};
	};
	
	class LS_P2_helmet_void_1 : LS_P2_helmet_void {
		author = "LastWarTeam";
		displayName = "Void Clone Trooper P2 Helmet (Officer)";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_HelmetP2_Officer.paa"};
	};
	
	class LS_ARF_helmet_uport : SWLB_clone_ARF_P1_helmet {
		author = "LastWarTeam";
		displayName = "Void Clone Trooper ARF helmet (Yport)";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Helmet_Uport.paa", "void_unit\data\Void_Helmet_Uport.paa", ""};
	};
	
	class LS_ARF_helmet : SWLB_clone_ARF_P1_helmet {
		author = "LastWarTeam";
		displayName = "Void Clone Trooper ARF helmet";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Helmet_ARF.paa", "void_unit\data\Void_Helmet_ARF.paa", ""};
	};
	
	class LS_P1_pilot_void : SWLB_P1_Pilot_Helmet {
		author = "SW Legion Studios";
		displayName = "Void Clone Trooper P1 Pilot Helmet";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_HelmetP1_Pilot.paa", "void_unit\data\Void_PilotP1_Lifesupport.paa"};
	};
	
	class LS_void_arty_uniform : SWLB_clone_uniform {
		author = "LastWarTeam";
		scope = 2;
		scopecurator = 2;
		displayName = "Void Clone Trooper Uniform (Dominus)";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Arta.paa", "void_unit\data\Void_Armor2_Arta.paa"};
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "LS_void_arty_P2";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class LS_void_arc_uniform : LS_void_arty_uniform {
		displayName = "Void ARC Trooper Uniform";
		hiddenSelectionsTextures[] = {"void_unit\data\3rdparty\arc_camo_co.paa", "void_unit\data\3rdparty\arc_camo1_co.paa"};
		
		class ItemInfo : ItemInfo {
			uniformClass = "LS_void_arc_P1";
		};
	};
	
	class LS_void_taldin_arc_uniform : LS_void_arty_uniform {
		displayName = "Void ARC Trooper Uniform (Tal`din)";
		hiddenSelectionsTextures[] = {"void_unit\data\3rdparty\Void_Armor1_Taldin.paa", "void_unit\data\3rdparty\Void_Armor2_Taldin.paa"};
		
		class ItemInfo : ItemInfo {
			uniformClass = "LS_void_arc_taldin_P1";
		};
	};
	
	class LS_void_recon_uniform : LS_void_arty_uniform {
		displayName = "Void Clone Trooper Uniform (Nebula)";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Rozved.paa", "void_unit\data\Void_Armor2_Rozved.paa"};
		
		class ItemInfo : ItemInfo {
			uniformClass = "LS_void_recon_P2";
		};
	};
	
	class LS_void_assault_uniform : LS_void_arty_uniform {
		displayName = "Void Clone Trooooper Uniform (Attero)";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Shturm.paa", "void_unit\data\Void_Armor2_Shturm.paa"};
		
		class ItemInfo : ItemInfo {
			uniformClass = "LS_void_assault_P2";
		};
	};
	
	class LS_void_uport_uniform : LS_void_arty_uniform {
		displayName = "Void Clone Trooper Uniform (Uport)";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Uport.paa", "void_unit\data\Void_Armor2_Uport.paa"};
		
		class ItemInfo : ItemInfo {
			uniformClass = "LS_void_uport_ARF";
		};
	};
	
	class LS_void_goty_uniform : LS_void_arty_uniform {
		displayName = "Void Clone Trooper Uniform (Goty)";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Goty.paa", "void_unit\data\Void_Armor2_Goty.paa"};
		
		class ItemInfo : ItemInfo {
			uniformClass = "LS_void_goty_P1";
		};
	};
	
	class LS_void_arf_nightwish_uniform : LS_void_arty_uniform {
		displayName = "Void Clone Trooper Uniform (Nightwish)";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Nightwish.paa", "void_unit\data\Void_Armor2_ARF.paa"};
		
		class ItemInfo : ItemInfo {
			uniformClass = "LS_void_nightwish_ARF";
		};
	};
	
	class LS_void_arf_uniform : LS_void_arty_uniform {
		displayName = "Void Clone Trooper Uniform (ARF)";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_ARF.paa", "void_unit\data\Void_Armor2_ARF.paa"};
		
		class ItemInfo : ItemInfo {
			uniformClass = "LS_void_clone_ARF";
		};
	};
	
	class LS_void_commander_uniform : LS_void_arty_uniform {
		displayName = "Void Clone Commander Uniform";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Kivi.paa", "void_unit\data\Void_Armor2_Kivi.paa"};
		
		class ItemInfo : ItemInfo {
			uniformClass = "LS_void_commander_P1";
		};
	};
	
	class LS_void_clone_nvg : SWLB_clone_nvg {
		author = "LastWarTeam";
		displayName = "Void NV visor";
		hiddenSelectionsTextures[] = {"void_unit\data\void_nvgs_co.paa"};
	};
	
	class LS_void_clone_nvg_spec : SWLB_clone_nvg_spec {
		author = "LastWarTeam";
		displayName = "Void Clone specialist NV visor";
		hiddenSelectionsTextures[] = {"void_unit\data\void_nvgs_co.paa"};
	};
	
	class LS_void_clone_nvg_nco : SWLB_clone_nvg_nco {
		author = "LastWarTeam";
		displayName = "Void NCO NV visor";
		hiddenSelectionsTextures[] = {"void_unit\data\void_nvgs_co.paa"};
	};
	
	class LS_void_clone_rangefinder : SWLB_clone_rangefinder {
		author = "LastWarTeam";
		displayName = "Void Clone rangefinder";
		hiddenSelectionsTextures[] = {"void_unit\data\void_nvgs_co.paa"};
	};
	
	class LS_void_clone_ccVisor : SWLB_clone_ccVisor {
		author = "LastWarTeam";
		displayName = "Void CC visor";
		hiddenSelectionsTextures[] = {"void_unit\data\void_nvgs_co.paa"};
	};
	
	class LS_void_clone_mcVisor : SWLB_clone_mcVisor {
		author = "LastWarTeam";
		displayName = "Void MC visor";
		hiddenSelectionsTextures[] = {"void_unit\data\void_nvgs_co.paa", "void_unit\data\void_nvgs_co.paa"};
	};
};

class CfgVehicles {
	class SWLB_clone_commando_base;	// External class reference
	class SWLB_clone_commando_backpack_k2;	// External class reference
	class SWLB_clone_commando_backpack_k2_rto;	// External class reference
	class SWLB_clone_commando_backpack_k2_eod;	// External class reference
	class SWLB_clone_base_P2;	// External class reference
	class SWLB_clone_assault_base_P2;	// External class reference
	class SWLB_clone_cfr_base_P2;	// External class reference
	class SWLB_clone_medic_base_P2;	// External class reference
	class SWLB_clone_RTO_base_P2;	// External class reference
	class SWLB_clone_recon_base_P2;	// External class reference
	class SWLB_clone_recon_nco_base_P2;	// External class reference
	class SWLB_clone_recon_officer_base_P2;	// External class reference
	class SWLB_clone_airborne_base_P2;	// External class reference
	class SWLB_clone_airborne_nco_base_P2;	// External class reference
	class SWLB_clone_lieutenant_base_P2;	// External class reference
	class SWLB_clone_captain_base_P2;	// External class reference
	class SWLB_clone_commander_base_P2;	// External class reference
	class SWLB_clone_marshal_commander_base_P2;	// External class reference
	class SWLB_clone_arc_base_P2;	// External class reference
	class SWLB_clone_pilot_base_P2;	// External class reference
	class SWLB_clone_sniper_base_P2;	// External class reference
	class SWLB_clone_sg_base_P2;	// External class reference
	class SWLB_clone_at_base_P2;	// External class reference
	class SWLB_clone_backpack;	// External class reference
	class SWLB_clone_backpack_eod;	// External class reference
	class SWLB_clone_backpack_heavy;	// External class reference
	class SWLB_clone_backpack_RTO;	// External class reference
	class SWLB_clone_RTO_mini_backpack;	// External class reference
	class SWLB_clone_base_P1;	// External class reference
	
	class LS_void_backpack_RTO : SWLB_clone_backpack_RTO {
		author = "LastWarTeam";
		scope = 2;
		scopecurator = 2;
		displayName = "Void RTO Backpack";
		hiddenSelectionsTextures[] = {"void_unit\data\backpack_rto_co.paa", "", "", "", "void_unit\data\backpack_rto_co.paa"};
	};
	
	class LS_uport_backpack_RTO : LS_void_backpack_RTO {
		displayName = "Void RTO Backpack (Uport)";
		hiddenSelectionsTextures[] = {"void_unit\data\uport_backpack_rto_co.paa", "", "", "", "void_unit\data\uport_backpack_rto_co.paa"};
	};
	
	class LS_nightwish_backpack_RTO : LS_void_backpack_RTO {
		displayName = "Void Nightwish RTO Backpack";
		hiddenSelectionsTextures[] = {"void_unit\data\nightwish_rto_co.paa", "", "", "", "void_unit\data\nightwish_rto_co.paa"};
	};
	
	class LS_void_backpack : SWLB_clone_backpack {
		author = "LastWarTeam";
		scope = 2;
		scopecurator = 2;
		displayName = "Void Backpack";
		hiddenSelectionsTextures[] = {"void_unit\data\backpack_co.paa", "void_unit\data\backpack_co.paa"};
	};
	
	class LS_void_medic_backpack : LS_void_backpack {
		displayName = "Void Medic Backpack";
		hiddenSelectionsTextures[] = {"void_unit\data\backpack_medic_co.paa", "void_unit\data\backpack_medic_co.paa", "", "void_unit\data\backpack_medic_co.paa"};
	};
	
	class LS_void_heavy_backpack : LS_void_backpack {
		maximumload = 320;
		displayName = "Void Heavy Backpack";
		hiddenSelectionsTextures[] = {"void_unit\data\backpack_co.paa", "void_unit\data\backpack_co.paa", "void_unit\data\backpack_co.paa"};
	};
	
	class LS_void_arty_P1 : SWLB_clone_base_P1 {
		author = "LastWarTeam";
		displayName = "Void Dominus clone trooper";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_arty_uniform";
		backpack = "LS_void_backpack";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Arta.paa", "void_unit\data\Void_Armor2_Arta.paa"};
		linkedItems[] = {"SWLB_clone_basic_armor", "LS_P1_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"SWLB_clone_basic_armor", "LS_P1_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LS_void_arc_taldin_P1 : SWLB_clone_base_P1 {
		author = "LastWarTeam";
		displayName = "Void ARC clone trooper P1";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_taldin_arc_uniform";
		backpack = "JP_Void";
		hiddenSelectionsTextures[] = {"void_unit\data\3rdparty\Void_Armor1_Taldin.paa", "void_unit\data\3rdparty\Void_Armor2_Taldin.paa"};
		linkedItems[] = {"LS_void_arc_vest", "LS_P1_arc_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"LS_void_arc_vest", "LS_P1_arc_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LS_void_arc_P1 : SWLB_clone_base_P1 {
		author = "LastWarTeam";
		displayName = "Void ARC clone trooper P1";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_arc_uniform";
		backpack = "JP_Void";
		hiddenSelectionsTextures[] = {"void_unit\data\3rdparty\arc_camo_co.paa", "void_unit\data\3rdparty\arc_camo1_co.paa"};
		linkedItems[] = {"LS_void_arc_vest", "LS_P1_arc_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"LS_void_arc_vest", "LS_P1_arc_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LS_void_pilot_P1 : SWLB_clone_base_P1 {
		author = "LastWarTeam";
		displayName = "Void Pilot clone trooper P1";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_arty_uniform";
		backpack = "LS_void_backpack_RTO";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Arta.paa", "void_unit\data\Void_Armor2_Arta.paa"};
		linkedItems[] = {"SWLB_clone_basic_armor", "LS_P1_pilot_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"SWLB_clone_basic_armor", "LS_P1_pilot_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LS_void_goty_P1 : SWLB_clone_base_P1 {
		author = "LastWarTeam";
		displayName = "Void Goty clone trooper P1";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_goty_uniform";
		backpack = "LS_void_backpack";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Goty.paa", "void_unit\data\Void_Armor2_Goty.paa"};
		linkedItems[] = {"LS_void_goty_kama", "LS_P1_helmet_void_goty", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"LS_void_goty_kama", "LS_P1_helmet_void_goty", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LS_void_recon_P1 : SWLB_clone_base_P1 {
		author = "LastWarTeam";
		displayName = "Void Nebula clone trooper P1";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_recon_uniform";
		backpack = "LS_void_backpack_RTO";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Rozved.paa", "void_unit\data\Void_Armor2_Rozved.paa"};
		linkedItems[] = {"SWLB_clone_basic_armor", "LS_P1_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"SWLB_clone_basic_armor", "LS_P1_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LS_void_assault_P1 : SWLB_clone_base_P1 {
		author = "LastWarTeam";
		displayName = "Void Attero clone trooper P1";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_assault_uniform";
		backpack = "LS_void_backpack";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Shturm.paa", "void_unit\data\Void_Armor2_Shturm.paa"};
		linkedItems[] = {"SWLB_clone_basic_armor", "LS_P1_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"SWLB_clone_basic_armor", "LS_P1_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LS_void_commander_P1 : SWLB_clone_base_P1 {
		author = "LastWarTeam";
		displayName = "Void Commander clone trooper P1";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_commander_uniform";
		backpack = "LS_void_backpack_RTO";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Kivi.paa", "void_unit\data\Void_Armor2_Kivi.paa"};
		linkedItems[] = {"SWLB_clone_basic_armor", "LS_P1_helmet_void_commander", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"SWLB_clone_basic_armor", "LS_P1_helmet_void_commander", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LS_void_uport_ARF : SWLB_clone_base_P1 {
		author = "LastWarTeam";
		displayName = "Void Uport clone trooper";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_uport_uniform";
		backpack = "LS_uport_backpack_RTO";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Uport.paa", "void_unit\data\Void_Armor2_Uport.paa"};
		linkedItems[] = {"SWLB_clone_basic_armor", "LS_ARF_helmet_uport", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"SWLB_clone_basic_armor", "LS_ARF_helmet_uport", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LS_void_nightwish_ARF : SWLB_clone_base_P1 {
		author = "LastWarTeam";
		displayName = "Void Nightwish clone trooper";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_arf_nightwish_uniform";
		backpack = "LS_nightwish_backpack_RTO";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Nightwish.paa", "void_unit\data\Void_Armor2_ARF.paa"};
		linkedItems[] = {"SWLB_clone_basic_armor", "LS_ARF_helmet", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"SWLB_clone_basic_armor", "LS_ARF_helmet", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LS_void_clone_ARF : SWLB_clone_base_P1 {
		author = "LastWarTeam";
		displayName = "Void ARF clone trooper";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_arf_uniform";
		backpack = "LS_void_backpack_RTO";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_ARF.paa", "void_unit\data\Void_Armor2_ARF.paa"};
		linkedItems[] = {"SWLB_clone_basic_armor", "LS_ARF_helmet", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"SWLB_clone_basic_armor", "LS_ARF_helmet", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LS_void_arty_P2 : SWLB_clone_base_P2 {
		author = "LastWarTeam";
		displayName = "Void Dominus clone trooper P2";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_arty_uniform";
		backpack = "LS_void_backpack";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Arta.paa", "void_unit\data\Void_Armor2_Arta.paa"};
		linkedItems[] = {"SWLB_clone_basic_armor", "LS_P2_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"SWLB_clone_basic_armor", "LS_P2_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LS_void_recon_P2 : SWLB_clone_base_P2 {
		author = "LastWarTeam";
		displayName = "Void Nebula clone trooper P2";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_recon_uniform";
		backpack = "LS_void_backpack_RTO";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Rozved.paa", "void_unit\data\Void_Armor2_Rozved.paa"};
		linkedItems[] = {"SWLB_clone_basic_armor", "LS_P2_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"SWLB_clone_basic_armor", "LS_P2_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LS_void_assault_P2 : SWLB_clone_base_P2 {
		author = "LastWarTeam";
		displayName = "Void Attero clone trooper P2";
		faction = "LW_Faction";
		editorSubcategory = "LS_void_Legion";
		uniformClass = "LS_void_assault_uniform";
		backpack = "LS_void_backpack";
		hiddenSelectionsTextures[] = {"void_unit\data\Void_Armor1_Shturm.paa", "void_unit\data\Void_Armor2_Shturm.paa"};
		linkedItems[] = {"SWLB_clone_basic_armor", "LS_P2_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"SWLB_clone_basic_armor", "LS_P2_helmet_void", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
};

class cfgMods {
	author = "GLyba";
	timepacked = 1593980150;
};
