// config.bin - 23:39:42 07/23/20, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class RS_Legion {
		units[] = {"Pilot"};
		weapons[] = {"RS_Uniform_Pilot"};
	};
	author = "LastWarTeam";
	requiredAddons[] = {"SWLB_clones"};
};

class CfgFactionClasses {
	class LW_Faction {
		displayName = "LastWar";
	};
};

class CfgEditorSubcategories {
	class RS_Legion {
		displayName = "RS LW Legion";
	};
};

class CfgWeapons {
	class H_HelmetO_ViperSP_hex_F;	// External class reference
	class SWLB_clone_ccVisor;	// External class reference
	class SWLB_clone_mcVisor;	// External class reference
	class SWLB_clone_nvg;	// External class reference
	class SWLB_clone_nvg_nco;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_nvg_spec;	// External class reference
	class SWLB_clone_nvg_spec_nco;	// External class reference
	class SWLB_clone_commando_nvg_antenna;	// External class reference
	class SWLB_clone_commando_nvg;	// External class reference
	class SWLB_clone_P1_2_helmet;	// External class reference
	class SWLB_clone_ARF_P1_helmet;	// External class reference
	class SWLB_clone_ARF_P2_helmet;	// External class reference
	class SWLB_clone_P1_helmet;	// External class reference
	class SWLB_clone_eng_helmet;	// External class reference
	class SWLB_clone_BARC_helmet;	// External class reference
	class SWLB_clone_P2_helmet;	// External class reference
	class SWLB_clone_AB_helmet;	// External class reference
	class SWLB_clone_P15_helmet;	// External class reference
	class SDT_Hazard_Helmet;	// External class reference
	class SDT_stealth_helmet;	// External class reference
	class Scout_helmet;	// External class reference
	class SWLB_clone_pilot_P2_helmet;	// External class reference
	class SWLB_clone_commando_helmet_k1;	// External class reference
	class SWLB_clone_recon_armor;	// External class reference
	class SWLB_clone_recon_officer_armor;	// External class reference
	class SWLB_clone_recon_nco_armor;	// External class reference
	class SWLB_clone_officer_armor;	// External class reference
	class SWLB_clone_medic_armor;	// External class reference
	class SWLB_clone_kama_armor;	// External class reference
	class SWLB_clone_mc_uniform;	// External class reference
	class SWLB_clone_commander_armor;	// External class reference
	class SWLB_clone_cfr_armor;	// External class reference
	class SWLB_clone_airborne_armor;	// External class reference
	class SWLB_clone_airborne_nco_armor;	// External class reference
	class SWLB_clone_arc_armor;	// External class reference
	class SWLB_clone_commando_eod_armor_k1;	// External class reference
	class SWLB_clone_commando_sniper_armor_k1;	// External class reference
	class SWLB_clone_commando_sl_armor_k1;	// External class reference
	class SWLB_clone_commando_tech_armor_k1;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	class SWLB_clone_commando_uniform_k1;	// External class reference
	class SWLA_BL_Sergeant_Vest;	// External class reference
	class SWLB_mando_og_helmet;	// External class reference
	class SWLB_mando_og_armor;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_mando_uniform;	// External class reference
	class SWLB_CEE_Force_Recon_Officer;	// External class reference
	class SWLB_CEE_P1_Rangefinder;	// External class reference
	class UniformItem;	// External class reference
	class HeadgearItem;	// External class reference
	class SDT_pilot_p1_helmet;	// External class reference
	
	class RS_HelmetP2Pi_Broadside : SWLB_clone_pilot_P2_helmet {
		author = "LastWarTeam";
		displayName = "Clone Trooper P2 Pilot helmet (Broadside)";
		hiddenSelectionsTextures[] = {"RS_Unit\data\RS_HelmetP2Pi_Broadside.paa", "RS_Unit\data\RS_HelmetP2Pi_Broadside.paa"};
	};
	
	class RS_ARF_P2_helmet : SWLB_clone_ARF_P2_helmet {
		author = "LastWar Team";
		displayName = "Clone trooper P2 ARF helmet (Horn)";
		hiddenSelectionsTextures[] = {"RS_Unit\data\RS_HelmetARF_Horn.paa", "", "RS_Unit\data\RS_ARF_Flaps.paa"};
	};
	
	class RS_Uniform_Horn : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "RS Clone Trooper Uniform (Horn)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Horn";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class RS_Uniform_Pilot : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "RS Clone Trooper Uniform (Pilot)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Pilot";
			containerClass = "Supply150";
			mass = 40;
		};
	};
};

class CfgVehicles {
	class SWLB_clone_commando_base;	// External class reference
	class SWLB_clone_commando_backpack_k2;	// External class reference
	class SWLB_clone_commando_backpack_k2_rto;	// External class reference
	class SWLB_clone_commando_backpack_k2_eod;	// External class reference
	class SWLB_clone_base_P2;	// External class reference
	class SWLB_clone_base_P1;	// External class reference
	class SWLB_clone_assault_base_P2;	// External class reference
	class SWLB_clone_cfr_base_P2;	// External class reference
	class SWLB_clone_medic_base_P2;	// External class reference
	class SWLB_clone_RTO_base_P2;	// External class reference
	class SWLB_clone_recon_base_P2;	// External class reference
	class SWLB_clone_recon_nco_base_P2;	// External class reference
	class SWLB_clone_recon_officer_base_P2;	// External class reference
	class SWLB_clone_airborne_base_P2;	// External class reference
	class SWLB_clone_airborne_nco_base_P2;	// External class reference
	class SWLB_clone_lieutenant_base_P2;	// External class reference
	class SWLB_clone_captain_base_P2;	// External class reference
	class SWLB_clone_commander_base_P2;	// External class reference
	class SWLB_clone_marshal_commander_base_P2;	// External class reference
	class SWLB_clone_arc_base_P2;	// External class reference
	class SWLB_clone_pilot_base_P2;	// External class reference
	class SWLB_clone_sniper_base_P2;	// External class reference
	class SWLB_clone_sg_base_P2;	// External class reference
	class SWLB_clone_at_base_P2;	// External class reference
	class SWLB_clone_backpack;	// External class reference
	class SWLB_clone_backpack_eod;	// External class reference
	class SWLB_clone_backpack_heavy;	// External class reference
	class SWLB_mando_base_assault;	// External class reference
	class SWLB_clone_backpack_RTO;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_RTO_mini_backpack;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	
	class LS_clone_backpack_eod : SWLB_clone_backpack_eod {
		displayName = "Clone trooper EOD backpack";
		maximumload = 450;
		picture = "\SWLB_equipment\backpacks\data\ui\icon_SWLB_clone_backpack_heavy_ca.paa";
		hiddenSelectionsTextures[] = {"\SWLB_equipment\backpacks\data\SWLB_clone_backpack_eod_co.paa", "\SWLB_equipment\backpacks\data\SWLB_clone_backpack_co.paa", "\SWLB_equipment\backpacks\data\SWLB_clone_backpack_co.paa", ""};
	};
	
	class Horn : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper (Horn)";
		faction = "LW_Faction";
		editorSubcategory = "RS_Legion";
		uniformclass = "Horn";
		hiddenSelectionsTextures[] = {"RS_Unit\data\RS_Armor1_Horn.paa", "RS_Unit\data\RS_Armor2_Horn.paa"};
		linkedItems[] = {"ARC_HelmetP1_Fur", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARC_HelmetP1_Fur", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Pilot : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARC Clone Trooper (Pilot)";
		faction = "LW_Faction";
		editorSubcategory = "RS_Legion";
		uniformclass = "Pilot";
		hiddenSelectionsTextures[] = {"RS_Unit\data\RS_Armor1_Pilot.paa", "SWLB_clones\data\camo2_co.paa"};
		linkedItems[] = {"ARC_HelmetP1_Fur", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARC_HelmetP1_Fur", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
};

class cfgMods {
	author = "Last Force Project";
	timepacked = 1594648247;
};
