// config.bin - 23:39:59 07/23/20, generated in 0.04 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class LS_clones_mg_Z6 {
		author = "SW Legion Studios";
		requiredAddons[] = {"A3_Data_F", "A3_Weapons_F", "SWLW_main", "SWLW_clones", "SWLW_clones_mg"};
		requiredVersion = 0.1;
		units[] = {};
		weapons[] = {SWLW_Z6};
	};
};

class CfgAmmo {
	class SWLW_ammo_assault_blue;	// External class reference
	
	class LS_ammo_assault_blue : SWLW_ammo_assault_blue {
		hit = 20;
	};
};

class CfgMagazines {
	class SWLW_mag_base;	// External class reference
	
	class LS_Z6_mag : SWLW_mag_base {
		scope = 2;
		displayname = "Z-6 energy cell (500rnd)";
		initspeed = 800;
		picture = "\SWLW_clones\machineguns\Z6\data\ui\Z6_mag_ui.paa";
		ammo = "LS_ammo_assault_blue";
		count = 500;
		model = "SWLW_clones\machineguns\Z6\Z6_mag.p3d";
	};
};
class Mode_FullAuto;	// External class reference
class Mode_SemiAuto;	// External class reference
class Mode_Burst;	// External class reference
class SlotInfo;	// External class reference
class MuzzleSlot;	// External class reference
class CowsSlot;	// External class reference
class PointerSlot;	// External class reference
class UnderBarrelSlot;	// External class reference
class UGL_F;	// External class reference

class CfgRecoils {
	class recoil_default;	// External class reference
	
	class SWLW_Z6_recoil : recoil_default {
		kickBack[] = {0.045, 0.08};
		muzzleOuter[] = {0.3, 1, 0.3, 0.2};
		permanent = 0.03;
		temporary = 0.02;
	};
};

class CfgWeapons {
	class Rifle;	// External class reference
	
	class Rifle_Base_F : Rifle {
		class WeaponSlotsInfo;	// External class reference
		class GunParticles;	// External class reference
		scope = 1;
	};
	
	class LS_Z6_base : Rifle_Base_F {
		ace_overheating_mrbs = 100000;
		ace_overheating_slowdownFactor = 1e-006;
		ace_overheating_allowSwapBarrel = 1;
		ace_overheating_dispersion = 0;
		scope = 1;
		author = "SW Legion Studios";
		displayName = "Z6 Rotary Blaster";
		model = "SWLW_clones\machineguns\z6\Z6.p3d";
		picture = "\SWLW_clones\machineguns\z6\data\ui\Z6_ui.paa";
		magazines[] = {"LS_Z6_mag"};
		muzzles[] = {this};
		reloadAction = "ReloadMagazine";
		magazineReloadSwitchPhase = 0.4;
		discreteDistanceInitIndex = 0;
		maxRecoilSway = 0.01;
		swayDecaySpeed = 0.2;
		inertia = 3;
		initSpeed = 800;
		fireLightDuration = 0.05;
		fireLightIntensity = 0.4;
		fireLightDiffuse[] = {0, 0, 0.01};
		fireLightAmbient[] = {0, 0, 0};
		
		class GunParticles : GunParticles {
			class SecondEffect {
				positionName = "Nabojnicestart";
				directionName = "Nabojniceend";
				effectName = "CaselessAmmoCloud";
			};
		};
		opticsZoomMin = 0.25;
		opticsZoomMax = 1.25;
		opticsZoomInit = 0.75;
		distanceZoomMin = 300;
		distanceZoomMax = 300;
		descriptionShort = "";
		handAnim[] = {"OFP2_ManSkeleton", "\SWLW_clones\machineguns\z6\anims\Z6_handanim.rtm"};
		dexterity = 1;
		caseless[] = {"", 1, 1, 1};
		soundBullet[] = {"caseless", 1};
		flash = "gunfire";
		flashSize = 3;
		modes[] = {"FullAuto", "close", "short", "medium", "manual", "far_optic1", "far_optic2"};
		
		class Single : Mode_SemiAuto {
			sounds[] = {"StandardSound"};
			class BaseSoundModeType;	// External class reference
			
			class StandardSound : BaseSoundModeType {
				begin1[] = {"SWLW_clones\machineguns\z6\sounds\Z6_1.wss", 1, 1, 500};
				soundBegin[] = {"begin1", 1};
			};
			reloadTime = 1;
			dispersion = 0.001;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 15;
			midRangeProbab = 0.7;
			maxRange = 30;
			maxRangeProbab = 0.1;
		};
		
		class FullAuto : Mode_FullAuto {
			sounds[] = {"StandardSound"};
			class BaseSoundModeType;	// External class reference
			
			class StandardSound : BaseSoundModeType {
				begin1[] = {"SWLW_clones\machineguns\z6\sounds\Z6_1.wss", 1, 1, 500};
				soundBegin[] = {"begin1", 1};
			};
			reloadTime = 0.05;
			dispersion = 0.008;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 15;
			midRangeProbab = 0.7;
			maxRange = 30;
			maxRangeProbab = 0.1;
		};
		
		class close : FullAuto {
			showToPlayer = 0;
			aiRateOfFire = 0.25;
			aiRateOfFireDistance = 400;
			minRange = 0;
			minRangeProbab = 0.05;
			midRange = 200;
			midRangeProbab = 0.7;
			maxRange = 400;
			maxRangeProbab = 0.2;
		};
		
		class short : close {
			aiRateOfFire = 0.5;
			aiRateOfFireDistance = 500;
			minRange = 300;
			minRangeProbab = 0.2;
			midRange = 400;
			midRangeProbab = 0.7;
			maxRange = 500;
			maxRangeProbab = 0.2;
		};
		
		class medium : close {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 900;
			minRange = 400;
			minRangeProbab = 0.2;
			midRange = 700;
			midRangeProbab = 0.7;
			maxRange = 900;
			maxRangeProbab = 0.2;
		};
		
		class manual : FullAuto {
			dispersion = 0.00073;
			recoilProne = "recoil_single_prone_mx_sw";
			minRange = 0;
			minRangeProbab = 0.3;
			midRange = 5;
			midRangeProbab = 0.7;
			maxRange = 10;
			maxRangeProbab = 0.04;
			showToPlayer = 1;
		};
		
		class far_optic1 : close {
			burst = 3;
			requiredOpticType = 1;
			aiRateOfFire = 5;
			aiRateOfFireDistance = 650;
			minRange = 300;
			minRangeProbab = 0.05;
			midRange = 500;
			midRangeProbab = 0.4;
			maxRange = 650;
			maxRangeProbab = 0.01;
		};
		
		class far_optic2 : far_optic1 {
			burst = 3;
			requiredOpticType = 2;
			minRange = 400;
			minRangeProbab = 0.05;
			midRange = 750;
			midRangeProbab = 0.7;
			maxRange = 900;
			maxRangeProbab = 0.01;
			aiRateOfFire = 10;
			aiRateOfFireDistance = 900;
		};
		recoil = "SWLW_Z6_recoil";
		aiDispersionCoefY = 6;
		aiDispersionCoefX = 4;
		drySound[] = {"SWLW_clones\machineguns\z6\sounds\Z6_empty.wss", 2, 1, 20};
		reloadMagazineSound[] = {"SWLW_main\Carbines\DC15S\sounds\DC15s_reload.wss", 1, 1, 30};
		reloadSound[] = {"", 1, 1};
		
		class WeaponSlotsInfo : WeaponSlotsInfo {
			mass = 176;
			
			class MuzzleSlot : MuzzleSlot {
				compatibleItems[] = {};
			};
			
			class CowsSlot : CowsSlot {
				compatibleItems[] = {};
			};
			
			class PointerSlot : PointerSlot {
				compatibleItems[] = {};
			};
		};
	};
	
	class LS_Z6 : LS_Z6_base {
		scope = 2;
		scopearsneal = 2;
		initspeed = 800;
		muzzles[] = {this, "Explosive"};
		
		class Explosive : LS_Z6_base {
			author = "SW Legion Studios";
			displayName = "HE mode";
			initspeed = 300;
			magazines[] = {"SWLW_mag_40mm_10rnd"};
			modes[] = {"Single"};
		};
	};
};

class CfgVehicles {
	class Weapon_Base_F;	// External class reference
	
	class SWLW_GH_Z6 : Weapon_Base_F {
		author = "SW Legion Studios";
		displayName = "Z6 Rotary Blaster";
		scope = 2;
		
		class TransportWeapons {
			class LS_Z6 {
				count = 1;
				weapon = LS_Z6;
			};
		};
		
		class TransportMagazines {
			class LS_Z6_mag {
				count = 1;
				magazine = "LS_Z6_mag";
			};
			
			class SWLW_Z6_g_mag {
				count = 1;
				magazine = "SWLW_Z6_g_mag";
			};
		};
	};
};

class cfgMods {
	author = "Last Force Project";
	timepacked = 1594648269;
};
