// config.bin - 23:38:35 07/23/20, generated in 0.03 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class ARF_Legion {
		units[] = {"Reason", "Yamato", "Rabbit", "Anvil", "Rage", "Ytamato", "Xray", "Rick", "Osiris", "Acklay", "Vex", "Foxxy", "Phaeron", "Acklay_1"};
		weapons[] = {"ARF_helmet_Reason", "ARF_Uniform_Reason", "ARF_Camo_Reason", "ARF_Uniform_Yamato", "ARF_Camo_Yamato", "ARF_HelmetP1_Yamato", "ARF_HelmetP1_Rabbit", "ARF_Uniform_Rabbit", "ARF_Uniform_Rage", "ARF_HelmetP1_Rage", "ARF_Helmet_Ytamato", "ARF_Uniform_Ytamato", "ARF_Helmet_Xray", "ARF_Uniform_Xray", "ARF_Helmet_Rick", "ARF_Uniform_Rick", "ARF_Helmet_Osiris", "ARF_Uniform_Osiris", "ARF_Helmet_Phaeron", "ARF_Uniform_Phaeron", "ARF_Helmet_Foxxy", "ARF_Uniform_Foxxy", "ARF_Helmet_Acklay_1", "ARF_Uniform_Acklay_1", "ARF_Helmet_Acklay", "ARF_Uniform_Acklay", "ARF_Helmet_Vex", "ARF_Uniform_Vex"};
	};
	author = "LastWarTeam";
	requiredAddons[] = {"SWLB_clones"};
};

class CfgFactionClasses {
	class LW_Faction {
		displayName = "LastWar";
	};
};

class CfgEditorSubcategories {
	class ARF_Legion {
		displayName = "ARF LW Legion";
	};
};

class CfgWeapons {
	class H_HelmetO_ViperSP_hex_F;	// External class reference
	class SWLB_clone_ccVisor;	// External class reference
	class SWLB_clone_mcVisor;	// External class reference
	class SWLB_clone_nvg;	// External class reference
	class SWLB_clone_nvg_nco;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_nvg_spec;	// External class reference
	class SWLB_clone_nvg_spec_nco;	// External class reference
	class SWLB_clone_commando_nvg_antenna;	// External class reference
	class SWLB_clone_commando_nvg;	// External class reference
	class SWLB_clone_P1_2_helmet;	// External class reference
	class SWLB_clone_ARF_P1_helmet;	// External class reference
	class SWLB_clone_P1_helmet;	// External class reference
	class SWLB_clone_eng_helmet;	// External class reference
	class SWLB_clone_BARC_helmet;	// External class reference
	class SWLB_clone_P2_helmet;	// External class reference
	class SWLB_clone_AB_helmet;	// External class reference
	class SWLB_clone_P15_helmet;	// External class reference
	class SDT_Hazard_Helmet;	// External class reference
	class SDT_stealth_helmet;	// External class reference
	class Scout_helmet;	// External class reference
	class SWLB_clone_pilot_P2_helmet;	// External class reference
	class SWLB_clone_commando_helmet_k1;	// External class reference
	class SWLB_clone_recon_armor;	// External class reference
	class SWLB_clone_recon_officer_armor;	// External class reference
	class SWLB_clone_recon_nco_armor;	// External class reference
	class SWLB_clone_officer_armor;	// External class reference
	class SWLB_clone_medic_armor;	// External class reference
	class SWLB_clone_kama_armor;	// External class reference
	class SWLB_clone_mc_uniform;	// External class reference
	class SWLB_clone_commander_armor;	// External class reference
	class SWLB_clone_cfr_armor;	// External class reference
	class SWLB_clone_airborne_armor;	// External class reference
	class SWLB_clone_airborne_nco_armor;	// External class reference
	class SWLB_clone_arc_armor;	// External class reference
	class SWLB_clone_commando_eod_armor_k1;	// External class reference
	class SWLB_clone_commando_sniper_armor_k1;	// External class reference
	class SWLB_clone_commando_sl_armor_k1;	// External class reference
	class SWLB_clone_commando_tech_armor_k1;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	class SWLB_clone_commando_uniform_k1;	// External class reference
	class SWLA_BL_Sergeant_Vest;	// External class reference
	class SWLB_mando_og_helmet;	// External class reference
	class SWLB_mando_og_armor;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_mando_uniform;	// External class reference
	class SWLB_CEE_Force_Recon_Officer;	// External class reference
	class UniformItem;	// External class reference
	class HeadgearItem;	// External class reference
	class SDT_pilot_p1_helmet;	// External class reference
	
	class ARF_helmet_Reason : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Reason)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Helmet_Reason.paa"};
	};
	
	class ARF_helmet_Trauma : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Trauma)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_helmet_Trauma.paa"};
	};
	
	class ARF_Helmet_Horn : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Horn)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Helmet_Horn.paa"};
	};
	
	class ARF_HelmetP1_Yamato : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Yamato)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Helmet_Yamato.paa"};
	};
	
	class ARF_HelmetP1_Rabbit : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Rabbit)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_HelmetP1_Rabbit.paa"};
	};
	
	class ARF_Helmet_Anvil : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Anvil)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Helmet_Anvil.paa"};
	};
	
	class ARF_HelmetP1_Rage : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Rage)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_HelmetP1_Rage.paa"};
	};
	
	class ARF_Helmet_Xray : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Xray)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Helmet_Xray.paa"};
	};
	
	class ARF_Helmet_Rick : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Rick)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Helmet_Rick.paa"};
	};
	
	class ARF_Helmet_Osiris : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Osiris)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Helmet_Osiris.paa"};
	};
	
	class ARF_Helmet_Acklay_1 : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Acklay_1)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Helmet_1.paa"};
	};
	
	class ARF_Helmet_Phaeron : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Phaeron)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Helmet_Phaeron.paa"};
	};
	
	class ARF_Helmet_Foxxy : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Foxxy)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Helmet_Foxxy.paa"};
	};
	
	class ARF_Helmet_Vex : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Vex)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Helmet_Vex.paa"};
	};
	
	class ARF_Helmet_Acklay : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Helmet (Acklay)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Helmet_Acklay.paa"};
	};
	
	class ARF_Uniform_Reason : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Reason)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Reason";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Trauma : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Trauma)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Trauma";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Horn : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Horn)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Horn";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Yamato : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Yamato)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Yamato";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Rabbit : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Rabbit)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Rabbit";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Anvil : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Anvil)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Anvil";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Rage : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Rage)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Rage";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Xray : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Xray)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Xray";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Rick : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Rick)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Rick";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Osiris : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Osiris)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Osiris";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Acklay_1 : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Acklay_1)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Acklay_1";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Phaeron : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Phaeron)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Phaeron";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Foxxy : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Foxxy)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Foxxy";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Vex : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Vex)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Vex";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Uniform_Acklay : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper Uniform (Acklay)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Acklay";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class ARF_Camo_Reason : SWLB_CEE_Force_Recon_Officer {
		author = "LastWar Team";
		displayName = "ARF Camo (Reason)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Accessories_Reason.paa", "ARF_Unit\data\ARF_Cama_Reason.paa"};
	};
	
	class ARF_Camo_Trauma : SWLB_CEE_Force_Recon_Officer {
		author = "LastWar Team";
		displayName = "ARF Camo (Trauma)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Acces.paa", "ARF_Unit\data\ARF_officer_Trauma.paa"};
	};
	
	class ARF_Camo_Yamato : SWLB_CEE_Force_Recon_Officer {
		author = "LastWar Team";
		displayName = "ARF Camo (Yamato)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Accessories_1.paa", "ARF_Unit\data\ARF_Camo_Yamato.paa"};
	};
	
	class ARF_Camo_Rabbit : SWLB_CEE_Force_Recon_Officer {
		author = "LastWar Team";
		displayName = "ARF Camo (Rabbit)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Accessories_1.paa", "ARF_Unit\data\ARF_Camo_Rabbit.paa"};
	};
	
	class ARF_Camo_Acklay_1 : SWLB_CEE_Force_Recon_Officer {
		author = "LastWar Team";
		displayName = "ARF Camo (Acklay_1)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Accessories_1.paa", "ARF_Unit\data\ARF_Camo_1.paa"};
	};
	
	class ARF_Camo_Foxxy : SWLB_CEE_Force_Recon_Officer {
		author = "LastWar Team";
		displayName = "ARF Camo (Foxxy)";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Accessories_Foxxy.paa", "ARF_Unit\data\ARF_Camo_Foxxy.paa"};
	};
};

class CfgVehicles {
	class SWLB_clone_commando_base;	// External class reference
	class SWLB_clone_commando_backpack_k2;	// External class reference
	class SWLB_clone_commando_backpack_k2_rto;	// External class reference
	class SWLB_clone_commando_backpack_k2_eod;	// External class reference
	class SWLB_clone_base_P2;	// External class reference
	class SWLB_clone_base_P1;	// External class reference
	class SWLB_clone_assault_base_P2;	// External class reference
	class SWLB_clone_cfr_base_P2;	// External class reference
	class SWLB_clone_medic_base_P2;	// External class reference
	class SWLB_clone_RTO_base_P2;	// External class reference
	class SWLB_clone_recon_base_P2;	// External class reference
	class SWLB_clone_recon_nco_base_P2;	// External class reference
	class SWLB_clone_recon_officer_base_P2;	// External class reference
	class SWLB_clone_airborne_base_P2;	// External class reference
	class SWLB_clone_airborne_nco_base_P2;	// External class reference
	class SWLB_clone_lieutenant_base_P2;	// External class reference
	class SWLB_clone_captain_base_P2;	// External class reference
	class SWLB_clone_commander_base_P2;	// External class reference
	class SWLB_clone_marshal_commander_base_P2;	// External class reference
	class SWLB_clone_arc_base_P2;	// External class reference
	class SWLB_clone_pilot_base_P2;	// External class reference
	class SWLB_clone_sniper_base_P2;	// External class reference
	class SWLB_clone_sg_base_P2;	// External class reference
	class SWLB_clone_at_base_P2;	// External class reference
	class SWLB_clone_backpack;	// External class reference
	class SWLB_clone_backpack_eod;	// External class reference
	class SWLB_clone_backpack_heavy;	// External class reference
	class SWLB_mando_base_assault;	// External class reference
	class SWLB_clone_backpack_RTO;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_RTO_mini_backpack;	// External class reference
	class SWLB_CEE_Recon_RTO_Backpack;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	
	class ARF_MRTO_Acklay_1 : SWLB_clone_RTO_mini_backpack {
		author = "LastWar Team";
		displayName = "Clone recon RTO backpack (Acklay)";
		maximumload = 200;
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_MiniRTO_1.paa", "ARF_Unit\data\ARF_MRTOAccum_1.paa"};
	};
	
	class Reason : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Reason)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "ARF_Uniform_Reason";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_Reason.paa", "ARF_Unit\data\ARF_Armor2_Reason.paa"};
		linkedItems[] = {"ARF_helmet_Reason", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_helmet_Reason", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Trauma : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Trauma)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "Trauma";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_armor1_Trauma.paa", "ARF_Unit\data\ARF_armor2_Trauma.paa"};
		linkedItems[] = {"ARF_helmet_Trauma", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_helmet_Trauma", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Horn : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Horn)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "Horn";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_Horn.paa", "ARF_Unit\data\ARF_Armor2_Horn.paa"};
		linkedItems[] = {"ARF_Helmet_Horn", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_Helmet_Horn", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Yamato : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Yamato)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "Yamato";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_Yamato.paa", "ARF_Unit\data\ARF_armor2_Yamato.paa"};
		linkedItems[] = {"ARF_HelmetP1_Yamato", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_HelmetP1_Yamato", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Rabbit : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Rabbit)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "Rabbit";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_Rabbit.paa", "ARF_Unit\data\ARF_Armor2_Rabbit.paa"};
		linkedItems[] = {"ARF_HelmetP1_Rabbit", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_HelmetP1_Rabbit", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Anvil : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Anvil)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "Anvil";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_Anvil.paa", "ARF_Unit\data\ARF_Armor2_Anvil.paa"};
		linkedItems[] = {"ARF_Helmet_Anvil", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_Helmet_Anvil", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Rage : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Rage)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "Rage";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_Rage.paa", "ARF_Unit\data\ARF_Armor2_Rage.paa"};
		linkedItems[] = {"ARF_HelmetP1_Rage", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_HelmetP1_Rage", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Xray : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Xray)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "Xray";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_Xray.paa", "ARF_Unit\data\ARF_Armor2_Xray.paa"};
		linkedItems[] = {"ARF_Helmet_Xray", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_Helmet_Xray", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Rick : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Osiris)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "Osiris";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_Rick.paa", "ARF_Unit\data\ARF_Armor2_Rick.paa"};
		linkedItems[] = {"ARF_Helmet_Rick", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_Helmet_Rick", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Osiris : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Osiris)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "Osiris";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_Osiris.paa", "ARF_Unit\data\ARF_Armor2_Osiris.paa"};
		linkedItems[] = {"ARF_Helmet_Osiris", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_Helmet_Osiris", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Acklay_1 : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Acklay_1)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "1";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_1.paa", "ARF_Unit\data\ARF_Armor2_1.paa"};
		linkedItems[] = {"ARF_Helmet_1", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_Helmet_1", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Phaeron : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Phaeron)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "Phaeron";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_Phaeron.paa", "ARF_Unit\data\ARF_Armor2_Phaeron.paa"};
		linkedItems[] = {"ARF_Helmet_Phaeron", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_Helmet_Phaeron", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Foxxy : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Foxxy)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "Foxxy";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_Foxxy.paa", "ARF_Unit\data\ARF_Armor2_Foxxy.paa"};
		linkedItems[] = {"ARF_Helmet_Foxxy", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_Helmet_Foxxy", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Vex : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Vex)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "Vex";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_Vex.paa", "ARF_Unit\data\ARF_Armor2_Vex.paa"};
		linkedItems[] = {"ARF_Helmet_Vex", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_Helmet_Vex", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Acklay : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "ARF Clone Trooper (Acklay)";
		faction = "LW_Faction";
		editorSubcategory = "ARF_Legion";
		uniformclass = "Acklay";
		hiddenSelectionsTextures[] = {"ARF_Unit\data\ARF_Armor1_Acklay.paa", "ARF_Unit\data\ARF_Armor2_Acklay.paa"};
		linkedItems[] = {"ARF_Helmet_Acklay", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"ARF_Helmet_Acklay", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
};

class cfgMods {
	author = "GLyba";
	timepacked = 1593919332;
};
