// config.bin - 23:39:11 07/23/20, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class SWCMS {
		units[] = {"Olga_home"};
		weapons[] = {};
		requiredVersion = 0.3;
		requiredAddons[] = {"A3_Functions_F"};
	};
};

class CfgMusicClasses {
	class SWCMS {
		displayName = "Star Wars";
	};
};

class CfgSFX {
	class Olga_home {
		name = "Olga_Home";
		sounds[] = {"sfxsound"};
		sfxsound[] = {"LF_Faces\data\Olga_home.ogg", 75, 1, 75, 1, 1, 1, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
};

class CfgVehicles {
	class All;	// External class reference
	
	class Sound : All {
		author = "Cruisie";
		mapSize = 10;
		_generalMacro = "Sound";
		scope = 0;
		side = -1;
		animated = 0;
		vehicleClass = "Sounds";
		icon = "iconSound";
		faction = "none";
		editorCategory = "EdCat_Sounds";
		editorSubcategory = "EdSubcat_Sounds";
	};
	
	class OlgaMusic : Sound {
		author = "LucasArts & Jesse Harlin";
		_generalMacro = "OlgaMusic";
		scope = 2;
		sound = "Olga_home";
		displayName = "Olga Home";
	};
};

class CfgFaces {
	class Default {
		class Custom;	// External class reference
	};
	
	class Man_A3 : Default {
		class Default;	// External class reference
		class WhiteHead_01;	// External class reference
		class AsianHead_A3_01;	// External class reference
		
		class Mergen_face : WhiteHead_01 {
			displayname = "Mergen";
			texture = "LF_Faces\data\Mergen_face.paa";
			identityTypes[] = {"Head_Euro", "Head_NATO"};
			author = "LastForce Team";
			disabled = 0;
			materialWounded1 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			materialWounded2 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			textureHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
		};
		
		class Dural_face : WhiteHead_01 {
			displayname = "Dural";
			texture = "LF_Faces\data\Dural_face.paa";
			identityTypes[] = {"Head_Euro", "Head_NATO"};
			author = "LastForce Team";
			disabled = 0;
			materialWounded1 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			materialWounded2 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			textureHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
		};
		
		class Torand_face : WhiteHead_01 {
			displayname = "Torand";
			texture = "LF_Faces\data\Torand_head.paa";
			identityTypes[] = {"Head_Euro", "Head_NATO"};
			author = "LastForce Team";
			disabled = 0;
			materialWounded1 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			materialWounded2 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			textureHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
		};
		
		class Morog_face : WhiteHead_01 {
			displayname = "Morog";
			texture = "LF_Faces\data\Morog_Face.paa";
			identityTypes[] = {"Head_Euro", "Head_NATO"};
			author = "LastForce Team";
			disabled = 0;
			materialWounded1 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			materialWounded2 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			textureHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
		};
		
		class Mac_face : WhiteHead_01 {
			displayname = "Mac";
			texture = "LF_Faces\data\Mac_face.paa";
			identityTypes[] = {"Head_Euro", "Head_NATO"};
			author = "LastForce Team";
			disabled = 0;
			materialWounded1 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			materialWounded2 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			textureHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
		};
		
		class Dem_face : WhiteHead_01 {
			displayname = "Dem";
			texture = "LF_Faces\data\Dem_face.paa";
			identityTypes[] = {"Head_Euro", "Head_NATO"};
			author = "LastForce Team";
			disabled = 0;
			materialWounded1 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			materialWounded2 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			textureHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
		};
		
		class Jerome_face_v1 : WhiteHead_01 {
			displayname = "Jerome (V1)";
			texture = "LF_Faces\data\Jerome_face.paa";
			author = "LastForce Team";
			material = "\A3\Characters_F_EPB\Heads\Data\m_white_16.rvmat";
			materialWounded1 = "\A3\Characters_F_EPB\Heads\Data\m_white_16_injury.rvmat";
			materialWounded2 = "\A3\Characters_F_EPB\Heads\Data\m_white_16_injury.rvmat";
			textureHL = "\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialHL = "\A3\Characters_F\Heads\Data\hl_White_bald_muscular.rvmat";
			textureHL2 = "\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialHL2 = "\A3\Characters_F\Heads\Data\hl_White_bald_muscular.rvmat";
		};
		
		class Jerome_face_v2 : WhiteHead_01 {
			displayname = "Jerome (V2)";
			texture = "LF_Faces\data\Jerome_face_v2.paa";
			author = "LastForce Team";
			material = "\A3\Characters_F_EPB\Heads\Data\m_white_16.rvmat";
			materialWounded1 = "\A3\Characters_F_EPB\Heads\Data\m_white_16_injury.rvmat";
			materialWounded2 = "\A3\Characters_F_EPB\Heads\Data\m_white_16_injury.rvmat";
			textureHL = "\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialHL = "\A3\Characters_F\Heads\Data\hl_White_bald_muscular.rvmat";
			textureHL2 = "\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialHL2 = "\A3\Characters_F\Heads\Data\hl_White_bald_muscular.rvmat";
		};
		
		class CorsaSquad : WhiteHead_01 {
			displayname = "CorsaSquad";
			texture = "LF_Faces\data\CorsaSquad_face.paa";
			identityTypes[] = {"Head_Euro", "Head_NATO"};
			author = "LastForce Team";
			disabled = 0;
			materialWounded1 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			materialWounded2 = "A3\Characters_F_epb\Heads\Data\m_White_20_injury.rvmat";
			textureHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
		};
		
		class GuanaHead1 : AsianHead_A3_01 {
			author = "LastForce Team";
			displayname = "Guana";
			texture = "LF_Faces\data\Guana_face.paa";
			material = "\A3\Characters_F\Heads\Data\m_Asian_02.rvmat";
			materialWounded1 = "A3\Characters_F\Heads\Data\m_Asian_02_injury.rvmat";
			materialWounded2 = "A3\Characters_F\Heads\Data\m_Asian_02_injury.rvmat";
		};
	};
};

class cfgMods {
	author = "LastForceTeam";
	timepacked = 1569084761;
};
