// config.bin - 23:39:22 07/23/20, generated in 0.06 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class RepCom {
		units[] = {"Clever", "Forest", "Sand", "Naak", "Aden", "Goran", "Elyrea", "66", "13", "47"};
		weapons[] = {"RC_Solus_Uniform_Forest", "RC_Solus_Helmet_Forest", "RC_Solus_Uniform_Sand", "RC_Solus_Helmet_Sand", "RC_Alpha1_Uniform", "RC_Alpha2_Uniform", "RC_Alpha_Helmet_1", "RC_Alpha_Helmet_2", "RC_Yivra_nvg_Naak""RC_Yivra_Helmet_Naak", "RC_Yivra_s1_armor_Naak", "RC_Yivra_Uniform_Naak", "RC_Yivra_nvg_Aden""RC_Yivra_Helmet_Aden", "RC_Yivra_s1_armor_Aden", "RC_Yivra_Uniform_Aden", "RC_Yivra_nvg_Goran""RC_Yivra_Helmet_Goran", "RC_Yivra_s1_armor_Goran", "RC_Yivra_Uniform_Goran", "RC_Yivra_Helmet_Elyrea", "RC_Yivra_s1_armor_Elyrea", "RC_Yivra_Uniform_Elyrea", "RC_Helmet_13", "RC_Helmet_66", "RC_Uniform_66", "RC_RTO_Backpack_66", "RC_Helmet_13", "RC_Uniform_13", "RC_RTO_Backpack_13", "RC_Solus_Helmet_47", "RC_Solus_Uniform_47", "RC_Solus_EOD_Backpack_47", "RC_Solus_nvg_47", "RC_Solus_eod_armor_V2"};
	};
	author = "LastWarTeam";
	requiredAddons[] = {SWLB_CEE, "SWLB_clones"};
};

class CfgFactionClasses {
	class LW_Faction {
		displayName = "LastWar";
	};
};

class CfgEditorSubcategories {
	class RepCom {
		displayName = "Republic Commando LW";
	};
};

class CfgWeapons {
	class SWLB_clone_commando_uniform_k1;	// External class reference
	class SWLB_clone_commando_helmet_k1;	// External class reference
	class SWLB_clone_commando_basic_armor_k1;	// External class reference
	class SWLB_clone_commando_sniper_armor_k1;	// External class reference
	class SWLB_clone_commando_tech_armor_k1;	// External class reference
	class SWLB_clone_commando_eod_armor_k1;	// External class reference
	class SWLB_clone_commando_sl_armor_k1;	// External class reference
	class NVGoggles;	// External class reference
	class SWLB_clone_commando_nvg;	// External class reference
	class SWLB_clone_commando_nvg_antenna;	// External class reference
	class VestItem;	// External class reference
	class UniformItem;	// External class reference
	class HeadgearItem;	// External class reference
	class RC_eod_armor_V2;	// External class reference
	class RC_sl_armor_V2;	// External class reference
	class RC_sniper_armor_V2;	// External class reference
	class RC_Helmet;	// External class reference
	
	class RC_Solus_nvg_47 : SWLB_clone_commando_nvg {
		displayName = "Clone II commando NV visor (47)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_47.paa", "RepCom\data\RC_Solus_Helmet_47.paa"};
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_Solus_nvg_Clever : SWLB_clone_commando_nvg {
		displayName = "Clone II commando NV visor (Clever)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_Clever.paa", "RepCom\data\RC_Solus_Helmet_Clever.paa"};
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_Solus_Antena_Clever : SWLB_clone_commando_nvg_antenna {
		displayName = "RC Solus Visor (Clever)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_Clever.paa", "RepCom\data\RC_Solus_Helmet_Clever.paa"};
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_Solus_Antena_Omen : SWLB_clone_commando_nvg_antenna {
		displayName = "RC Solus Visor (Omen)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_Omen.paa", "RepCom\data\RC_Solus_Helmet_Omen.paa"};
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_Solus_Helmet_Omen : RC_Helmet {
		author = "LastWar Team";
		displayName = "RC Katarn Helmet mk2 (Omen)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_Omen.paa", "RepCom\data\RC_Solus_Helmet_Omen.paa"};
	};
	
	class RC_Solus_Helmet_Clever : RC_Helmet {
		author = "LastWar Team";
		displayName = "RC Katarn Helmet mk2 (Clever)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_Clever.paa", "RepCom\data\RC_Solus_Helmet_Clever.paa"};
	};
	
	class RC_Solus_Helmet_66 : RC_Helmet {
		author = "LastWar Team";
		displayName = "RC Katarn Helmet mk2 (66)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_66.paa", "RepCom\data\RC_Solus_Helmet_66.paa"};
	};
	
	class RC_Solus_Helmet_47 : RC_Helmet {
		author = "LastWar Team";
		displayName = "RC Katarn Helmet mk2 (47)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_47.paa", "RepCom\data\RC_Solus_Helmet_47.paa"};
	};
	
	class RC_Helmet_13 : RC_Helmet {
		author = "LastWar Team";
		displayName = "RC Katarn Helmet mk2 (13)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Helmet_13.paa", "RepCom\data\RC_Helmet_13.paa"};
	};
	
	class RC_Solus_nvg_Sand : SWLB_clone_commando_nvg {
		displayName = "RC Solus Visor (Sand)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_Sand.paa", "RepCom\data\RC_Solus_Helmet_Sand.paa"};
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_Solus_Antena_Sand : SWLB_clone_commando_nvg_antenna {
		displayName = "RC Solus Visor (Sand)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_Sand.paa", "RepCom\data\RC_Solus_Helmet_Sand.paa"};
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_Solus_nvg_Forest : SWLB_clone_commando_nvg {
		displayName = "RC Solus Visor (Forest)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_Forest.paa", "RepCom\data\RC_Solus_Helmet_Forest.paa"};
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_Solus_Antena_Forest : SWLB_clone_commando_nvg_antenna {
		displayName = "RC Solus Visor (Forest)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_Forest.paa", "RepCom\data\RC_Solus_Helmet_Forest.paa"};
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_Solus_Helmet_Sand : RC_Helmet {
		author = "LastWar Team";
		displayName = "RC Solus Katarn Helmet (Sand)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_Sand.paa", "RepCom\data\RC_Solus_Helmet_Sand.paa"};
	};
	
	class RC_Solus_Helmet_Forest : RC_Helmet {
		author = "LastWar Team";
		displayName = "RC Solus Katarn Helmet (Forest)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Helmet_Forest.paa", "RepCom\data\RC_Solus_Helmet_Forest.paa"};
	};
	
	class RC_Solus_Uniform_Omen : SWLB_clone_commando_uniform_k1 {
		author = "LastWar Team";
		displayName = "RC Solus Katarn uniform (Omen)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Omen";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class RC_Solus_Uniform_Clever : SWLB_clone_commando_uniform_k1 {
		author = "LastWar Team";
		displayName = "RC Solus Katarn uniform (Clever)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Clever";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class RC_Solus_Uniform_Sand : SWLB_clone_commando_uniform_k1 {
		author = "LastWar Team";
		displayName = "RC Solus Katarn uniform (Sand)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Sand";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class RC_Solus_Uniform_Forest : SWLB_clone_commando_uniform_k1 {
		author = "LastWar Team";
		displayName = "RC Solus Katarn uniform (Forest)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Forest";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class RC_Solus_eod_armor_V2_Omen : RC_eod_armor_V2 {
		displayName = "RC Solus EOD vest (Omen)";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Armor2_Omen.paa"};
		
		class ItemInfo : VestItem {
			hiddenSelections[] = {"camo1"};
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_eod_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_Solus_s1_armor_Clever : SWLB_clone_commando_sl_armor_k1 {
		displayName = "RC Solus vest (Clever)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Armor2_Clever.paa"};
		hiddenSelections[] = {"camo1"};
		
		class ItemInfo : VestItem {
			hiddenSelections[] = {"camo1"};
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_sl_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_Solus_eod_armor_Forest : RC_eod_armor_V2 {
		displayName = "RC Solus EOD vest (Forest)";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Armor2_Forest.paa"};
		
		class ItemInfo : VestItem {
			hiddenSelections[] = {"camo1"};
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_eod_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_Solus_eod_armor_Sand : RC_eod_armor_V2 {
		displayName = "RC Solus EOD vest (Sand)";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Armor2_Sand.paa"};
		
		class ItemInfo : VestItem {
			hiddenSelections[] = {"camo1"};
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_eod_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_Solus_eod_armor_V2 : RC_eod_armor_V2 {
		displayName = "Katarn II commando EOD vest (47)";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Armor2_47.paa"};
		
		class ItemInfo : VestItem {
			hiddenSelections[] = {"camo1"};
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_eod_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_Solus_Uniform_47 : SWLB_clone_commando_uniform_k1 {
		author = "LastWar Team";
		displayName = "Katarn uniform (47)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "47";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class RC_Solus_Uniform_66 : SWLB_clone_commando_uniform_k1 {
		author = "LastWar Team";
		displayName = "Katarn uniform (66)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "66";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class RC_Uniform_13 : SWLB_clone_commando_uniform_k1 {
		author = "LastWar Team";
		displayName = "Katarn uniform (13)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "13";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class RC_Alpha_Helmet_1 : RC_Helmet {
		author = "LastWar Team";
		displayName = "RC Alpha Katarn Helmet mk2";
		hiddenSelectionsTextures[] = {"SWLA_416th\data\SWLA_416th_Commando_Helmet_Co.paa", "SWLA_416th\data\SWLA_416th_Commando_Helmet_Co.paa"};
	};
	
	class RC_Alpha_Helmet_2 : RC_Helmet {
		author = "LastWar Team";
		displayName = "RC Alpha Katarn Helmet mk2";
		hiddenSelectionsTextures[] = {"SWLA_416th\data\SWLA_416th_Bridger_Helmet_Co.paa", "SWLA_416th\data\SWLA_416th_Bridger_Helmet_Co.paa"};
	};
	
	class RC_Alpha1_Uniform : SWLB_clone_commando_uniform_k1 {
		author = "LastWar Team";
		displayName = "Katarn uniform (Alpha)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Alpha1";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class RC_Alpha2_Uniform : SWLB_clone_commando_uniform_k1 {
		author = "LastWar Team";
		displayName = "Katarn uniform (Alpha)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Alpha2";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class RC_Yivra_nvg_Goran : SWLB_clone_commando_nvg {
		displayName = "RC Yivra visor (Goran)";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Helmet_Goran.paa", "RepCom\Yivra\RC_Yivra_Helmet_Goran.paa"};
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_Yivra_antenna_Goran : SWLB_clone_commando_nvg_antenna {
		displayName = "RC Yivra antenna (Goran)";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Helmet_Goran.paa"};
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_Yivra_antenna_Aden : SWLB_clone_commando_nvg_antenna {
		displayName = "RC Yivra antenna (Aden)";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Helmet_Aden.paa"};
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_Yivra_nvg_Naak : SWLB_clone_commando_nvg {
		displayName = "RC Yivra visor (Naak)";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Helmet_Naak.paa", "RepCom\Yivra\RC_Yivra_Helmet_Naak.paa"};
		visionMode[] = {"Normal", NVG, "TI"};
		thermalMode[] = {0, 1};
	};
	
	class RC_Yivra_Helmet_Elyrea : RC_Helmet {
		author = "LastWar Team";
		displayName = "RC Yivra Katarn Helmet mk2 (Elyrea)";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Helmet_Elyrea.paa", "RepCom\Yivra\RC_Yivra_Helmet_Elyrea.paa"};
		subItems[] = {"Integrated_NVG_TI_1_F"};
	};
	
	class RC_Yivra_Helmet_Goran : RC_Helmet {
		author = "LastWar Team";
		displayName = "RC Yivra Katarn Helmet mk2 (Goran)";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Helmet_Goran.paa", "RepCom\Yivra\RC_Yivra_Helmet_Goran.paa"};
	};
	
	class RC_Yivra_Helmet_Aden : RC_Helmet {
		author = "LastWar Team";
		displayName = "RC Yivra Katarn Helmet mk2 (Aden)";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Helmet_Aden.paa", "RepCom\Yivra\RC_Yivra_Helmet_Aden.paa"};
	};
	
	class RC_Yivra_Helmet_Naak : RC_Helmet {
		author = "LastWar Team";
		displayName = "RC Yivra Katarn Helmet mk2 (Naak)";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Helmet_Naak.paa", "RepCom\Yivra\RC_Yivra_Helmet_Naak.paa"};
	};
	
	class RC_Yivra_s1_armor_Elyrea : RC_sl_armor_V2 {
		displayName = "Yivra Katarn II  squad leader vest (Elyrea)";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Armor2_Elyrea.paa"};
		
		class ItemInfo : VestItem {
			hiddenSelections[] = {"camo1"};
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_sl_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_Yivra_eod_armor_V2_Aden : RC_eod_armor_V2 {
		displayName = "Yivra Katarn II  squad leader vest (Aden)";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Armor2_Aden.paa"};
		
		class ItemInfo : VestItem {
			hiddenSelections[] = {"camo1"};
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_eod_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_Yivra_Sniper_armor_V2_Naak : RC_sniper_armor_V2 {
		displayName = "Yivra Katarn II Sniper vest (Naak)";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Armor2_Naak.paa"};
		
		class ItemInfo : VestItem {
			hiddenSelections[] = {"camo1"};
			uniformModel = "\SWLB_clones_spec\SWLB_clone_commando_sniper_armor.p3d";
			containerClass = "Supply40";
			mass = 80;
			
			class HitpointsProtectionInfo {
				class Chest {
					hitpointName = "HitChest";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Diaphragm {
					hitpointName = "HitDiaphragm";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					armor = 30;
					armorStructural = 5;
					explosionShielding = 0.001;
					minTotalDamageThreshold = 10;
					impactDamageMultiplier = 0.4;
					passThrough = 0.3;
				};
			};
		};
	};
	
	class RC_Yivra_Uniform_Elyrea : SWLB_clone_commando_uniform_k1 {
		author = "LastWar Team";
		displayName = "RC Yivra Katarn uniform (Elyrea)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Elyrea";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class RC_Yivra_Uniform_Goran : SWLB_clone_commando_uniform_k1 {
		author = "LastWar Team";
		displayName = "RC Yivra Katarn uniform (Goran)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Goran";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class RC_Yivra_Uniform_Aden : SWLB_clone_commando_uniform_k1 {
		author = "LastWar Team";
		displayName = "RC Yivra Katarn uniform (Aden)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Aden";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class RC_Yivra_Uniform_Naak : SWLB_clone_commando_uniform_k1 {
		author = "LastWar Team";
		displayName = "RC Yivra Katarn uniform (Naak)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Naak";
			containerClass = "Supply150";
			mass = 40;
		};
	};
};

class CfgVehicles {
	class SWLB_clone_commando_base;	// External class reference
	class RC;	// External class reference
	class RC_backpack;	// External class reference
	class RC_RTO_Backpack;	// External class reference
	class RC_EOD_Backpack;	// External class reference
	class RC_Tech_Backpack;	// External class reference
	
	class RC_Alpha_Backpack : RC_backpack {
		author = "LastWar Team";
		displayName = "RC Alpha Tech Backpack mk2";
		hiddenSelectionsTextures[] = {"SWLA_416th\data\SWLA_416th_Commando_Backpack_Co.paa", "SWLA_416th\data\SWLA_416th_Commando_Backpack_Co.paa"};
	};
	
	class RC_Yivra_RTO_Backpack_Elyrea : RC_RTO_Backpack {
		author = "LastWar Team";
		displayName = "RC Yivra RTO Backpack mk2 (Elyrea)";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Bpack_Elyrea.paa", "RepCom\Yivra\RC_Yivra_Bpack_Elyrea.paa"};
	};
	
	class RC_Yivra_Tech_Backpack_Goran : RC_Tech_Backpack {
		author = "LastWar Team";
		displayName = "RC Yivra Tech Backpack mk2 (Goran)";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_BPack_Goran.paa", "RepCom\Yivra\RC_Yivra_BPack_Goran.paa", "RepCom\Yivra\RC_Yivra_Tech_Goran.paa"};
	};
	
	class RC_Yivra_EOD_Backpack_Aden : RC_EOD_Backpack {
		author = "LastWar Team";
		displayName = "RC Yivra EOD Backpack mk2 (Aden)";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_BPack_Aden.paa", "RepCom\Yivra\RC_Yivra_BPack_Aden.paa"};
	};
	
	class RC_Yivra_Backpack_Naak : RC_backpack {
		author = "LastWar Team";
		displayName = "RC Yivra Backpack mk2 (Naak)";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_BPack_Naak.paa", "RepCom\Yivra\RC_Yivra_BPack_Naak.paa"};
	};
	
	class Alpha1 : RC {
		author = "LastWar Team";
		displayName = "Katarn uniform (Alpha)";
		faction = "LW_Faction";
		editorSubcategory = "RepCom";
		uniformclass = "Alpha1";
		hiddenSelectionsTextures[] = {"SWLA_416th\data\SWLA_416th_Commando_Armor1_Co.paa", "SWLA_416th\data\SWLA_416th_Commando_Armor2_Co.paa"};
		linkedItems[] = {"RC_Alpha_Helmet_1", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"RC_Alpha_Helmet_1", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Alpha2 : RC {
		author = "LastWar Team";
		displayName = "Katarn uniform (Alpha)";
		faction = "LW_Faction";
		editorSubcategory = "RepCom";
		uniformclass = "Alpha2";
		hiddenSelectionsTextures[] = {"SWLA_416th\data\SWLA_416th_Bridger_Armor1_Co.paa", "SWLA_416th\data\SWLA_416th_Bridger_Armor2_Co.paa"};
		linkedItems[] = {"RC_Alpha_Helmet_2", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"RC_Alpha_Helmet_2", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Elyrea : RC {
		author = "LastWar Team";
		displayName = "Katarn uniform (Elyrea)";
		faction = "LW_Faction";
		editorSubcategory = "RepCom";
		uniformclass = "Elyrea";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Armor1_Elyrea.paa", "RepCom\Yivra\RC_Yivra_Armor2_Elyrea.paa"};
		linkedItems[] = {"RC_Yivra_Helmet_Elyrea", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"RC_Yivra_Helmet_Elyrea", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Goran : RC {
		author = "LastWar Team";
		displayName = "Katarn uniform (Goran)";
		faction = "LW_Faction";
		editorSubcategory = "RepCom";
		uniformclass = "Goran";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Armor1_Goran.paa", "RepCom\Yivra\RC_Yivra_Armor2_Goran.paa"};
		linkedItems[] = {"RC_Yivra_Helmet_Elyrea", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"RC_Yivra_Helmet_Elyrea", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Aden : RC {
		author = "LastWar Team";
		displayName = "Katarn uniform (Aden)";
		faction = "LW_Faction";
		editorSubcategory = "RepCom";
		uniformclass = "Aden";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Armor1_Aden.paa", "RepCom\Yivra\RC_Yivra_Armor2_Aden.paa"};
		linkedItems[] = {"RC_Yivra_Helmet_Aden", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"RC_Yivra_Helmet_Aden", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Naak : RC {
		author = "LastWar Team";
		displayName = "Katarn uniform (Naak)";
		faction = "LW_Faction";
		editorSubcategory = "RepCom";
		uniformclass = "Naak";
		hiddenSelectionsTextures[] = {"RepCom\Yivra\RC_Yivra_Armor1_Naak.paa", "RepCom\Yivra\RC_Yivra_Armor2_Naak.paa"};
		linkedItems[] = {"RC_Yivra_Helmet_Naak", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"RC_Yivra_Helmet_Naak", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class RC_Solus_Backpack_Clever : RC_RTO_Backpack {
		author = "LastWar Team";
		displayName = "RC Solus RTO Backpack (Clever)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_BPack_Clever.paa", "RepCom\data\RC_Solus_BPack_Clever.paa"};
	};
	
	class RC_Solus_Backpack_Sand : RC_backpack {
		author = "LastWar Team";
		displayName = "RC Solus Backpack (Sand)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_BPack_Sand.paa", "RepCom\data\RC_Solus_BPack_Sand.paa"};
	};
	
	class RC_Solus_Tech_Backpack_Sand : RC_Tech_Backpack {
		author = "LastWar Team";
		displayName = "RC Solus Tech Backpack (Sand)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_BPack_Sand.paa", "RepCom\data\RC_Solus_BPack_Sand.paa", "RepCom\data\RC_Solus_Tech_Sand.paa"};
	};
	
	class RC_Solus_EOD_Backpack_Sand : RC_EOD_Backpack {
		author = "LastWar Team";
		displayName = "RC Solus EOD Backpack (Sand)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_BPack_Sand.paa", "RepCom\data\RC_Solus_BPack_Sand.paa"};
	};
	
	class RC_Solus_Backpack_Forest : RC_backpack {
		author = "LastWar Team";
		displayName = "RC Solus Backpack (Forest)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_BPack_Forest.paa", "RepCom\data\RC_Solus_BPack_Forest.paa"};
	};
	
	class RC_Solus_Tech_Backpack_Forest : RC_Tech_Backpack {
		author = "LastWar Team";
		displayName = "RC Solus Tech Backpack (Forest)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_BPack_Forest.paa", "RepCom\data\RC_Solus_BPack_Forest.paa", "RepCom\data\RC_Solus_Tech_Forest.paa"};
	};
	
	class RC_Solus_EOD_Backpack_Forest : RC_EOD_Backpack {
		author = "LastWar Team";
		displayName = "RC Solus EOD Backpack (Forest)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_BPack_Forest.paa", "RepCom\data\RC_Solus_BPack_Forest.paa"};
	};
	
	class RC_Solus_Backpack_66 : RC_backpack {
		author = "LastWar Team";
		displayName = "RC Backpack mk2 (66)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Bpack_66.paa", "RepCom\data\RC_Solus_Bpack_66.paa"};
	};
	
	class RC_Solus_EOD_Backpack_Omen : RC_EOD_Backpack {
		author = "LastWar Team";
		displayName = "RC EOD Backpack mk2 (Omen)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Bpack_Omen.paa", "RepCom\data\RC_Solus_Bpack_Omen.paa"};
	};
	
	class RC_Solus_EOD_Backpack_47 : RC_EOD_Backpack {
		author = "LastWar Team";
		displayName = "RC EOD Backpack mk2 (47)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Bpack_47.paa", "RepCom\data\RC_Solus_Bpack_47.paa"};
	};
	
	class RC_RTO_Backpack_13 : RC_RTO_Backpack {
		author = "LastWar Team";
		displayName = "RC RTO Backpack mk2 (13)";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Rto_13.paa", "RepCom\data\RC_Rto_13.paa"};
	};
	
	class Omen : RC {
		author = "LastWar Team";
		displayName = "Katarn uniform (Omen)";
		faction = "LW_Faction";
		editorSubcategory = "RepCom";
		uniformclass = "Omen";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Armor1_Omen.paa", "RepCom\data\RC_Solus_Armor2_Omen.paa"};
		linkedItems[] = {"RC_Solus_Helmet_Omen", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"RC_Solus_Helmet_Omen", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Clever : RC {
		author = "LastWar Team";
		displayName = "Katarn uniform (Clever)";
		faction = "LW_Faction";
		editorSubcategory = "RepCom";
		uniformclass = "Clever";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Armor1_Clever.paa", "RepCom\data\RC_Solus_Armor2_Clever.paa"};
		linkedItems[] = {"RC_Solus_Helmet_Forest", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"RC_Solus_Helmet_Forest", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Forest : RC {
		author = "LastWar Team";
		displayName = "Katarn uniform (Forest)";
		faction = "LW_Faction";
		editorSubcategory = "RepCom";
		uniformclass = "Forest";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Armor1_Forest.paa", "RepCom\data\RC_Solus_Armor2_Forest.paa"};
		linkedItems[] = {"RC_Solus_Helmet_Forest", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"RC_Solus_Helmet_Forest", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Sand : RC {
		author = "LastWar Team";
		displayName = "Katarn uniform (Sand)";
		faction = "LW_Faction";
		editorSubcategory = "RepCom";
		uniformclass = "Sand";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Armor1_Sand.paa", "RepCom\data\RC_Solus_Armor2_Sand.paa"};
		linkedItems[] = {"RC_Solus_Helmet_Sand", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"RC_Solus_Helmet_Sand", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class 66 : RC {
		author = "LastWar Team";
		displayName = "Katarn uniform (66)";
		faction = "LW_Faction";
		editorSubcategory = "RepCom";
		uniformclass = "66";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Armor1_66.paa", "RepCom\data\RC_Solus_Armor2_66.paa"};
		linkedItems[] = {"RC_Solus_Helmet_47", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"RC_Solus_Helmet_47", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class 47 : RC {
		author = "LastWar Team";
		displayName = "Katarn uniform (47)";
		faction = "LW_Faction";
		editorSubcategory = "RepCom";
		uniformclass = "47";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Solus_Armor1_47.paa", "RepCom\data\RC_Solus_Armor2_47.paa"};
		linkedItems[] = {"RC_Solus_Helmet_47", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"RC_Solus_Helmet_47", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class 13 : RC {
		author = "LastWar Team";
		displayName = "Katarn uniform (13)";
		faction = "LW_Faction";
		editorSubcategory = "RepCom";
		uniformclass = "13";
		hiddenSelectionsTextures[] = {"RepCom\data\RC_Armor1_13.paa", "RepCom\data\RC_Armor2_13.paa"};
		linkedItems[] = {"RC_Helmet_13", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"RC_Helmet_13", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
};

class cfgMods {
	author = "Last Force Project";
	timepacked = 1594648239;
};
