// config.bin - 23:37:36 07/23/20, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class 66_Legion {
		units[] = {""};
		weapons[] = {""};
	};
	author = "LastWarTeam";
	requiredAddons[] = {"SWLB_clones", "SWLB_equipment", SWLB_CEE};
};

class CfgFactionClasses {
	class LW_Faction {
		displayName = "LastWar";
	};
};

class CfgEditorSubcategories {
	class 66_Legion {
		displayName = "66th LW Legion";
	};
};

class CfgWeapons {
	class H_HelmetO_ViperSP_hex_F;	// External class reference
	class SWLB_clone_ccVisor;	// External class reference
	class SWLB_clone_mcVisor;	// External class reference
	class SWLB_clone_nvg;	// External class reference
	class SWLB_clone_nvg_nco;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_nvg_spec;	// External class reference
	class SWLB_clone_nvg_spec_nco;	// External class reference
	class SWLB_clone_commando_nvg_antenna;	// External class reference
	class SWLB_clone_commando_nvg;	// External class reference
	class SWLB_clone_P1_2_helmet;	// External class reference
	class SWLB_clone_ARF_P1_helmet;	// External class reference
	class SWLB_clone_P1_helmet;	// External class reference
	class SWLB_clone_eng_helmet;	// External class reference
	class SWLB_clone_BARC_helmet;	// External class reference
	class SWLB_clone_P2_helmet;	// External class reference
	class SWLB_clone_AB_helmet;	// External class reference
	class SWLB_clone_P15_helmet;	// External class reference
	class SDT_Hazard_Helmet;	// External class reference
	class SDT_stealth_helmet;	// External class reference
	class Scout_helmet;	// External class reference
	class SWLB_clone_pilot_P2_helmet;	// External class reference
	class SWLB_clone_commando_helmet_k1;	// External class reference
	class SWLB_clone_recon_armor;	// External class reference
	class SWLB_clone_recon_officer_armor;	// External class reference
	class SWLB_clone_recon_nco_armor;	// External class reference
	class SWLB_clone_officer_armor;	// External class reference
	class SWLB_clone_medic_armor;	// External class reference
	class SWLB_clone_kama_armor;	// External class reference
	class SWLB_clone_mc_uniform;	// External class reference
	class SWLB_clone_commander_armor;	// External class reference
	class SWLB_clone_cfr_armor;	// External class reference
	class SWLB_clone_airborne_armor;	// External class reference
	class SWLB_CEE_Force_Recon_Officer;	// External class reference
	class SWLB_clone_airborne_nco_armor;	// External class reference
	class SWLB_clone_arc_armor;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	class SWLB_P2_SpecOps_Helmet;	// External class reference
	class SWLA_BL_Sergeant_Vest;	// External class reference
	class SWLB_CEE_Fox_Visor;	// External class reference
	class UniformItem;	// External class reference
	class HeadgearItem;	// External class reference
	class SDT_pilot_p1_helmet;	// External class reference
	class SWLB_P1_Pilot_Helmet;	// External class reference
	class SWLB_CEE_Hazard_Helmet;	// External class reference
	
	class 66_HelmetP2_ENG : SWLB_clone_eng_helmet {
		author = "LastWarTeam";
		displayName = "66th Clone Trooper P2 Eng helmet";
		hiddenSelectionsTextures[] = {"66_Unit\data\66_HelmetP2_ENG.paa", "66_Unit\data\66_HelmetP2_ENG.paa"};
	};
	
	class 66_HelmetP2 : SWLB_clone_P2_helmet {
		author = "LastWarTeam";
		displayName = "66th Clone Trooper P2 helmet (Sergeant)";
		hiddenSelectionsTextures[] = {"66_Unit\data\66_HelmetP2.paa"};
	};
	
	class 66_HelmetP2_Specialist : SWLB_clone_P2_helmet {
		author = "LastWarTeam";
		displayName = "66th Clone Trooper P2 helmet (Specialist)";
		hiddenSelectionsTextures[] = {"66_Unit\data\66_HelmetP2_Specialist.paa"};
	};
	
	class 66_HelmetP2_AT : SWLB_clone_P2_helmet {
		author = "LastWarTeam";
		displayName = "66th Clone Trooper P2 helmet (AT)";
		hiddenSelectionsTextures[] = {"66_Unit\data\66_HelmetP2_AT.paa"};
	};
	
	class 66_HelmetP2_GR : SWLB_clone_P2_helmet {
		author = "LastWarTeam";
		displayName = "66th Clone Trooper P2 helmet (GR)";
		hiddenSelectionsTextures[] = {"66_Unit\data\66_HelmetP2_GR.paa"};
	};
	
	class 66_HelmetP2_Med : SWLB_clone_P2_helmet {
		author = "LastWarTeam";
		displayName = "66th Clone Trooper P2 helmet (Med)";
		hiddenSelectionsTextures[] = {"66_Unit\data\66_HelmetP2_Med.paa"};
	};
	
	class 66_HelmetP2_O : SWLB_clone_P2_helmet {
		author = "LastWarTeam";
		displayName = "66th Clone Trooper P2 helmet (O)";
		hiddenSelectionsTextures[] = {"66_Unit\data\66_HelmetP2_O.paa"};
	};
	
	class 66_HelmetP2_Rec : SWLB_clone_P2_helmet {
		author = "LastWarTeam";
		displayName = "66th Clone Trooper P2 helmet (Rec)";
		hiddenSelectionsTextures[] = {"66_Unit\data\66_HelmetP2_Rec.paa"};
	};
	
	class 66_HelmetP15_ARC : SWLB_clone_P15_helmet {
		author = "LastWarTeam";
		displayName = "66th Clone Trooper P2 helmet (ARC)";
		hiddenSelectionsTextures[] = {"66_Unit\data\66_HelmetP15_ARC.paa"};
	};
	
	class 66_HelmetSO_MG_2 : SWLB_P2_SpecOps_Helmet {
		displayName = "66th Clone Trooper P2 helmet (MG-2)";
		hiddenSelectionsTextures[] = {"66_Unit\data\66_HelmetSO_MG_2"};
	};
	
	class 66_HelmetSO_MG : SWLB_P2_SpecOps_Helmet {
		displayName = "66th Clone Trooper P2 helmet (MG)";
		hiddenSelectionsTextures[] = {"66_Unit\data\66_HelmetSO_MG"};
	};
	
	class 66_Helmet12_Lima : SWLB_clone_P1_2_helmet {
		author = "LastWarTeam";
		displayName = "66th Clone Trooper ARC helmet (Lima)";
		hiddenSelectionsTextures[] = {"66_Unit\data\66_Helmet12_Lima.paa"};
	};
	
	class 66_Helmet_Hazard : SWLB_CEE_Hazard_Helmet {
		author = "LastWarTeam";
		displayName = "66th Clone Trooper Hazard helmet";
		hiddenSelectionsTextures[] = {"66_Unit\data\66_Helmet_Hazard.paa"};
	};
};

class CfgVehicles {
	class SWLB_clone_base_P2;	// External class reference
	class SWLB_clone_base_P1;	// External class reference
	class SWLB_clone_assault_base_P2;	// External class reference
	class SWLB_clone_cfr_base_P2;	// External class reference
	class SWLB_clone_medic_base_P2;	// External class reference
	class SWLB_clone_RTO_base_P2;	// External class reference
	class SWLB_clone_recon_base_P2;	// External class reference
	class SWLB_clone_recon_nco_base_P2;	// External class reference
	class SWLB_clone_recon_officer_base_P2;	// External class reference
	class SWLB_clone_airborne_base_P2;	// External class reference
	class SWLB_clone_airborne_nco_base_P2;	// External class reference
	class SWLB_clone_lieutenant_base_P2;	// External class reference
	class SWLB_clone_captain_base_P2;	// External class reference
	class SWLB_clone_commander_base_P2;	// External class reference
	class SWLB_clone_marshal_commander_base_P2;	// External class reference
	class SWLB_clone_arc_base_P2;	// External class reference
	class SWLB_clone_pilot_base_P2;	// External class reference
	class SWLB_clone_sniper_base_P2;	// External class reference
	class SWLB_clone_sg_base_P2;	// External class reference
	class SWLB_clone_at_base_P2;	// External class reference
	class SWLB_clone_backpack;	// External class reference
	class SWLB_clone_backpack_eod;	// External class reference
	class SWLB_clone_backpack_heavy;	// External class reference
	class SWLB_clone_backpack_medic;	// External class reference
	class SWLB_mando_base_assault;	// External class reference
	class SWLB_clone_backpack_RTO;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_RTO_mini_backpack;	// External class reference
	class SWLB_clone_uniform;	// External class reference
};

class cfgMods {
	author = "Last Force Project";
	timepacked = 1594648116;
};
