// config.bin - 23:37:30 07/23/20, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class 41_Legion {
		units[] = {JP_41_1, "41", "Gree"};
		weapons[] = {"41_Uniform", "41_Uniform_Gree"};
	};
	author = "LastWarTeam";
	requiredAddons[] = {"Jet_Unit", "SWLB_clones", "SWLB_equipment", SWLB_CEE};
};

class CfgFactionClasses {
	class LW_Faction {
		displayName = "LastWar";
	};
};

class CfgEditorSubcategories {
	class 41_Legion {
		displayName = "41st LW Legion";
	};
};

class CfgWeapons {
	class H_HelmetO_ViperSP_hex_F;	// External class reference
	class SWLB_clone_ccVisor;	// External class reference
	class SWLB_clone_mcVisor;	// External class reference
	class SWLB_clone_nvg;	// External class reference
	class SWLB_clone_nvg_nco;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_nvg_spec;	// External class reference
	class SWLB_clone_nvg_spec_nco;	// External class reference
	class SWLB_clone_commando_nvg_antenna;	// External class reference
	class SWLB_clone_commando_nvg;	// External class reference
	class SWLB_clone_P1_2_helmet;	// External class reference
	class SWLB_clone_ARF_P1_helmet;	// External class reference
	class SWLB_clone_ARF_P2_helmet;	// External class reference
	class SWLB_clone_P1_helmet;	// External class reference
	class SWLB_clone_eng_helmet;	// External class reference
	class SWLB_clone_BARC_helmet;	// External class reference
	class SWLB_clone_P2_helmet;	// External class reference
	class SWLB_clone_AB_helmet;	// External class reference
	class SWLB_clone_P15_helmet;	// External class reference
	class SDT_Hazard_Helmet;	// External class reference
	class SDT_stealth_helmet;	// External class reference
	class Scout_helmet;	// External class reference
	class SWLB_clone_pilot_P2_helmet;	// External class reference
	class SWLB_clone_commando_helmet_k1;	// External class reference
	class SWLB_clone_recon_armor;	// External class reference
	class SWLB_clone_recon_officer_armor;	// External class reference
	class SWLB_clone_recon_nco_armor;	// External class reference
	class SWLB_clone_officer_armor;	// External class reference
	class SWLB_clone_medic_armor;	// External class reference
	class SWLB_clone_kama_armor;	// External class reference
	class SWLB_clone_mc_uniform;	// External class reference
	class SWLB_clone_commander_armor;	// External class reference
	class SWLB_clone_cfr_armor;	// External class reference
	class SWLB_clone_airborne_armor;	// External class reference
	class SWLB_CEE_Force_Recon_Officer;	// External class reference
	class SWLB_clone_airborne_nco_armor;	// External class reference
	class SWLB_clone_arc_armor;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	class SWLA_BL_Sergeant_Vest;	// External class reference
	class SWLB_CEE_Fox_Visor;	// External class reference
	class UniformItem;	// External class reference
	class HeadgearItem;	// External class reference
	class SDT_pilot_p1_helmet;	// External class reference
	class SWLB_P1_Pilot_Helmet;	// External class reference
	class SWLB_CEE_Hazard_Helmet;	// External class reference
	
	class 41_HelmetP1_Pilot : SWLB_P1_Pilot_Helmet {
		author = "LastWar Team";
		displayName = "41st Clone Trooper P1 Helmet (Pilot)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_HelmetP1_Pilot.paa", "swlb_cee\data\swlb_p1_pilot_lifesupport_co.paa"};
	};
	
	class 41_ARF_P2_helmet : SWLB_clone_ARF_P2_helmet {
		author = "LastWar Team";
		displayName = "41st Clone trooper P2 ARF helmet (GC)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_HelmetP2_ARF.paa", "", "41_Unit\data\41_ARF_Flaps.paa"};
	};
	
	class 41_HelmetP2_Skull2 : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "41st Clone Trooper P2 Helmet (Skull)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_HelmetP2_Skull2.paa"};
	};
	
	class 41_HelmetP2_Pekar : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "41st Clone Trooper P2 Helmet (Pekar)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_HelmetP2_Pekar.paa"};
	};
	
	class 41_HelmetP2_GC : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "41st Clone Trooper P2 Helmet (GC)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_HelmetP2_GC.paa"};
	};
	
	class 41_HelmetP2_ARF : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "41st Clone Trooper P1 ARF Helmet (GC)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_HelmetP2_ARF.paa"};
	};
	
	class 41_HelmetP2_ARC : SWLB_clone_P15_helmet {
		author = "LastWar Team";
		displayName = "41st Clone Trooper P2 ARC Helmet (GC)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_HelmetP2_ARC.paa"};
	};
	
	class 41_Helmet15 : SWLB_clone_P15_helmet {
		author = "LastWar Team";
		displayName = "41st Clone Trooper P2 ARC Helmet";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Helmet15.paa"};
	};
	
	class 41_Helmet_Hazard : SWLB_CEE_Hazard_Helmet {
		author = "LastWar Team";
		displayName = "41st Clone Trooper P2 Hazard Helmet (GC)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Helmet_Hazard.paa"};
	};
	
	class 41_HelmetP2_Barc : SWLB_clone_BARC_helmet {
		author = "LastWar Team";
		displayName = "41st Clone Trooper P2 BARC Helmet (GC)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_HelmetP2_Barc.paa"};
	};
	
	class 41_HelmetP2_Eng : SWLB_clone_eng_helmet {
		author = "LastWar Team";
		displayName = "41st Clone Trooper P2 ENG Helmet (GC)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_HelmetP2_Eng.paa"};
	};
	
	class 41_HelmetP2_Pilot : SWLB_clone_pilot_P2_helmet {
		author = "LastWar Team";
		displayName = "41st Clone Trooper P2 Pilot Helmet (GC)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_HelmetP2_Pilot.paa", "41_Unit\data\41_HelmetP2_Pilot.paa"};
	};
	
	class 41_HelmetP1_Atlas : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "41st Clone Trooper P1 Helmet (Atlas)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_HelmetP1_Atlas.paa"};
	};
	
	class 41_Uniform_Skull2 : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "41st Clone Trooper Uniform (Skull\2)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Skull2";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 41_Uniform_GreenComp : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "41st Clone Trooper Uniform (GC)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "GreenComp";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 41_Uniform_Watch : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "41st Clone Trooper Uniform (Watch)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Watch";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 41_Uniform_Skull : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "41st Clone Trooper Uniform (Skull)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Skull";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 41_Uniform_Lp : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "41st Clone Trooper Uniform (Lp)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Lp";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 41_Uniform_Fist : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "41st Clone Trooper Uniform (Fist)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Fist";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 41_Uniform_Falcon : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "41st Clone Trooper Uniform (Falcon)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Falcon";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 41_Uniform_Atlas : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "41st Clone Trooper Uniform (Atlas)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Atlas";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 41_Uniform : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "41st Clone Trooper Uniform";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "41";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 41_Uniform_Gree : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "41st Clone Trooper Uniform (Gree)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Gree";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 41_Plate_Watch : SWLB_clone_arc_armor {
		displayName = "41st ARC Camo\Plate (Watch)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Plate_Watch.paa", "41_Unit\data\41_Camo_ARC.paa"};
	};
	
	class 41_Plate_Skull : SWLB_clone_arc_armor {
		displayName = "41st ARC Camo\Plate (Skull)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Plate_Skull.paa", "41_Unit\data\41_Camo_ARC.paa"};
	};
	
	class 41_Plate_LP : SWLB_clone_arc_armor {
		displayName = "41st ARC Camo\Plate (LP)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Plate_LP.paa", "41_Unit\data\41_Camo_ARC.paa"};
	};
	
	class 41_Plate_Fist : SWLB_clone_arc_armor {
		displayName = "41st ARC Camo\Plate (Fist)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Plate_Fist.paa", "41_Unit\data\41_Camo_ARC.paa"};
	};
	
	class 41_Plate_Falcon : SWLB_clone_arc_armor {
		displayName = "41st ARC Camo\Plate (Falcon)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Plate_Falcon.paa", "41_Unit\data\41_Camo_ARC.paa"};
	};
	
	class 41_Camo_Atlas : SWLB_clone_kama_armor {
		displayName = "41st Camo (Atlas)";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Camo_Atlas.paa"};
	};
};

class CfgVehicles {
	class SWLB_clone_base_P2;	// External class reference
	class SWLB_clone_base_P1;	// External class reference
	class SWLB_clone_assault_base_P2;	// External class reference
	class SWLB_clone_cfr_base_P2;	// External class reference
	class SWLB_clone_medic_base_P2;	// External class reference
	class SWLB_clone_RTO_base_P2;	// External class reference
	class SWLB_clone_recon_base_P2;	// External class reference
	class SWLB_clone_recon_nco_base_P2;	// External class reference
	class SWLB_clone_recon_officer_base_P2;	// External class reference
	class SWLB_clone_airborne_base_P2;	// External class reference
	class SWLB_clone_airborne_nco_base_P2;	// External class reference
	class SWLB_clone_lieutenant_base_P2;	// External class reference
	class SWLB_clone_captain_base_P2;	// External class reference
	class SWLB_clone_commander_base_P2;	// External class reference
	class SWLB_clone_marshal_commander_base_P2;	// External class reference
	class SWLB_clone_arc_base_P2;	// External class reference
	class SWLB_clone_pilot_base_P2;	// External class reference
	class SWLB_clone_sniper_base_P2;	// External class reference
	class SWLB_clone_sg_base_P2;	// External class reference
	class SWLB_clone_at_base_P2;	// External class reference
	class SWLB_clone_backpack;	// External class reference
	class SWLB_clone_backpack_eod;	// External class reference
	class SWLB_clone_backpack_heavy;	// External class reference
	class SWLB_clone_backpack_medic;	// External class reference
	class SWLB_mando_base_assault;	// External class reference
	class SWLB_clone_backpack_RTO;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_RTO_mini_backpack;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	
	class Skull2 : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "41st Clone Trooper (Skull2)";
		faction = "LW_Faction";
		editorSubcategory = "41_Legion";
		uniformclass = "GreenComp";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Armor1_Skull2.paa", "41_Unit\data\41_Armor2_Skull2.paa"};
		linkedItems[] = {"41_HelmetP2_Skull2", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"41_HelmetP2_Skull2", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class GreenComp : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "41st Clone Trooper (GC)";
		faction = "LW_Faction";
		editorSubcategory = "41_Legion";
		uniformclass = "GreenComp";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Armor1_GC.paa", "41_Unit\data\41_Armor2_GC.paa"};
		linkedItems[] = {"41_HelmetP2_GC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"41_HelmetP2_GC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Atlas : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "41st Clone Trooper (Atlas)";
		faction = "LW_Faction";
		editorSubcategory = "41_Legion";
		uniformclass = "Atlas";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Armor1_Atlas.paa", "41_Unit\data\41_Armor2_Atlas.paa"};
		linkedItems[] = {"41_HelmetP1_Atlas", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"41_HelmetP1_Atlas", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Falcon : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "101st Clone Trooper (Falcon)";
		faction = "LW_Faction";
		editorSubcategory = "41_Legion";
		uniformclass = "Falcon";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Armor1_Falcon.paa", "41_Unit\data\41_Armor2_LP.paa"};
		linkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Fist : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "101st Clone Trooper (Fist)";
		faction = "LW_Faction";
		editorSubcategory = "41_Legion";
		uniformclass = "Fist";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Armor1_Fist.paa", "41_Unit\data\41_Armor2_LP.paa"};
		linkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class LP : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "101st Clone Trooper (LP)";
		faction = "LW_Faction";
		editorSubcategory = "41_Legion";
		uniformclass = "LP";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Armor1_LP.paa", "41_Unit\data\41_Armor2_LP.paa"};
		linkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Skull : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "101st Clone Trooper (Skull)";
		faction = "LW_Faction";
		editorSubcategory = "41_Legion";
		uniformclass = "Skull";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Armor1_Skull.paa", "41_Unit\data\41_Armor2_LP.paa"};
		linkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Watch : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "101st Clone Trooper (Watch)";
		faction = "LW_Faction";
		editorSubcategory = "41_Legion";
		uniformclass = "Watch";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Armor1_Watch.paa", "41_Unit\data\41_Armor2_LP.paa"};
		linkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class 41 : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "101st Clone Trooper (41)";
		faction = "LW_Faction";
		editorSubcategory = "41_Legion";
		uniformclass = "41";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Armor1.paa", "SWLB_clones\data\camo2_co.paa"};
		linkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Gree : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "101st Clone Trooper (Gree)";
		faction = "LW_Faction";
		editorSubcategory = "41_Legion";
		uniformclass = "Gree";
		hiddenSelectionsTextures[] = {"41_Unit\data\41_Armor1_Gree.paa", "41_Unit\data\41_Armor2_Gree.paa"};
		linkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"101_HelmetP1_ARC", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
};

class cfgMods {
	author = SCHTAMP;
	timepacked = 1594731952;
};
