// config.bin - 23:38:23 07/23/20, generated in 0.06 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class 501_Legion {
		units[] = {"Husky", "Glyba", "Liver", "Flin", "Fren", "Dok", "Kid", "Oni", "Olaf", "Grif", "Draxler", "Mali", "Bjorn", "Kira", "Radaga"};
		weapons[] = {"501_HelmetP1_Echo", "501_Uniform_Husky", "501_HelmetP1_Husky", "501_Uniform_Glyba", "501_HelmetP1_Glyba", "501_Uniform_Liver", "501_HelmetP1_Liver", "501_HelmetP1_Tron", "501_HelmetP1_Fives", "501_HelmetP1_Pilot", "501_HelmetP1_Fren", "501_Uniform_Fren", "501_HelmetP1_Dok", "501_Uniform_Dok", "501_HelmetP1_Radaga", "501_Uniform_Radaga", "501_HelmetP1_Kira", "501_Uniform_Kira", "501_HelmetP1_Bjorn", "501_Uniform_Bjorn", "501_HelmetP1_Mali", "501_Uniform_Mali", "501_HelmetP1_Kid", "501_Uniform_Kid", "501_HelmetP1_Oni", "501_Uniform_Oni", "501_HelmetP1_Olaf", "501_Uniform_Olaf", "501_HelmetP1", "501_Uniform_Grif", "501_HelmetP1_Grif", "501_Uniform_Draxler", "501_HelmetP1_Draxler"};
	};
	author = "LastWarTeam";
	requiredAddons[] = {"SWLB_clones"};
};

class CfgFactionClasses {
	class LW_Faction {
		displayName = "LastWar";
	};
};

class CfgEditorSubcategories {
	class 501_Legion {
		displayName = "501st LW Legion";
	};
};

class CfgWeapons {
	class H_HelmetO_ViperSP_hex_F;	// External class reference
	class SWLB_clone_ccVisor;	// External class reference
	class SWLB_clone_mcVisor;	// External class reference
	class SWLB_clone_nvg;	// External class reference
	class SWLB_clone_nvg_nco;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_nvg_spec;	// External class reference
	class SWLB_clone_nvg_spec_nco;	// External class reference
	class SWLB_clone_commando_nvg_antenna;	// External class reference
	class SWLB_clone_commando_nvg;	// External class reference
	class SWLB_clone_P1_2_helmet;	// External class reference
	class SWLB_clone_ARF_P1_helmet;	// External class reference
	class SWLB_clone_P1_helmet;	// External class reference
	class SWLB_clone_eng_helmet;	// External class reference
	class SWLB_clone_BARC_helmet;	// External class reference
	class SWLB_clone_P2_helmet;	// External class reference
	class SWLB_clone_AB_helmet;	// External class reference
	class SWLB_clone_P15_helmet;	// External class reference
	class SDT_Hazard_Helmet;	// External class reference
	class SDT_stealth_helmet;	// External class reference
	class Scout_helmet;	// External class reference
	class SWLB_clone_pilot_P2_helmet;	// External class reference
	class SWLB_clone_commando_helmet_k1;	// External class reference
	class SWLB_clone_recon_armor;	// External class reference
	class SWLB_clone_recon_officer_armor;	// External class reference
	class SWLB_clone_recon_nco_armor;	// External class reference
	class SWLB_clone_officer_armor;	// External class reference
	class SWLB_clone_medic_armor;	// External class reference
	class SWLB_clone_kama_armor;	// External class reference
	class SWLB_clone_mc_uniform;	// External class reference
	class SWLB_clone_commander_armor;	// External class reference
	class SWLB_clone_cfr_armor;	// External class reference
	class SWLB_clone_airborne_armor;	// External class reference
	class SWLB_clone_airborne_nco_armor;	// External class reference
	class SWLB_clone_arc_armor;	// External class reference
	class SWLB_clone_commando_eod_armor_k1;	// External class reference
	class SWLB_clone_commando_sniper_armor_k1;	// External class reference
	class SWLB_clone_commando_sl_armor_k1;	// External class reference
	class SWLB_clone_commando_tech_armor_k1;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	class SWLB_clone_commando_uniform_k1;	// External class reference
	class SWLA_BL_Sergeant_Vest;	// External class reference
	class SWLB_mando_og_helmet;	// External class reference
	class SWLB_mando_og_armor;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_mando_uniform;	// External class reference
	class UniformItem;	// External class reference
	class HeadgearItem;	// External class reference
	class SDT_pilot_p1_helmet;	// External class reference
	class SWLB_P1_Pilot_Helmet;	// External class reference
	class SWLB_CEE_Hazard_Helmet;	// External class reference
	
	class 501_Helmet15_ARC : SWLB_clone_P15_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper ARC Helmet";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Helmet15_ARC.paa"};
	};
	
	class 501_Helmet_Hazard : SWLB_CEE_Hazard_Helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Hazard Helmet";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Helmet_Hazard.paa"};
	};
	
	class 501_HelmetP15_Flin : SWLB_clone_P15_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Flin)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP15_Flin.paa"};
	};
	
	class 501_HelmetP2_Pilot : SWLB_clone_pilot_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Pilot Helmet";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Pilot.paa", "501_Unit\data\501_HelmetP2_Pilot.paa"};
	};
	
	class 501_HelmetP2_Arsi : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Arsi)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Arsi.paa"};
	};
	
	class 501_HelmetP2 : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2.paa"};
	};
	
	class 501_HelmetP2_Skink : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Skink)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Skink.paa"};
	};
	
	class 501_HelmetP2_Bjorn : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Bjorn)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Bjorn.paa"};
	};
	
	class 501_HelmetP2_Dok : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Dok)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Dok.paa"};
	};
	
	class 501_HelmetP2_Eng : SWLB_clone_eng_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Eng)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Eng.paa"};
	};
	
	class 501_HelmetP2_Fren : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Fren)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Fren.paa"};
	};
	
	class 501_HelmetP2_Glyba : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Glyba)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Glyba.paa"};
	};
	
	class 501_HelmetP2_Husky : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Husky)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Husky.paa"};
	};
	
	class 501_HelmetP2_Kid : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Kid)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Kid.paa"};
	};
	
	class 501_HelmetP2_Kira : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Kira)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Kira.paa"};
	};
	
	class 501_HelmetP2_Liver : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Liver)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Liver.paa"};
	};
	
	class 501_HelmetP2_Mali : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Mali)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Mali.paa"};
	};
	
	class 501_HelmetP2_Med : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Med)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Med.paa"};
	};
	
	class 501_HelmetP2_Mg : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Mg)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Mg.paa"};
	};
	
	class 501_HelmetP2_Olaf : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Olaf)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Olaf.paa"};
	};
	
	class 501_HelmetP2_Oni : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Oni)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Oni.paa"};
	};
	
	class 501_HelmetP2_Radaga : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Radaga)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Radaga.paa"};
	};
	
	class 501_HelmetP2_Tron : SWLB_clone_P2_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P2 Helmet (Tron)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP2_Tron.paa"};
	};
	
	class 501_HelmetP1_Pilot : SWLB_P1_Pilot_Helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Pilot)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Pilot.paa", "swlb_cee\data\swlb_p1_pilot_lifesupport_co.paa"};
	};
	
	class 501_HelmetP1_Echo : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Echo)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Echo.paa"};
	};
	
	class 501_HelmetP1_Husky : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Husky)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Husky.paa"};
	};
	
	class 501_HelmetP1_Glyba : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Glyba)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Glyba.paa"};
	};
	
	class 501_HelmetP1_Flin : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Flin)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Flin.paa"};
	};
	
	class 501_HelmetP1_Liver : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Liver)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Liver.paa"};
	};
	
	class 501_HelmetP1_Fives : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Fives)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Fives.paa"};
	};
	
	class 501_HelmetP1_Tron : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Tron)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Tron.paa"};
	};
	
	class 501_HelmetP1_Fren : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Fren)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Fren.paa"};
	};
	
	class 501_HelmetP1_Dok : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Dok)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Dok.paa"};
	};
	
	class 501_HelmetP1_Radaga : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Radaga)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Radaga.paa"};
	};
	
	class 501_HelmetP1_Kira : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Kira)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Kira.paa"};
	};
	
	class 501_HelmetP1_Bjorn : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Bjorn)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Bjorn.paa"};
	};
	
	class 501_HelmetP1_Mali : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Mali)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Mali.paa"};
	};
	
	class 501_HelmetP1_MG : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (MG)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_MG.paa"};
	};
	
	class 501_HelmetP1_Med : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Med)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Med.paa"};
	};
	
	class 501_HelmetP1_Eng : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (ENG)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Eng.paa"};
	};
	
	class 501_HelmetP1 : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1.paa"};
	};
	
	class 501_HelmetP1_Olaf : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Olaf)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Olaf.paa"};
	};
	
	class 501_HelmetP1_Oni : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Oni)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Oni.paa"};
	};
	
	class 501_HelmetP1_Kid : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Kid)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Kid.paa"};
	};
	
	class 501_HelmetP1_Grif : SWLB_clone_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper P1 Helmet (Grif)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetP1_Grif.paa"};
	};
	
	class 501_HelmetARF_Draxler : SWLB_clone_ARF_P1_helmet {
		author = "LastWar Team";
		displayName = "501st Clone Trooper ARF Helmet (Draxler)";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_HelmetARF_Draxler.paa"};
	};
	
	class 501_Uniform_Skink : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Skink)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Skink";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Husky : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Husky)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Husky";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Glyba : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Glyba)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Glyba";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Liver : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Liver)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Liver";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Flin : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Flin)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Flin";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Tron : SWLB_clone_mc_uniform {
		author = "LastWar Team";
		displayName = "501st Clone marshal commander armor (Tron)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Tron";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Fren : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Fren)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Fren";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Dok : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Dok)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Dok";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Radaga : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Radaga)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Radaga";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Mali : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Mali)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Mali";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Olaf : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Olaf)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Olaf";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Oni : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Oni)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Oni";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Kid : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Kid)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Kid";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Grif : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Grif)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Grif";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Draxler : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper ARF Uniform (Draxler)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Draxler";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Bjorn : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Bjorn)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Bjorn";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_Uniform_Kira : SWLB_clone_uniform {
		author = "LastWar Team";
		displayName = "501st Clone Trooper Uniform (Kira)";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Kira";
			containerClass = "Supply150";
			mass = 40;
		};
	};
	
	class 501_ARC_Camo_Plate_Flin : SWLB_clone_arc_armor {
		displayName = "501st ARC Camo\Plate (Flin)";
		hiddenSelectionsTextures[] = {"\501_unit\data\501_Plate_Flin.paa", "\501_unit\data\501_Camo_Flin.paa"};
	};
	
	class 501_ARC_Camo_Mali : SWLB_clone_arc_armor {
		displayName = "501st ARC Camo (Mali)";
		hiddenSelectionsTextures[] = {"", "\501_unit\data\501_Camo_Mali.paa"};
	};
};

class CfgVehicles {
	class SWLB_clone_commando_base;	// External class reference
	class SWLB_clone_commando_backpack_k2;	// External class reference
	class SWLB_clone_commando_backpack_k2_rto;	// External class reference
	class SWLB_clone_commando_backpack_k2_eod;	// External class reference
	class SWLB_clone_base_P2;	// External class reference
	class SWLB_clone_base_P1;	// External class reference
	class SWLB_clone_assault_base_P2;	// External class reference
	class SWLB_clone_cfr_base_P2;	// External class reference
	class SWLB_clone_medic_base_P2;	// External class reference
	class SWLB_clone_RTO_base_P2;	// External class reference
	class SWLB_clone_recon_base_P2;	// External class reference
	class SWLB_clone_recon_nco_base_P2;	// External class reference
	class SWLB_clone_recon_officer_base_P2;	// External class reference
	class SWLB_clone_airborne_base_P2;	// External class reference
	class SWLB_clone_airborne_nco_base_P2;	// External class reference
	class SWLB_clone_lieutenant_base_P2;	// External class reference
	class SWLB_clone_captain_base_P2;	// External class reference
	class SWLB_clone_commander_base_P2;	// External class reference
	class SWLB_clone_marshal_commander_base_P2;	// External class reference
	class SWLB_clone_arc_base_P2;	// External class reference
	class SWLB_clone_pilot_base_P2;	// External class reference
	class SWLB_clone_sniper_base_P2;	// External class reference
	class SWLB_clone_sg_base_P2;	// External class reference
	class SWLB_clone_at_base_P2;	// External class reference
	class SWLB_clone_backpack;	// External class reference
	class SWLB_clone_backpack_eod;	// External class reference
	class SWLB_clone_backpack_heavy;	// External class reference
	class SWLB_mando_base_assault;	// External class reference
	class SWLB_clone_backpack_RTO;	// External class reference
	class SWLB_mando_rangefinder;	// External class reference
	class SWLB_clone_rangefinder;	// External class reference
	class SWLB_clone_RTO_mini_backpack;	// External class reference
	class SWLB_clone_uniform;	// External class reference
	
	class Skink : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Skink)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Skink";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Skink.paa", "501_Unit\data\501_Armor2_Skink.paa"};
		linkedItems[] = {"501_HelmetP1_Skink", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Skink", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Husky : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Husky)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Husky";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Husky.paa", "501_Unit\data\501_Armor2_Husky.paa"};
		linkedItems[] = {"501_HelmetP1_Husky", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Husky", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Glyba : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Glyba)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Glyba";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Glyba.paa", "501_Unit\data\501_Armor2_Glyba.paa"};
		linkedItems[] = {"501_HelmetP1_Glyba", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Glyba", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Liver : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Liver)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Liver";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Liver.paa", "501_Unit\data\501_Armor2_Liver.paa"};
		linkedItems[] = {"501_HelmetP1_Liver", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Liver", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Flin : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Flin)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Flin";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Flin.paa", "501_Unit\data\501_Armor2_Flin.paa"};
		linkedItems[] = {"501_HelmetP1_Flin", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Flin", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Tron : SWLB_clone_marshal_commander_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Tron)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Tron";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1MC_Tron.paa", "501_Unit\data\501_Armor2MC_Tron.paa"};
		linkedItems[] = {"501_HelmetP1_Tron", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Tron", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Fren : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Fren)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Fren";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Fren.paa", "501_Unit\data\501_Armor2_Fren.paa"};
		linkedItems[] = {"501_HelmetP1_Fren", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Fren", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Dok : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Dok)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Dok";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Dok.paa", "501_Unit\data\501_Armor2_Dok.paa"};
		linkedItems[] = {"501_HelmetP1_Dok", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Dok", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Radaga : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Radaga)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Radaga";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Radaga.paa", "501_Unit\data\501_Armor2_Radaga.paa"};
		linkedItems[] = {"501_HelmetP1_Kira", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Kira", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Kira : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Kira)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Kira";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Kira.paa", "501_Unit\data\501_Armor2_Kira.paa"};
		linkedItems[] = {"501_HelmetP1_Kira", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Kira", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Bjorn : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Bjorn)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Bjorn";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Bjorn.paa", "501_Unit\data\501_Armor2_Bjorn.paa"};
		linkedItems[] = {"501_HelmetP1_Bjorn", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Bjorn", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Mali : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Mali)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Mali";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Mali.paa", "501_Unit\data\501_Armor2_Mali.paa"};
		linkedItems[] = {"501_HelmetP1_Mali", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Mali", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Draxler : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Draxler)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Draxler";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Draxler.paa", "501_Unit\data\501_Armor2_Draxler.paa"};
		linkedItems[] = {"501_HelmetARF_Draxler", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetARF_Draxler", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Olaf : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Olaf)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Olaf";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Olaf.paa", "501_Unit\data\501_Armor2_Olaf.paa"};
		linkedItems[] = {"501_HelmetP1_Olaf", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Olaf", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Oni : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Oni)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Oni";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Oni.paa", "501_Unit\data\501_Armor2_Oni.paa"};
		linkedItems[] = {"501_HelmetP1_Oni", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Oni", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Kid : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Kid)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Kid";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Kid.paa", "501_Unit\data\501_Armor2_Kid.paa"};
		linkedItems[] = {"501_HelmetP1_Kid", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Kid", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
	
	class Grif : SWLB_clone_base_P2 {
		author = "LastWar Team";
		displayName = "501st Clone Trooper (Grif)";
		faction = "LW_Faction";
		editorSubcategory = "501_Legion";
		uniformclass = "Grif";
		hiddenSelectionsTextures[] = {"501_Unit\data\501_Armor1_Grif.paa", "501_Unit\data\501_Armor2_Grif.paa"};
		linkedItems[] = {"501_HelmetP1_Grif", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
		respawnLinkedItems[] = {"501_HelmetP1_Grif", "ItemMap", "ItemCompass", "ItemWatch", "SWLB_comlink"};
	};
};

class cfgMods {
	author = "Last Force Project";
	timepacked = 1594648166;
};
