// config.bin - 23:40:05 07/23/20, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class SWLW_WestarM5 {
		requiredAddons[] = {"A3_Data_F", "A3_Weapons_F", "SWLW_main", "SWLW_clones", "SWLW_clones_smgs"};
		requiredVersion = 0.1;
		units[] = {"LW_GH_WestarM5"};
		weapons[] = {"LW_WestarM5", "LW_WestarM5_ugl", "SWLW_WestarM5_scope"};
	};
};

class CfgAmmo {
	class SWLW_ammo_smg_blue;	// External class reference
	
	class LW_ammo_hi_blue : SWLW_ammo_smg_blue {
		hit = 25;
		typicalspeed = 300;
		caliber = 1.4;
		model = "SWLW_main\Effects\laser_blue.p3d";
		dangerRadiusBulletClose = 4;
		dangerRadiusHit = 8;
		suppressionRadiusBulletClose = 2;
		suppressionRadiusHit = 4;
		audibleFire = 45;
		airFriction = 0;
		timetolive = 6;
		effectfly = "SWLW_plasma_blue";
	};
	
	class LW_ammo_low_blue : SWLW_ammo_smg_blue {
		hit = 15;
		typicalspeed = 300;
		caliber = 1.4;
		model = "SWLW_main\Effects\laser_blue.p3d";
		dangerRadiusBulletClose = 4;
		dangerRadiusHit = 8;
		suppressionRadiusBulletClose = 2;
		suppressionRadiusHit = 4;
		audibleFire = 45;
		airFriction = 0;
		timetolive = 6;
		effectfly = "SWLW_plasma_blue";
	};
};

class CfgMagazines {
	class SWLW_mag_base;	// External class reference
	
	class LW_WestarM5_low_Mag : SWLW_mag_base {
		author = "SW Legion Studios";
		scope = 2;
		tracersEvery = 1;
		type = 16;
		mass = 10;
		initSpeed = 310;
		picture = "\SWLW_clones\smgs\westar_m5\data\ui\WestarM5_mag_ui.paa";
		displayName = "Westar M5 low energy plasma cell (100rnd)";
		ammo = "LW_ammo_low_blue";
		count = 100;
		descriptionShort = "100rnd low energy cell for Westar M5";
		model = "SWLW_clones\smgs\westar_m5\WestarM5_mag.p3d";
	};
	
	class LW_WestarM5_hi_Mag : LW_WestarM5_low_Mag {
		displayName = "Westar M5 plasma cell (60rnd)";
		descriptionShort = "60rnd energy cell for Westar M5";
		count = 60;
		ammo = "LW_ammo_hi_blue";
	};
};
class Mode_SemiAuto;	// External class reference
class Mode_FullAuto;	// External class reference
class SlotInfo;	// External class reference
class CowsSlot;	// External class reference
class MuzzleSlot;	// External class reference

class CfgWeapons {
	class ItemCore;	// External class reference
	class InventoryItem_Base_F;	// External class reference
	class InventoryOpticsItem_Base_F;	// External class reference
	class Rifle_Long_Base_F;	// External class reference
	class UGL_F;	// External class reference
	
	class SWLW_rifle_base : Rifle_Long_Base_F {
		scope = 1;
		
		class WeaponSlotsInfo {
			class SlotInfo;	// External class reference
		};
		class GunParticles;	// External class reference
		class AnimationSources;	// External class reference
	};
	
	class LW_WestarM5 : SWLW_rifle_base {
		scope = 2;
		model = "\SWLW_clones\smgs\westar_m5\WestarM5.p3d";
		handAnim[] = {"OFP2_ManSkeleton", "\SWLW_clones\smgs\westar_m5\anims\westarm5_handanim.rtm"};
		reloadAction = "ReloadMagazine";
		picture = "\SWLW_clones\smgs\westar_m5\data\ui\WestarM5_ui.paa";
		magazines[] = {"LW_WestarM5_low_Mag", "LW_WestarM5_hi_Mag"};
		displayname = "Westar M5";
		descriptionShort = "";
		selectionFireAnim = "zasleh";
		
		class Library {
			libTextDesc = "";
		};
		drySound[] = {"", 0.398107, 1, 20};
		reloadMagazineSound[] = {"\SWLW_clones\pistols\dc17\sounds\DC17_reload.wss", 0.562341, 1, 30};
		soundBullet[] = {};
		modes[] = {"Single", "FullAuto", "close", "short", "medium"};
		recoil = "SWLW_recoil";
		fireLightDuration = 0.05;
		fireLightIntensity = 0.4;
		fireLightDiffuse[] = {0, 0, 0.01};
		fireLightAmbient[] = {0, 0, 0};
		
		class Single : Mode_SemiAuto {
			sounds[] = {"StandardSound"};
			
			class BaseSoundModeType {
				weaponSoundEffect = "";
				closure1[] = {};
				closure2[] = {};
				soundClosure[] = {};
			};
			
			class StandardSound : BaseSoundModeType {
				weaponSoundEffect = "";
				begin1[] = {"\SWLW_clones\smgs\dc15s\sounds\DC15S_2", 1, 1, 1800};
				begin2[] = {"\SWLW_clones\smgs\dc15s\sounds\DC15S_2", 1, 1, 1800};
				begin3[] = {"\SWLW_clones\smgs\dc15s\sounds\DC15S_3", 1, 1, 1800};
				soundBegin[] = {"begin1", 0.33, "begin2", 0.33, "begin3", 0.33};
			};
			reloadTime = 0.15;
			dispersion = 0.002;
			minRange = 5;
			minRangeProbab = 0.3;
			midRange = 25;
			midRangeProbab = 0.6;
			maxRange = 50;
			maxRangeProbab = 0.1;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 25;
		};
		
		class FullAuto : Mode_FullAuto {
			sounds[] = {"StandardSound"};
			
			class BaseSoundModeType {
				weaponSoundEffect = "";
				closure1[] = {};
				closure2[] = {};
				soundClosure[] = {};
			};
			
			class StandardSound : BaseSoundModeType {
				weaponSoundEffect = "";
				begin1[] = {"\SWLW_clones\smgs\dc15s\sounds\DC15S_1", 1, 1, 1800};
				begin2[] = {"\SWLW_clones\smgs\dc15s\sounds\DC15S_2", 1, 1, 1800};
				begin3[] = {"\SWLW_clones\smgs\dc15s\sounds\DC15S_3", 1, 1, 1800};
				soundBegin[] = {"begin1", 0.33, "begin2", 0.33, "begin3", 0.33};
			};
			reloadTime = 0.15;
			dispersion = 0.0014545;
			minRange = 5;
			minRangeProbab = 0.3;
			midRange = 25;
			midRangeProbab = 0.6;
			maxRange = 50;
			maxRangeProbab = 0.1;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 25;
		};
		
		class close : Single {
			showToPlayer = 0;
			aiRateOfFire = 0.25;
			aiRateOfFireDistance = 400;
			minRange = 0;
			minRangeProbab = 0.05;
			midRange = 200;
			midRangeProbab = 0.7;
			maxRange = 400;
			maxRangeProbab = 0.2;
		};
		
		class short : close {
			aiRateOfFire = 0.5;
			aiRateOfFireDistance = 500;
			minRange = 300;
			minRangeProbab = 0.2;
			midRange = 400;
			midRangeProbab = 0.7;
			maxRange = 500;
			maxRangeProbab = 0.2;
		};
		
		class medium : close {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 900;
			minRange = 400;
			minRangeProbab = 0.2;
			midRange = 700;
			midRangeProbab = 0.7;
			maxRange = 900;
			maxRangeProbab = 0.2;
		};
		inertia = 0.3;
		dexterity = 1.7;
		initSpeed = 400;
		
		class WeaponSlotsInfo : WeaponSlotsInfo {
			mass = 80;
			
			class CowsSlot : CowsSlot {
				compatibleItems[] = {"SWLW_WestarM5_scope"};
			};
		};
	};
	
	class LW_WestarM5_ugl : LW_WestarM5 {
		displayName = "Westar M-5 (UGL)";
		model = "\SWLW_clones\smgs\westar_m5\WestarM5_ugl.p3d";
		muzzles[] = {this, EGLM};
		handAnim[] = {"OFP2_ManSkeleton", "\SWLW_clones\smgs\westar_m5\anims\westarm5_ugl_handanim.rtm"};
		
		class EGLM : UGL_F {
			displayName = "1rnd HE launcher";
			descriptionShort = "";
			useModelOptics = 0;
			useExternalOptic = 0;
			initspeed = 75;
			magazines[] = {"SWLW_WestarM5_g_Mag", "RD501_AT_GL_x2_mag", "RD501_HE_GL_x3_mag"};
			magazineWell[] = {};
			cameraDir = "OP_look";
			discreteDistance[] = {100};
			discreteDistanceCameraPoint[] = {"OP_eye"};
			discreteDistanceInitIndex = 1;
		};
	};
};

class CfgVehicles {
	class Weapon_Base_F;	// External class reference
	
	class LW_GH_WestarM5 : Weapon_Base_F {
		author = "SW Legion Studios";
		displayName = "Westar M5";
		scope = 2;
		
		class TransportWeapons {
			class SWLW_WestarM5 {
				count = 1;
				weapon = "LW_WestarM5";
			};
		};
		
		class TransportMagazines {
			class SWLW_WestarM5_Mag {
				count = 1;
				magazine = "LW_WestarM5_low_Mag";
			};
		};
	};
};

class cfgMods {
	author = "Last Force Project";
	timepacked = 1594648269;
};
